*&---------------------------------------------------------------------*
*&  Include           /ADESSO/INKASSO_MONITOR_SCR
*&---------------------------------------------------------------------*

*************************************************************************
* Selektionsbildschirm
*************************************************************************
* Funktionstaste 1 anlegen (FC01)
SELECTION-SCREEN: FUNCTION KEY 1.


SELECTION-SCREEN BEGIN OF BLOCK sel WITH FRAME TITLE TEXT-b01.
SELECT-OPTIONS: so_bukrs FOR wa_fkkop-bukrs NO-DISPLAY,
                so_gpart FOR wa_fkkop-gpart,
                so_vkont FOR wa_fkkop-vkont,
                so_vktyp FOR wa_fkkvk-vktyp,                    "Nuss 04.2018
                so_regio FOR wa_fkkvkp-regiogr_ca_b,
                so_name1 FOR wa_name,
                so_lockr FOR wa_fkkvkp-mansp,
                so_spart FOR wa_fkkop-spart.                    "Nuss 04.2018
PARAMETERS:     p_ovrdue(3) TYPE n.

SELECT-OPTIONS: so_vtref FOR wa_fkkop-vtref NO-DISPLAY,
                so_opbel FOR wa_fkkop-opbel NO-DISPLAY,
                so_faedn FOR wa_fkkop-faedn NO-DISPLAY,
                so_mahns FOR wa_fkkmaze-mahns NO-DISPLAY,
                so_mahnv FOR wa_fkkmaze-mahnv NO-DISPLAY.

PARAMETERS:     p_lockr     LIKE fkkvkp-mansp DEFAULT '§' NO-DISPLAY.


SELECTION-SCREEN END OF BLOCK sel.

SELECTION-SCREEN BEGIN OF BLOCK opt1 WITH FRAME TITLE TEXT-b02.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_xagapi AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_xagapi.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_reca   AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_reca.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_vorm   AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_vorm.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_xnewin  AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_xnewin.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_look   AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_look.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_chkd   AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_chkd.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_frei   AS CHECKBOX.    "Nuss 05.2018
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_frei.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK opt1.


SELECTION-SCREEN BEGIN OF BLOCK opt2 WITH FRAME TITLE TEXT-b03.

SELECT-OPTIONS: so_agdat FOR wa_out-agdat MODIF ID inf.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(15) TEXT-lst MODIF ID inf.
SELECTION-SCREEN COMMENT 20(10) datinfos MODIF ID inf.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_infos  AS CHECKBOX MODIF ID inf.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_infos MODIF ID inf.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(15) TEXT-lst MODIF ID inf.
SELECTION-SCREEN COMMENT 20(10) datinfgp MODIF ID inf.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_infgp  AS CHECKBOX MODIF ID inf.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_infgp MODIF ID inf.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK opt21 WITH FRAME TITLE TEXT-b04.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_xrview  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_xrview.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_xagip  AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_xagip.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_xinspl  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_xinspl.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_xopwo  AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_xopwo.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK opt21.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK opt22 WITH FRAME TITLE TEXT-b05.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_xfact  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_xfact.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_abbri   AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_abbri.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_apprse  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_apprse.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_apprwo   AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_apprwo.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_sell  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_sell.
SELECTION-SCREEN POSITION 33.
PARAMETERS: p_wroff  AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD p_wroff.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_dsel  AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_dsel.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK opt22.

SELECT-OPTIONS: so_xagip FOR wa_dfkkcoll-agsta NO-DISPLAY.
SELECT-OPTIONS: so_xopwo FOR wa_dfkkcoll-agsta NO-DISPLAY.
SELECT-OPTIONS: so_aggrd FOR wa_dfkkcoll-aggrd NO-DISPLAY.

SELECTION-SCREEN END OF BLOCK opt2.


selection-screen begin of block aus with frame title TEXT-300.
PARAMETERS: p_vari LIKE disvariant-variant MODIF ID out.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_hier RADIOBUTTON GROUP alv DEFAULT 'X' MODIF ID out.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_hier MODIF ID out.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_liste RADIOBUTTON GROUP out DEFAULT 'X' MODIF ID out.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD pa_liste MODIF ID out.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_alv  RADIOBUTTON GROUP alv MODIF ID out.
SELECTION-SCREEN COMMENT 5(25) FOR FIELD p_alv MODIF ID out.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_showh RADIOBUTTON GROUP out MODIF ID out.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD pa_showh MODIF ID out.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_updhi RADIOBUTTON GROUP out MODIF ID out.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD pa_updhi MODIF ID out.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK aus.

SELECTION-SCREEN BEGIN OF BLOCK vor WITH FRAME TITLE TEXT-004.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(40) TEXT-102 MODIF ID pre.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(60) TEXT-100 MODIF ID pre.
PARAMETERS:  p_check  AS CHECKBOX MODIF ID pre.
SELECTION-SCREEN END OF LINE.
* --> Nuss 06.2018
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(60) TEXT-103 MODIF ID pre.
PARAMETERS p_acccha AS CHECKBOX MODIF ID pre.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK vor.
* <-- Nuss 06.2018
