*&---------------------------------------------------------------------*
*&  Include           /ADESSO/MT_BEL_LOADWB_SEL
*&---------------------------------------------------------------------*


*----------------------------------------------------------------------
* SELEKTIONSBILDSCHIM
*----------------------------------------------------------------------

* Grundeinstellungen (Firma, Exportpfad, Extension Export, Importpfad)
SELECTION-SCREEN BEGIN OF BLOCK a WITH FRAME TITLE text-b01.
SELECTION-SCREEN BEGIN OF BLOCK aa WITH FRAME TITLE text-b02.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(22) text-p01.

PARAMETERS: firma LIKE temfd-firma.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK aa.
SELECTION-SCREEN BEGIN OF BLOCK ab WITH FRAME TITLE text-b03.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(22) text-p02.

PARAMETERS: exp_path LIKE temfd-path.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(22) text-p03.
PARAMETERS: exp_ext(3) TYPE c DEFAULT 'EXP'.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK ab.
SELECTION-SCREEN BEGIN OF BLOCK ac WITH FRAME TITLE text-b04.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(22) text-p04.

PARAMETERS: imp_path LIKE temfd-path.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(22) text-p05.
PARAMETERS: imp_ext(3) TYPE c DEFAULT 'IMP'.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK ac.
SELECTION-SCREEN END OF BLOCK a.

* Migrations-Objekte
SELECTION-SCREEN BEGIN OF BLOCK b WITH FRAME TITLE text-b05.
*Partner
SELECTION-SCREEN BEGIN OF BLOCK bpar WITH FRAME TITLE text-par.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_par LIKE temfd-file DEFAULT 'PARTNER'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_par AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpar.
*Partnernotizen
SELECTION-SCREEN BEGIN OF BLOCK bpno WITH FRAME TITLE text-pno.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pno LIKE temfd-file DEFAULT 'PARTN_NOTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pno AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpno.
*Portionen
SELECTION-SCREEN BEGIN OF BLOCK b420 WITH FRAME TITLE text-420.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_420 LIKE temfd-file DEFAULT 'BDC_TE420'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_420 AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b420.
*Ableseeinheiten
SELECTION-SCREEN BEGIN OF BLOCK bmru WITH FRAME TITLE text-mru.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_mru LIKE temfd-file DEFAULT 'BDC_MRUNIT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_mru AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bmru.
*Anschlußobjekt
SELECTION-SCREEN BEGIN OF BLOCK bcon WITH FRAME TITLE text-con.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_con LIKE temfd-file DEFAULT 'CONNOBJ'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_con AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bcon.
*Notizen zum Anschlußobjekt (Außendiensthinweise)
SELECTION-SCREEN BEGIN OF BLOCK bcno WITH FRAME TITLE text-cno.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_cno LIKE temfd-file DEFAULT 'CON_NOTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_cno AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bcno.
*Hinweise zum Anschlußobjekt (Außendiensthinweise)
SELECTION-SCREEN BEGIN OF BLOCK bnoc WITH FRAME TITLE text-noc.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_noc LIKE temfd-file DEFAULT 'NOTE_CON'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_noc AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bnoc.
*Verbrauchsstelle
SELECTION-SCREEN BEGIN OF BLOCK bpre WITH FRAME TITLE text-pre.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pre LIKE temfd-file DEFAULT 'PREMISE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pre AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpre.
*Geräteplatz
SELECTION-SCREEN BEGIN OF BLOCK bdlc WITH FRAME TITLE text-dlc.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dlc LIKE temfd-file DEFAULT 'DEVLOC'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dlc AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdlc.
*Hinweise zum Geräteplatz (Außendiensthinweise)
SELECTION-SCREEN BEGIN OF BLOCK bnod WITH FRAME TITLE text-nod.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_nod LIKE temfd-file DEFAULT 'NOTE_DLC'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_nod AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bnod.
*Notizen zum Geräteplatz
SELECTION-SCREEN BEGIN OF BLOCK bdno WITH FRAME TITLE text-dno.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dno LIKE temfd-file DEFAULT 'DLC_NOTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dno AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdno.
*Stichprobenlos
SELECTION-SCREEN BEGIN OF BLOCK blot WITH FRAME TITLE text-lot.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_lot LIKE temfd-file DEFAULT 'LOT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_lot AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK blot.
*Gerätegruppierung
SELECTION-SCREEN BEGIN OF BLOCK bdgr WITH FRAME TITLE text-dgr.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dgr LIKE temfd-file DEFAULT 'DEVGRP'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dgr AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdgr.
*Geräte
SELECTION-SCREEN BEGIN OF BLOCK bdev WITH FRAME TITLE text-dev.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dev LIKE temfd-file DEFAULT 'DEVICE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dev AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdev.
*Geräteinfosätze
SELECTION-SCREEN BEGIN OF BLOCK bdir WITH FRAME TITLE text-dir.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dir LIKE temfd-file DEFAULT 'DEVINFOREC'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dir AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdir.
*Anlagen
SELECTION-SCREEN BEGIN OF BLOCK bins WITH FRAME TITLE text-ins.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_ins LIKE temfd-file DEFAULT 'INSTLN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_ins AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bins.
*Anlagenänderung
SELECTION-SCREEN BEGIN OF BLOCK bich WITH FRAME TITLE text-ich.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_ich LIKE temfd-file DEFAULT 'INSTLNCHA'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_ich AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bich.
*Anlagen (NN)
SELECTION-SCREEN BEGIN OF BLOCK binn WITH FRAME TITLE text-inn.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_inn LIKE temfd-file DEFAULT 'INSTLN_NN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_inn AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK binn.
*Anlagenänderung (NN)
SELECTION-SCREEN BEGIN OF BLOCK bicn WITH FRAME TITLE text-icn.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_icn LIKE temfd-file DEFAULT 'INSTLNCHNN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_icn AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bicn.
*Fakten
SELECTION-SCREEN BEGIN OF BLOCK bfac WITH FRAME TITLE text-fac.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_fac LIKE temfd-file DEFAULT 'FACTS'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_fac AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bfac.
*Zählpunkt (Point of Delivery)
SELECTION-SCREEN BEGIN OF BLOCK bpod WITH FRAME TITLE text-pod.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pod LIKE temfd-file DEFAULT 'POD'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pod AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpod.
*Ändern Zählpunkt
SELECTION-SCREEN BEGIN OF BLOCK bpoc WITH FRAME TITLE text-poc.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_poc LIKE temfd-file DEFAULT 'PODCHANGE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_poc AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpoc.
*Zählpunktservice
SELECTION-SCREEN BEGIN OF BLOCK bpos WITH FRAME TITLE text-pos.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pos LIKE temfd-file DEFAULT 'PODSERVICE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pos AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpos.
*Bezugsgrößen
SELECTION-SCREEN BEGIN OF BLOCK brva WITH FRAME TITLE text-rva.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_rva LIKE temfd-file DEFAULT 'REFVALUES'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_rva AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK brva.
*Lastprofil zu Anlage
SELECTION-SCREEN BEGIN OF BLOCK blop WITH FRAME TITLE text-lop.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_lop LIKE temfd-file DEFAULT 'LOADPROF'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_lop AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK blop.
*Vertragskonto
SELECTION-SCREEN BEGIN OF BLOCK bacc WITH FRAME TITLE text-acc.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_acc LIKE temfd-file DEFAULT 'ACCOUNT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_acc AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bacc.
*Vertragskonto für Sammler
SELECTION-SCREEN BEGIN OF BLOCK bacs WITH FRAME TITLE text-acs.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_acs LIKE temfd-file DEFAULT 'ACCOUNTS'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_acs AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bacs.
*Notizen zum Vertragskonto
SELECTION-SCREEN BEGIN OF BLOCK bacn WITH FRAME TITLE text-acn.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_acn LIKE temfd-file DEFAULT 'ACC_NOTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_acn AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bacn.
*Einzug / Versorgungsvertrag
SELECTION-SCREEN BEGIN OF BLOCK bmoi WITH FRAME TITLE text-moi.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_moi LIKE temfd-file DEFAULT 'MOVE_IN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_moi AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bmoi.
*Einzug / historischer Versorgungsvertrag
SELECTION-SCREEN BEGIN OF BLOCK bmoh WITH FRAME TITLE text-moh.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_moh LIKE temfd-file DEFAULT 'MOVE_IN_H'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_moh AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bmoh.
*Auszug
SELECTION-SCREEN BEGIN OF BLOCK bmoo WITH FRAME TITLE text-moo.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_moo LIKE temfd-file DEFAULT 'MOVE_OUT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_moo AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bmoo.
*Kundenkontakt
SELECTION-SCREEN BEGIN OF BLOCK bbct WITH FRAME TITLE text-bct.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_bct LIKE temfd-file DEFAULT 'BCONTACT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_bct AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bbct.
*Notizen zum Kundenkontakt
SELECTION-SCREEN BEGIN OF BLOCK bbcn WITH FRAME TITLE text-bcn.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_bcn LIKE temfd-file DEFAULT 'BCONT_NOTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_bcn AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bbcn.
*Abschlagsplan
SELECTION-SCREEN BEGIN OF BLOCK bbpm WITH FRAME TITLE text-bpm.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_bpm LIKE temfd-file DEFAULT 'BBP_MULT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_bpm AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bbpm.
*Zahlungen
SELECTION-SCREEN BEGIN OF BLOCK bpay WITH FRAME TITLE text-pay.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pay LIKE temfd-file DEFAULT 'PAYMENT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pay AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpay.
*offene Posten
SELECTION-SCREEN BEGIN OF BLOCK bdoc WITH FRAME TITLE text-doc.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_doc LIKE temfd-file DEFAULT 'DOCUMENT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_doc AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdoc.
*Ratenplan
SELECTION-SCREEN BEGIN OF BLOCK bipl WITH FRAME TITLE text-ipl.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_ipl LIKE temfd-file DEFAULT 'INSTPLAN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_ipl AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bipl.
*Sperrbeleg anlegen
SELECTION-SCREEN BEGIN OF BLOCK bdcd WITH FRAME TITLE text-dcd.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dcd LIKE temfd-file DEFAULT 'DISC_DOC'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dcd AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdcd.
*Sperrauftrag anlegen
SELECTION-SCREEN BEGIN OF BLOCK bdco WITH FRAME TITLE text-dco.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dco LIKE temfd-file DEFAULT 'DISC_ORDER'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dco AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdco.
*Sperrung erfassen
SELECTION-SCREEN BEGIN OF BLOCK bdce WITH FRAME TITLE text-dce.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dce LIKE temfd-file DEFAULT 'DISC_ENTER'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dce AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdce.
*Wiederinbetriebnahmeauftrag anlegen
SELECTION-SCREEN BEGIN OF BLOCK bdcr WITH FRAME TITLE text-dcr.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dcr LIKE temfd-file DEFAULT 'DISC_RCORD'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dcr AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdcr.
*Wiederinbetriebnahme anlegen
SELECTION-SCREEN BEGIN OF BLOCK bdcm WITH FRAME TITLE text-dcm.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_dcm LIKE temfd-file DEFAULT 'DISC_RCENT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_dcm AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdcm.
*Geräteeinbau /-ausbau /-wechsel (Installations-Management)
SELECTION-SCREEN BEGIN OF BLOCK binm WITH FRAME TITLE text-inm.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_inm LIKE temfd-file DEFAULT 'INST_MGMT'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_inm AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK binm.
*Zählerstand anlegen
SELECTION-SCREEN BEGIN OF BLOCK bmrd WITH FRAME TITLE text-mrd.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_mrd LIKE temfd-file DEFAULT 'METERREAD'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_mrd AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bmrd.
*Tarifdaten zur Anlagenstruktur ändern
SELECTION-SCREEN BEGIN OF BLOCK bdrt WITH FRAME TITLE text-drt.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_drt LIKE temfd-file DEFAULT 'DEVICERATE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_drt AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bdrt.
*Anlegen Kopfdaten zum EDM-Profil
SELECTION-SCREEN BEGIN OF BLOCK bphd WITH FRAME TITLE text-phd.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_phd LIKE temfd-file DEFAULT 'PROFHEAD'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_phd AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bphd.
*Zuordnung Zählwerk - EDM Profil
SELECTION-SCREEN BEGIN OF BLOCK bpas WITH FRAME TITLE text-pas.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_pas LIKE temfd-file DEFAULT 'PROFASSIGN'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_pas AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bpas.
*Anlegen Zählwerksbeziehungen
SELECTION-SCREEN BEGIN OF BLOCK brrl WITH FRAME TITLE text-rrl.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_rrl LIKE temfd-file DEFAULT 'REGRELSHIP'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_rrl AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK brrl.
*Ablesereihenfolge
SELECTION-SCREEN BEGIN OF BLOCK bsrt WITH FRAME TITLE text-srt.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_srt LIKE temfd-file DEFAULT 'STRT_ROUTE'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_srt AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bsrt.

* Anlegen der Regionalstruktur   19.03.2008_kb
SELECTION-SCREEN BEGIN OF BLOCK regio WITH FRAME TITLE text-reg.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(18) text-obj.
PARAMETERS: dat_reg LIKE temfd-file DEFAULT 'ADRSTREET'.
SELECTION-SCREEN COMMENT 42(12) text-001.
PARAMETERS: obj_reg AS CHECKBOX.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK regio.

SELECTION-SCREEN END OF BLOCK b.
