*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 22.03.2016 at 15:51:09 by user THIMEL.R
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZAGC_MRCONTACT..................................*
FORM GET_DATA_ZAGC_MRCONTACT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /IDXGC/MRCONTACT WHERE
(VIM_WHERETAB) .
    CLEAR ZAGC_MRCONTACT .
ZAGC_MRCONTACT-MANDT =
/IDXGC/MRCONTACT-MANDT .
ZAGC_MRCONTACT-ANLAGE =
/IDXGC/MRCONTACT-ANLAGE .
ZAGC_MRCONTACT-FROMDATE =
/IDXGC/MRCONTACT-FROMDATE .
ZAGC_MRCONTACT-TODATE =
/IDXGC/MRCONTACT-TODATE .
ZAGC_MRCONTACT-CONTACT_BP =
/IDXGC/MRCONTACT-CONTACT_BP .
ZAGC_MRCONTACT-CR_NAME =
/IDXGC/MRCONTACT-CR_NAME .
ZAGC_MRCONTACT-CR_DATE =
/IDXGC/MRCONTACT-CR_DATE .
ZAGC_MRCONTACT-CR_TIME =
/IDXGC/MRCONTACT-CR_TIME .
ZAGC_MRCONTACT-CH_NAME =
/IDXGC/MRCONTACT-CH_NAME .
ZAGC_MRCONTACT-CH_DATE =
/IDXGC/MRCONTACT-CH_DATE .
ZAGC_MRCONTACT-CH_TIME =
/IDXGC/MRCONTACT-CH_TIME .
<VIM_TOTAL_STRUC> = ZAGC_MRCONTACT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZAGC_MRCONTACT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZAGC_MRCONTACT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZAGC_MRCONTACT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /IDXGC/MRCONTACT WHERE
  ANLAGE = ZAGC_MRCONTACT-ANLAGE AND
  FROMDATE = ZAGC_MRCONTACT-FROMDATE .
    IF SY-SUBRC = 0.
    DELETE /IDXGC/MRCONTACT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /IDXGC/MRCONTACT WHERE
  ANLAGE = ZAGC_MRCONTACT-ANLAGE AND
  FROMDATE = ZAGC_MRCONTACT-FROMDATE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /IDXGC/MRCONTACT.
    ENDIF.
/IDXGC/MRCONTACT-MANDT =
ZAGC_MRCONTACT-MANDT .
/IDXGC/MRCONTACT-ANLAGE =
ZAGC_MRCONTACT-ANLAGE .
/IDXGC/MRCONTACT-FROMDATE =
ZAGC_MRCONTACT-FROMDATE .
/IDXGC/MRCONTACT-TODATE =
ZAGC_MRCONTACT-TODATE .
/IDXGC/MRCONTACT-CONTACT_BP =
ZAGC_MRCONTACT-CONTACT_BP .
/IDXGC/MRCONTACT-CR_NAME =
ZAGC_MRCONTACT-CR_NAME .
/IDXGC/MRCONTACT-CR_DATE =
ZAGC_MRCONTACT-CR_DATE .
/IDXGC/MRCONTACT-CR_TIME =
ZAGC_MRCONTACT-CR_TIME .
/IDXGC/MRCONTACT-CH_NAME =
ZAGC_MRCONTACT-CH_NAME .
/IDXGC/MRCONTACT-CH_DATE =
ZAGC_MRCONTACT-CH_DATE .
/IDXGC/MRCONTACT-CH_TIME =
ZAGC_MRCONTACT-CH_TIME .
    IF SY-SUBRC = 0.
    UPDATE /IDXGC/MRCONTACT .
    ELSE.
    INSERT /IDXGC/MRCONTACT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZAGC_MRCONTACT-UPD_FLAG,
STATUS_ZAGC_MRCONTACT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZAGC_MRCONTACT.
  SELECT SINGLE * FROM /IDXGC/MRCONTACT WHERE
ANLAGE = ZAGC_MRCONTACT-ANLAGE AND
FROMDATE = ZAGC_MRCONTACT-FROMDATE .
ZAGC_MRCONTACT-MANDT =
/IDXGC/MRCONTACT-MANDT .
ZAGC_MRCONTACT-ANLAGE =
/IDXGC/MRCONTACT-ANLAGE .
ZAGC_MRCONTACT-FROMDATE =
/IDXGC/MRCONTACT-FROMDATE .
ZAGC_MRCONTACT-TODATE =
/IDXGC/MRCONTACT-TODATE .
ZAGC_MRCONTACT-CONTACT_BP =
/IDXGC/MRCONTACT-CONTACT_BP .
ZAGC_MRCONTACT-CR_NAME =
/IDXGC/MRCONTACT-CR_NAME .
ZAGC_MRCONTACT-CR_DATE =
/IDXGC/MRCONTACT-CR_DATE .
ZAGC_MRCONTACT-CR_TIME =
/IDXGC/MRCONTACT-CR_TIME .
ZAGC_MRCONTACT-CH_NAME =
/IDXGC/MRCONTACT-CH_NAME .
ZAGC_MRCONTACT-CH_DATE =
/IDXGC/MRCONTACT-CH_DATE .
ZAGC_MRCONTACT-CH_TIME =
/IDXGC/MRCONTACT-CH_TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZAGC_MRCONTACT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZAGC_MRCONTACT-ANLAGE TO
/IDXGC/MRCONTACT-ANLAGE .
MOVE ZAGC_MRCONTACT-FROMDATE TO
/IDXGC/MRCONTACT-FROMDATE .
MOVE ZAGC_MRCONTACT-MANDT TO
/IDXGC/MRCONTACT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/IDXGC/MRCONTACT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /IDXGC/MRCONTACT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/IDXGC/MRCONTACT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
