*&---------------------------------------------------------------------*
*&  Include           /IDXGC/RP_PDOC_CREATE_BDR_SEL
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK gb_hdr WITH FRAME TITLE text-bk1.

*SELECTION-SCREEN COMMENT 1(50) TEXT-t20. "unschoen
**
*SELECTION-SCREEN BEGIN OF LINE.
*MESSAGE 'Success!' TYPE 'I'.
*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK gb_hdr.


*Zweiter Textblock

SELECTION-SCREEN BEGIN OF BLOCK gb_msg WITH FRAME TITLE TEXT-bk2.


SELECTION-SCREEN BEGIN OF LINE.
DATA mdolc TYPE ext_ui.
SELECTION-SCREEN COMMENT 1(39) TEXT-t04.
SELECT-OPTIONS marloc FOR mdolc.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(42) TEXT-z05 FOR Field aus.
PARAMETERS: aus TYPE /idxgc/de_proc_date.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(42) TEXT-t06.
PARAMETERS: bilanz TYPE /IDXGC/DE_SETTL_PROC.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK gb_msg.
