*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 13.06.2017 at 16:33:06
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_IA................................*
FORM GET_DATA_/ADESSO/V_MDC_IA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_INA WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_IA .
/ADESSO/V_MDC_IA-MANDT =
/ADESSO/MDC_INA-MANDT .
/ADESSO/V_MDC_IA-EDIFACT_STRUCTUR =
/ADESSO/MDC_INA-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_IA-VALID_FROM =
/ADESSO/MDC_INA-VALID_FROM .
/ADESSO/V_MDC_IA-MP_GROUP_NO =
/ADESSO/MDC_INA-MP_GROUP_NO .
/ADESSO/V_MDC_IA-AUTO_CHANGE =
/ADESSO/MDC_INA-AUTO_CHANGE .
/ADESSO/V_MDC_IA-AUTO_CHANGE_RESPONSE =
/ADESSO/MDC_INA-AUTO_CHANGE_RESPONSE .
/ADESSO/V_MDC_IA-AUTO_CHANGE_DELAY =
/ADESSO/MDC_INA-AUTO_CHANGE_DELAY .
/ADESSO/V_MDC_IA-BADI_NAME =
/ADESSO/MDC_INA-BADI_NAME .
/ADESSO/V_MDC_IA-USER_COMMENT =
/ADESSO/MDC_INA-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_IA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_IA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_IA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_IA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_INA WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_IA-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_IA-VALID_FROM AND
  MP_GROUP_NO = /ADESSO/V_MDC_IA-MP_GROUP_NO .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_INA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_INA WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_IA-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_IA-VALID_FROM AND
  MP_GROUP_NO = /ADESSO/V_MDC_IA-MP_GROUP_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_INA.
    ENDIF.
/ADESSO/MDC_INA-MANDT =
/ADESSO/V_MDC_IA-MANDT .
/ADESSO/MDC_INA-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_IA-EDIFACT_STRUCTUR .
/ADESSO/MDC_INA-VALID_FROM =
/ADESSO/V_MDC_IA-VALID_FROM .
/ADESSO/MDC_INA-MP_GROUP_NO =
/ADESSO/V_MDC_IA-MP_GROUP_NO .
/ADESSO/MDC_INA-AUTO_CHANGE =
/ADESSO/V_MDC_IA-AUTO_CHANGE .
/ADESSO/MDC_INA-AUTO_CHANGE_RESPONSE =
/ADESSO/V_MDC_IA-AUTO_CHANGE_RESPONSE .
/ADESSO/MDC_INA-AUTO_CHANGE_DELAY =
/ADESSO/V_MDC_IA-AUTO_CHANGE_DELAY .
/ADESSO/MDC_INA-BADI_NAME =
/ADESSO/V_MDC_IA-BADI_NAME .
/ADESSO/MDC_INA-USER_COMMENT =
/ADESSO/V_MDC_IA-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_INA .
    ELSE.
    INSERT /ADESSO/MDC_INA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_IA-UPD_FLAG,
STATUS_/ADESSO/V_MDC_IA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_IA.
  SELECT SINGLE * FROM /ADESSO/MDC_INA WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_IA-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_IA-VALID_FROM AND
MP_GROUP_NO = /ADESSO/V_MDC_IA-MP_GROUP_NO .
/ADESSO/V_MDC_IA-MANDT =
/ADESSO/MDC_INA-MANDT .
/ADESSO/V_MDC_IA-EDIFACT_STRUCTUR =
/ADESSO/MDC_INA-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_IA-VALID_FROM =
/ADESSO/MDC_INA-VALID_FROM .
/ADESSO/V_MDC_IA-MP_GROUP_NO =
/ADESSO/MDC_INA-MP_GROUP_NO .
/ADESSO/V_MDC_IA-AUTO_CHANGE =
/ADESSO/MDC_INA-AUTO_CHANGE .
/ADESSO/V_MDC_IA-AUTO_CHANGE_RESPONSE =
/ADESSO/MDC_INA-AUTO_CHANGE_RESPONSE .
/ADESSO/V_MDC_IA-AUTO_CHANGE_DELAY =
/ADESSO/MDC_INA-AUTO_CHANGE_DELAY .
/ADESSO/V_MDC_IA-BADI_NAME =
/ADESSO/MDC_INA-BADI_NAME .
/ADESSO/V_MDC_IA-USER_COMMENT =
/ADESSO/MDC_INA-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_IA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_IA-EDIFACT_STRUCTUR TO
/ADESSO/MDC_INA-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_IA-VALID_FROM TO
/ADESSO/MDC_INA-VALID_FROM .
MOVE /ADESSO/V_MDC_IA-MP_GROUP_NO TO
/ADESSO/MDC_INA-MP_GROUP_NO .
MOVE /ADESSO/V_MDC_IA-MANDT TO
/ADESSO/MDC_INA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_INA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_INA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_INA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_IN................................*
FORM GET_DATA_/ADESSO/V_MDC_IN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_IN WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_IN .
/ADESSO/V_MDC_IN-MANDT =
/ADESSO/MDC_IN-MANDT .
/ADESSO/V_MDC_IN-EDIFACT_STRUCTUR =
/ADESSO/MDC_IN-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_IN-VALID_FROM =
/ADESSO/MDC_IN-VALID_FROM .
/ADESSO/V_MDC_IN-AUTO_CHANGE =
/ADESSO/MDC_IN-AUTO_CHANGE .
/ADESSO/V_MDC_IN-AUTO_CHANGE_RESPONSE =
/ADESSO/MDC_IN-AUTO_CHANGE_RESPONSE .
/ADESSO/V_MDC_IN-AUTO_CHANGE_DELAY =
/ADESSO/MDC_IN-AUTO_CHANGE_DELAY .
/ADESSO/V_MDC_IN-BADI_NAME =
/ADESSO/MDC_IN-BADI_NAME .
/ADESSO/V_MDC_IN-USER_COMMENT =
/ADESSO/MDC_IN-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_IN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_IN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_IN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_IN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_IN WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_IN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_IN-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_IN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_IN WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_IN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_IN-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_IN.
    ENDIF.
/ADESSO/MDC_IN-MANDT =
/ADESSO/V_MDC_IN-MANDT .
/ADESSO/MDC_IN-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_IN-EDIFACT_STRUCTUR .
/ADESSO/MDC_IN-VALID_FROM =
/ADESSO/V_MDC_IN-VALID_FROM .
/ADESSO/MDC_IN-AUTO_CHANGE =
/ADESSO/V_MDC_IN-AUTO_CHANGE .
/ADESSO/MDC_IN-AUTO_CHANGE_RESPONSE =
/ADESSO/V_MDC_IN-AUTO_CHANGE_RESPONSE .
/ADESSO/MDC_IN-AUTO_CHANGE_DELAY =
/ADESSO/V_MDC_IN-AUTO_CHANGE_DELAY .
/ADESSO/MDC_IN-BADI_NAME =
/ADESSO/V_MDC_IN-BADI_NAME .
/ADESSO/MDC_IN-USER_COMMENT =
/ADESSO/V_MDC_IN-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_IN .
    ELSE.
    INSERT /ADESSO/MDC_IN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_IN-UPD_FLAG,
STATUS_/ADESSO/V_MDC_IN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_IN.
  SELECT SINGLE * FROM /ADESSO/MDC_IN WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_IN-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_IN-VALID_FROM .
/ADESSO/V_MDC_IN-MANDT =
/ADESSO/MDC_IN-MANDT .
/ADESSO/V_MDC_IN-EDIFACT_STRUCTUR =
/ADESSO/MDC_IN-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_IN-VALID_FROM =
/ADESSO/MDC_IN-VALID_FROM .
/ADESSO/V_MDC_IN-AUTO_CHANGE =
/ADESSO/MDC_IN-AUTO_CHANGE .
/ADESSO/V_MDC_IN-AUTO_CHANGE_RESPONSE =
/ADESSO/MDC_IN-AUTO_CHANGE_RESPONSE .
/ADESSO/V_MDC_IN-AUTO_CHANGE_DELAY =
/ADESSO/MDC_IN-AUTO_CHANGE_DELAY .
/ADESSO/V_MDC_IN-BADI_NAME =
/ADESSO/MDC_IN-BADI_NAME .
/ADESSO/V_MDC_IN-USER_COMMENT =
/ADESSO/MDC_IN-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_IN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_IN-EDIFACT_STRUCTUR TO
/ADESSO/MDC_IN-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_IN-VALID_FROM TO
/ADESSO/MDC_IN-VALID_FROM .
MOVE /ADESSO/V_MDC_IN-MANDT TO
/ADESSO/MDC_IN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_IN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_IN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_IN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_MA................................*
FORM GET_DATA_/ADESSO/V_MDC_MA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_MAIN WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_MA .
/ADESSO/V_MDC_MA-MANDT =
/ADESSO/MDC_MAIN-MANDT .
/ADESSO/V_MDC_MA-GLOBAL_INTCODE =
/ADESSO/MDC_MAIN-GLOBAL_INTCODE .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_MA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_MA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_MA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_MA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MAIN WHERE
  GLOBAL_INTCODE = /ADESSO/V_MDC_MA-GLOBAL_INTCODE .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_MAIN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MAIN WHERE
  GLOBAL_INTCODE = /ADESSO/V_MDC_MA-GLOBAL_INTCODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_MAIN.
    ENDIF.
/ADESSO/MDC_MAIN-MANDT =
/ADESSO/V_MDC_MA-MANDT .
/ADESSO/MDC_MAIN-GLOBAL_INTCODE =
/ADESSO/V_MDC_MA-GLOBAL_INTCODE .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_MAIN .
    ELSE.
    INSERT /ADESSO/MDC_MAIN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_MA-UPD_FLAG,
STATUS_/ADESSO/V_MDC_MA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_MA.
  SELECT SINGLE * FROM /ADESSO/MDC_MAIN WHERE
GLOBAL_INTCODE = /ADESSO/V_MDC_MA-GLOBAL_INTCODE .
/ADESSO/V_MDC_MA-MANDT =
/ADESSO/MDC_MAIN-MANDT .
/ADESSO/V_MDC_MA-GLOBAL_INTCODE =
/ADESSO/MDC_MAIN-GLOBAL_INTCODE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_MA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_MA-GLOBAL_INTCODE TO
/ADESSO/MDC_MAIN-GLOBAL_INTCODE .
MOVE /ADESSO/V_MDC_MA-MANDT TO
/ADESSO/MDC_MAIN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_MAIN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_MAIN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_MAIN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_MG................................*
FORM GET_DATA_/ADESSO/V_MDC_MG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_MPGR WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_MG .
/ADESSO/V_MDC_MG-MANDT =
/ADESSO/MDC_MPGR-MANDT .
/ADESSO/V_MDC_MG-MP_GROUP_NO =
/ADESSO/MDC_MPGR-MP_GROUP_NO .
/ADESSO/V_MDC_MG-MP_GROUP_TYPE =
/ADESSO/MDC_MPGR-MP_GROUP_TYPE .
/ADESSO/V_MDC_MG-USER_COMMENT =
/ADESSO/MDC_MPGR-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_MG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_MG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_MG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_MG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MPGR WHERE
  MP_GROUP_NO = /ADESSO/V_MDC_MG-MP_GROUP_NO .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_MPGR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MPGR WHERE
  MP_GROUP_NO = /ADESSO/V_MDC_MG-MP_GROUP_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_MPGR.
    ENDIF.
/ADESSO/MDC_MPGR-MANDT =
/ADESSO/V_MDC_MG-MANDT .
/ADESSO/MDC_MPGR-MP_GROUP_NO =
/ADESSO/V_MDC_MG-MP_GROUP_NO .
/ADESSO/MDC_MPGR-MP_GROUP_TYPE =
/ADESSO/V_MDC_MG-MP_GROUP_TYPE .
/ADESSO/MDC_MPGR-USER_COMMENT =
/ADESSO/V_MDC_MG-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_MPGR .
    ELSE.
    INSERT /ADESSO/MDC_MPGR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_MG-UPD_FLAG,
STATUS_/ADESSO/V_MDC_MG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_MG.
  SELECT SINGLE * FROM /ADESSO/MDC_MPGR WHERE
MP_GROUP_NO = /ADESSO/V_MDC_MG-MP_GROUP_NO .
/ADESSO/V_MDC_MG-MANDT =
/ADESSO/MDC_MPGR-MANDT .
/ADESSO/V_MDC_MG-MP_GROUP_NO =
/ADESSO/MDC_MPGR-MP_GROUP_NO .
/ADESSO/V_MDC_MG-MP_GROUP_TYPE =
/ADESSO/MDC_MPGR-MP_GROUP_TYPE .
/ADESSO/V_MDC_MG-USER_COMMENT =
/ADESSO/MDC_MPGR-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_MG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_MG-MP_GROUP_NO TO
/ADESSO/MDC_MPGR-MP_GROUP_NO .
MOVE /ADESSO/V_MDC_MG-MANDT TO
/ADESSO/MDC_MPGR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_MPGR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_MPGR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_MPGR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_MS................................*
FORM GET_DATA_/ADESSO/V_MDC_MS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_MPSP WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_MS .
/ADESSO/V_MDC_MS-MANDT =
/ADESSO/MDC_MPSP-MANDT .
/ADESSO/V_MDC_MS-MP_GROUP_NO =
/ADESSO/MDC_MPSP-MP_GROUP_NO .
/ADESSO/V_MDC_MS-SERVPROV =
/ADESSO/MDC_MPSP-SERVPROV .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_MS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_MS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_MS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_MS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MPSP WHERE
  MP_GROUP_NO = /ADESSO/V_MDC_MS-MP_GROUP_NO AND
  SERVPROV = /ADESSO/V_MDC_MS-SERVPROV .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_MPSP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_MPSP WHERE
  MP_GROUP_NO = /ADESSO/V_MDC_MS-MP_GROUP_NO AND
  SERVPROV = /ADESSO/V_MDC_MS-SERVPROV .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_MPSP.
    ENDIF.
/ADESSO/MDC_MPSP-MANDT =
/ADESSO/V_MDC_MS-MANDT .
/ADESSO/MDC_MPSP-MP_GROUP_NO =
/ADESSO/V_MDC_MS-MP_GROUP_NO .
/ADESSO/MDC_MPSP-SERVPROV =
/ADESSO/V_MDC_MS-SERVPROV .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_MPSP .
    ELSE.
    INSERT /ADESSO/MDC_MPSP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_MS-UPD_FLAG,
STATUS_/ADESSO/V_MDC_MS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_MS.
  SELECT SINGLE * FROM /ADESSO/MDC_MPSP WHERE
MP_GROUP_NO = /ADESSO/V_MDC_MS-MP_GROUP_NO AND
SERVPROV = /ADESSO/V_MDC_MS-SERVPROV .
/ADESSO/V_MDC_MS-MANDT =
/ADESSO/MDC_MPSP-MANDT .
/ADESSO/V_MDC_MS-MP_GROUP_NO =
/ADESSO/MDC_MPSP-MP_GROUP_NO .
/ADESSO/V_MDC_MS-SERVPROV =
/ADESSO/MDC_MPSP-SERVPROV .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_MS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_MS-MP_GROUP_NO TO
/ADESSO/MDC_MPSP-MP_GROUP_NO .
MOVE /ADESSO/V_MDC_MS-SERVPROV TO
/ADESSO/MDC_MPSP-SERVPROV .
MOVE /ADESSO/V_MDC_MS-MANDT TO
/ADESSO/MDC_MPSP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_MPSP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_MPSP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_MPSP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_OP................................*
FORM GET_DATA_/ADESSO/V_MDC_OP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_ODP WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_OP .
/ADESSO/V_MDC_OP-AMID =
/ADESSO/MDC_ODP-AMID .
/ADESSO/V_MDC_OP-VALID_FROM =
/ADESSO/MDC_ODP-VALID_FROM .
/ADESSO/V_MDC_OP-EDIFACT_STRUCTUR =
/ADESSO/MDC_ODP-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_OP-DP_CONDITION =
/ADESSO/MDC_ODP-DP_CONDITION .
/ADESSO/V_MDC_OP-SOURCE_DP_CLASS =
/ADESSO/MDC_ODP-SOURCE_DP_CLASS .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_OP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_OP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_OP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_OP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_ODP WHERE
  AMID = /ADESSO/V_MDC_OP-AMID AND
  VALID_FROM = /ADESSO/V_MDC_OP-VALID_FROM AND
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_OP-EDIFACT_STRUCTUR .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_ODP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_ODP WHERE
  AMID = /ADESSO/V_MDC_OP-AMID AND
  VALID_FROM = /ADESSO/V_MDC_OP-VALID_FROM AND
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_OP-EDIFACT_STRUCTUR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_ODP.
    ENDIF.
/ADESSO/MDC_ODP-AMID =
/ADESSO/V_MDC_OP-AMID .
/ADESSO/MDC_ODP-VALID_FROM =
/ADESSO/V_MDC_OP-VALID_FROM .
/ADESSO/MDC_ODP-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_OP-EDIFACT_STRUCTUR .
/ADESSO/MDC_ODP-DP_CONDITION =
/ADESSO/V_MDC_OP-DP_CONDITION .
/ADESSO/MDC_ODP-SOURCE_DP_CLASS =
/ADESSO/V_MDC_OP-SOURCE_DP_CLASS .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_ODP .
    ELSE.
    INSERT /ADESSO/MDC_ODP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_OP-UPD_FLAG,
STATUS_/ADESSO/V_MDC_OP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_OP.
  SELECT SINGLE * FROM /ADESSO/MDC_ODP WHERE
AMID = /ADESSO/V_MDC_OP-AMID AND
VALID_FROM = /ADESSO/V_MDC_OP-VALID_FROM AND
EDIFACT_STRUCTUR = /ADESSO/V_MDC_OP-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_OP-AMID =
/ADESSO/MDC_ODP-AMID .
/ADESSO/V_MDC_OP-VALID_FROM =
/ADESSO/MDC_ODP-VALID_FROM .
/ADESSO/V_MDC_OP-EDIFACT_STRUCTUR =
/ADESSO/MDC_ODP-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_OP-DP_CONDITION =
/ADESSO/MDC_ODP-DP_CONDITION .
/ADESSO/V_MDC_OP-SOURCE_DP_CLASS =
/ADESSO/MDC_ODP-SOURCE_DP_CLASS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_OP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_OP-AMID TO
/ADESSO/MDC_ODP-AMID .
MOVE /ADESSO/V_MDC_OP-VALID_FROM TO
/ADESSO/MDC_ODP-VALID_FROM .
MOVE /ADESSO/V_MDC_OP-EDIFACT_STRUCTUR TO
/ADESSO/MDC_ODP-EDIFACT_STRUCTUR .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_ODP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_ODP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_ODP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_OU................................*
FORM GET_DATA_/ADESSO/V_MDC_OU.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_OUT WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_OU .
/ADESSO/V_MDC_OU-AMID =
/ADESSO/MDC_OUT-AMID .
/ADESSO/V_MDC_OU-VALID_FROM =
/ADESSO/MDC_OUT-VALID_FROM .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_OU.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_OU .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_OU.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_OU-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_OUT WHERE
  AMID = /ADESSO/V_MDC_OU-AMID AND
  VALID_FROM = /ADESSO/V_MDC_OU-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_OUT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_OUT WHERE
  AMID = /ADESSO/V_MDC_OU-AMID AND
  VALID_FROM = /ADESSO/V_MDC_OU-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_OUT.
    ENDIF.
/ADESSO/MDC_OUT-AMID =
/ADESSO/V_MDC_OU-AMID .
/ADESSO/MDC_OUT-VALID_FROM =
/ADESSO/V_MDC_OU-VALID_FROM .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_OUT .
    ELSE.
    INSERT /ADESSO/MDC_OUT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_OU-UPD_FLAG,
STATUS_/ADESSO/V_MDC_OU-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_OU.
  SELECT SINGLE * FROM /ADESSO/MDC_OUT WHERE
AMID = /ADESSO/V_MDC_OU-AMID AND
VALID_FROM = /ADESSO/V_MDC_OU-VALID_FROM .
/ADESSO/V_MDC_OU-AMID =
/ADESSO/MDC_OUT-AMID .
/ADESSO/V_MDC_OU-VALID_FROM =
/ADESSO/MDC_OUT-VALID_FROM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_OU USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_OU-AMID TO
/ADESSO/MDC_OUT-AMID .
MOVE /ADESSO/V_MDC_OU-VALID_FROM TO
/ADESSO/MDC_OUT-VALID_FROM .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_OUT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_OUT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_OUT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_PD................................*
FORM GET_DATA_/ADESSO/V_MDC_PD.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_PDOC WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_PD .
/ADESSO/V_MDC_PD-PDOC_STEP_TABLE =
/ADESSO/MDC_PDOC-PDOC_STEP_TABLE .
/ADESSO/V_MDC_PD-PDOC_STEP_FIELD =
/ADESSO/MDC_PDOC-PDOC_STEP_FIELD .
/ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER =
/ADESSO/MDC_PDOC-PDOC_STEP_QUALIFIER .
/ADESSO/V_MDC_PD-EDIFACT_STRUCTUR =
/ADESSO/MDC_PDOC-EDIFACT_STRUCTUR .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_PD.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_PD .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_PD.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_PD-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_PDOC WHERE
  PDOC_STEP_TABLE = /ADESSO/V_MDC_PD-PDOC_STEP_TABLE AND
  PDOC_STEP_FIELD = /ADESSO/V_MDC_PD-PDOC_STEP_FIELD AND
  PDOC_STEP_QUALIFIER = /ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER AND
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_PD-EDIFACT_STRUCTUR .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_PDOC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_PDOC WHERE
  PDOC_STEP_TABLE = /ADESSO/V_MDC_PD-PDOC_STEP_TABLE AND
  PDOC_STEP_FIELD = /ADESSO/V_MDC_PD-PDOC_STEP_FIELD AND
  PDOC_STEP_QUALIFIER = /ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER AND
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_PD-EDIFACT_STRUCTUR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_PDOC.
    ENDIF.
/ADESSO/MDC_PDOC-PDOC_STEP_TABLE =
/ADESSO/V_MDC_PD-PDOC_STEP_TABLE .
/ADESSO/MDC_PDOC-PDOC_STEP_FIELD =
/ADESSO/V_MDC_PD-PDOC_STEP_FIELD .
/ADESSO/MDC_PDOC-PDOC_STEP_QUALIFIER =
/ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER .
/ADESSO/MDC_PDOC-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_PD-EDIFACT_STRUCTUR .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_PDOC .
    ELSE.
    INSERT /ADESSO/MDC_PDOC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_PD-UPD_FLAG,
STATUS_/ADESSO/V_MDC_PD-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_PD.
  SELECT SINGLE * FROM /ADESSO/MDC_PDOC WHERE
PDOC_STEP_TABLE = /ADESSO/V_MDC_PD-PDOC_STEP_TABLE AND
PDOC_STEP_FIELD = /ADESSO/V_MDC_PD-PDOC_STEP_FIELD AND
PDOC_STEP_QUALIFIER = /ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER AND
EDIFACT_STRUCTUR = /ADESSO/V_MDC_PD-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_PD-PDOC_STEP_TABLE =
/ADESSO/MDC_PDOC-PDOC_STEP_TABLE .
/ADESSO/V_MDC_PD-PDOC_STEP_FIELD =
/ADESSO/MDC_PDOC-PDOC_STEP_FIELD .
/ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER =
/ADESSO/MDC_PDOC-PDOC_STEP_QUALIFIER .
/ADESSO/V_MDC_PD-EDIFACT_STRUCTUR =
/ADESSO/MDC_PDOC-EDIFACT_STRUCTUR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_PD USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_PD-PDOC_STEP_TABLE TO
/ADESSO/MDC_PDOC-PDOC_STEP_TABLE .
MOVE /ADESSO/V_MDC_PD-PDOC_STEP_FIELD TO
/ADESSO/MDC_PDOC-PDOC_STEP_FIELD .
MOVE /ADESSO/V_MDC_PD-PDOC_STEP_QUALIFIER TO
/ADESSO/MDC_PDOC-PDOC_STEP_QUALIFIER .
MOVE /ADESSO/V_MDC_PD-EDIFACT_STRUCTUR TO
/ADESSO/MDC_PDOC-EDIFACT_STRUCTUR .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_PDOC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_PDOC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_PDOC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_RE................................*
FORM GET_DATA_/ADESSO/V_MDC_RE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_RAED WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_RE .
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR =
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_RE-VALID_FROM =
/ADESSO/MDC_RAED-VALID_FROM .
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD =
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR_ADD .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_RE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_RE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_RE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_RE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_RAED WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_RE-VALID_FROM AND
  EDIFACT_STRUCTUR_ADD = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_RAED .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_RAED WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_RE-VALID_FROM AND
  EDIFACT_STRUCTUR_ADD = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_RAED.
    ENDIF.
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR .
/ADESSO/MDC_RAED-VALID_FROM =
/ADESSO/V_MDC_RE-VALID_FROM .
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR_ADD =
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_RAED .
    ELSE.
    INSERT /ADESSO/MDC_RAED .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_RE-UPD_FLAG,
STATUS_/ADESSO/V_MDC_RE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_RE.
  SELECT SINGLE * FROM /ADESSO/MDC_RAED WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_RE-VALID_FROM AND
EDIFACT_STRUCTUR_ADD = /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD .
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR =
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_RE-VALID_FROM =
/ADESSO/MDC_RAED-VALID_FROM .
/ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD =
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR_ADD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_RE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR TO
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_RE-VALID_FROM TO
/ADESSO/MDC_RAED-VALID_FROM .
MOVE /ADESSO/V_MDC_RE-EDIFACT_STRUCTUR_ADD TO
/ADESSO/MDC_RAED-EDIFACT_STRUCTUR_ADD .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_RAED'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_RAED TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_RAED'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_RI................................*
FORM GET_DATA_/ADESSO/V_MDC_RI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_RAID WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_RI .
/ADESSO/V_MDC_RI-EDIFACT_STRUCTUR =
/ADESSO/MDC_RAID-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_RI-VALID_FROM =
/ADESSO/MDC_RAID-VALID_FROM .
/ADESSO/V_MDC_RI-DISTRIBUTOR_ROLE =
/ADESSO/MDC_RAID-DISTRIBUTOR_ROLE .
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_SUPPLIER =
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_SUPPLIER .
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_MOS =
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_MOS .
/ADESSO/V_MDC_RI-SUPPLIER_ROLE =
/ADESSO/MDC_RAID-SUPPLIER_ROLE .
/ADESSO/V_MDC_RI-SUPPLIER_AMID =
/ADESSO/MDC_RAID-SUPPLIER_AMID .
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_ROLE =
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_ROLE .
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_AMID =
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_AMID .
/ADESSO/V_MDC_RI-FEEDER_ROLE =
/ADESSO/MDC_RAID-FEEDER_ROLE .
/ADESSO/V_MDC_RI-FEEDER_AMID =
/ADESSO/MDC_RAID-FEEDER_AMID .
/ADESSO/V_MDC_RI-FEEDER_FUTURE_ROLE =
/ADESSO/MDC_RAID-FEEDER_FUTURE_ROLE .
/ADESSO/V_MDC_RI-FEEDER_FUTURE_AMID =
/ADESSO/MDC_RAID-FEEDER_FUTURE_AMID .
/ADESSO/V_MDC_RI-MOS_ROLE =
/ADESSO/MDC_RAID-MOS_ROLE .
/ADESSO/V_MDC_RI-MOS_AMID =
/ADESSO/MDC_RAID-MOS_AMID .
/ADESSO/V_MDC_RI-BMOS_ROLE =
/ADESSO/MDC_RAID-BMOS_ROLE .
/ADESSO/V_MDC_RI-BMOS_AMID =
/ADESSO/MDC_RAID-BMOS_AMID .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_RI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_RI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_RI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_RI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_RAID WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_RI-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_RI-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_RAID .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_RAID WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_RI-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_RI-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_RAID.
    ENDIF.
/ADESSO/MDC_RAID-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_RI-EDIFACT_STRUCTUR .
/ADESSO/MDC_RAID-VALID_FROM =
/ADESSO/V_MDC_RI-VALID_FROM .
/ADESSO/MDC_RAID-DISTRIBUTOR_ROLE =
/ADESSO/V_MDC_RI-DISTRIBUTOR_ROLE .
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_SUPPLIER =
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_SUPPLIER .
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_MOS =
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_MOS .
/ADESSO/MDC_RAID-SUPPLIER_ROLE =
/ADESSO/V_MDC_RI-SUPPLIER_ROLE .
/ADESSO/MDC_RAID-SUPPLIER_AMID =
/ADESSO/V_MDC_RI-SUPPLIER_AMID .
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_ROLE =
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_ROLE .
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_AMID =
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_AMID .
/ADESSO/MDC_RAID-FEEDER_ROLE =
/ADESSO/V_MDC_RI-FEEDER_ROLE .
/ADESSO/MDC_RAID-FEEDER_AMID =
/ADESSO/V_MDC_RI-FEEDER_AMID .
/ADESSO/MDC_RAID-FEEDER_FUTURE_ROLE =
/ADESSO/V_MDC_RI-FEEDER_FUTURE_ROLE .
/ADESSO/MDC_RAID-FEEDER_FUTURE_AMID =
/ADESSO/V_MDC_RI-FEEDER_FUTURE_AMID .
/ADESSO/MDC_RAID-MOS_ROLE =
/ADESSO/V_MDC_RI-MOS_ROLE .
/ADESSO/MDC_RAID-MOS_AMID =
/ADESSO/V_MDC_RI-MOS_AMID .
/ADESSO/MDC_RAID-BMOS_ROLE =
/ADESSO/V_MDC_RI-BMOS_ROLE .
/ADESSO/MDC_RAID-BMOS_AMID =
/ADESSO/V_MDC_RI-BMOS_AMID .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_RAID .
    ELSE.
    INSERT /ADESSO/MDC_RAID .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_RI-UPD_FLAG,
STATUS_/ADESSO/V_MDC_RI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_RI.
  SELECT SINGLE * FROM /ADESSO/MDC_RAID WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_RI-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_RI-VALID_FROM .
/ADESSO/V_MDC_RI-EDIFACT_STRUCTUR =
/ADESSO/MDC_RAID-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_RI-VALID_FROM =
/ADESSO/MDC_RAID-VALID_FROM .
/ADESSO/V_MDC_RI-DISTRIBUTOR_ROLE =
/ADESSO/MDC_RAID-DISTRIBUTOR_ROLE .
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_SUPPLIER =
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_SUPPLIER .
/ADESSO/V_MDC_RI-DISTRIBUTOR_AMID_MOS =
/ADESSO/MDC_RAID-DISTRIBUTOR_AMID_MOS .
/ADESSO/V_MDC_RI-SUPPLIER_ROLE =
/ADESSO/MDC_RAID-SUPPLIER_ROLE .
/ADESSO/V_MDC_RI-SUPPLIER_AMID =
/ADESSO/MDC_RAID-SUPPLIER_AMID .
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_ROLE =
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_ROLE .
/ADESSO/V_MDC_RI-SUPPLIER_FUTURE_AMID =
/ADESSO/MDC_RAID-SUPPLIER_FUTURE_AMID .
/ADESSO/V_MDC_RI-FEEDER_ROLE =
/ADESSO/MDC_RAID-FEEDER_ROLE .
/ADESSO/V_MDC_RI-FEEDER_AMID =
/ADESSO/MDC_RAID-FEEDER_AMID .
/ADESSO/V_MDC_RI-FEEDER_FUTURE_ROLE =
/ADESSO/MDC_RAID-FEEDER_FUTURE_ROLE .
/ADESSO/V_MDC_RI-FEEDER_FUTURE_AMID =
/ADESSO/MDC_RAID-FEEDER_FUTURE_AMID .
/ADESSO/V_MDC_RI-MOS_ROLE =
/ADESSO/MDC_RAID-MOS_ROLE .
/ADESSO/V_MDC_RI-MOS_AMID =
/ADESSO/MDC_RAID-MOS_AMID .
/ADESSO/V_MDC_RI-BMOS_ROLE =
/ADESSO/MDC_RAID-BMOS_ROLE .
/ADESSO/V_MDC_RI-BMOS_AMID =
/ADESSO/MDC_RAID-BMOS_AMID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_RI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_RI-EDIFACT_STRUCTUR TO
/ADESSO/MDC_RAID-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_RI-VALID_FROM TO
/ADESSO/MDC_RAID-VALID_FROM .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_RAID'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_RAID TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_RAID'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_SA................................*
FORM GET_DATA_/ADESSO/V_MDC_SA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_SNDA WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_SA .
/ADESSO/V_MDC_SA-MANDT =
/ADESSO/MDC_SNDA-MANDT .
/ADESSO/V_MDC_SA-EDIFACT_STRUCTUR =
/ADESSO/MDC_SNDA-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_SA-VALID_FROM =
/ADESSO/MDC_SNDA-VALID_FROM .
/ADESSO/V_MDC_SA-MP_GROUP_NO =
/ADESSO/MDC_SNDA-MP_GROUP_NO .
/ADESSO/V_MDC_SA-SEND =
/ADESSO/MDC_SNDA-SEND .
/ADESSO/V_MDC_SA-SEND_DELAY =
/ADESSO/MDC_SNDA-SEND_DELAY .
/ADESSO/V_MDC_SA-USER_COMMENT =
/ADESSO/MDC_SNDA-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_SA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_SA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_SA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_SA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_SNDA WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_SA-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_SA-VALID_FROM AND
  MP_GROUP_NO = /ADESSO/V_MDC_SA-MP_GROUP_NO .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_SNDA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_SNDA WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_SA-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_SA-VALID_FROM AND
  MP_GROUP_NO = /ADESSO/V_MDC_SA-MP_GROUP_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_SNDA.
    ENDIF.
/ADESSO/MDC_SNDA-MANDT =
/ADESSO/V_MDC_SA-MANDT .
/ADESSO/MDC_SNDA-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_SA-EDIFACT_STRUCTUR .
/ADESSO/MDC_SNDA-VALID_FROM =
/ADESSO/V_MDC_SA-VALID_FROM .
/ADESSO/MDC_SNDA-MP_GROUP_NO =
/ADESSO/V_MDC_SA-MP_GROUP_NO .
/ADESSO/MDC_SNDA-SEND =
/ADESSO/V_MDC_SA-SEND .
/ADESSO/MDC_SNDA-SEND_DELAY =
/ADESSO/V_MDC_SA-SEND_DELAY .
/ADESSO/MDC_SNDA-USER_COMMENT =
/ADESSO/V_MDC_SA-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_SNDA .
    ELSE.
    INSERT /ADESSO/MDC_SNDA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_SA-UPD_FLAG,
STATUS_/ADESSO/V_MDC_SA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_SA.
  SELECT SINGLE * FROM /ADESSO/MDC_SNDA WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_SA-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_SA-VALID_FROM AND
MP_GROUP_NO = /ADESSO/V_MDC_SA-MP_GROUP_NO .
/ADESSO/V_MDC_SA-MANDT =
/ADESSO/MDC_SNDA-MANDT .
/ADESSO/V_MDC_SA-EDIFACT_STRUCTUR =
/ADESSO/MDC_SNDA-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_SA-VALID_FROM =
/ADESSO/MDC_SNDA-VALID_FROM .
/ADESSO/V_MDC_SA-MP_GROUP_NO =
/ADESSO/MDC_SNDA-MP_GROUP_NO .
/ADESSO/V_MDC_SA-SEND =
/ADESSO/MDC_SNDA-SEND .
/ADESSO/V_MDC_SA-SEND_DELAY =
/ADESSO/MDC_SNDA-SEND_DELAY .
/ADESSO/V_MDC_SA-USER_COMMENT =
/ADESSO/MDC_SNDA-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_SA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_SA-EDIFACT_STRUCTUR TO
/ADESSO/MDC_SNDA-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_SA-VALID_FROM TO
/ADESSO/MDC_SNDA-VALID_FROM .
MOVE /ADESSO/V_MDC_SA-MP_GROUP_NO TO
/ADESSO/MDC_SNDA-MP_GROUP_NO .
MOVE /ADESSO/V_MDC_SA-MANDT TO
/ADESSO/MDC_SNDA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_SNDA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_SNDA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_SNDA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_MDC_SN................................*
FORM GET_DATA_/ADESSO/V_MDC_SN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/MDC_SND WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_MDC_SN .
/ADESSO/V_MDC_SN-MANDT =
/ADESSO/MDC_SND-MANDT .
/ADESSO/V_MDC_SN-EDIFACT_STRUCTUR =
/ADESSO/MDC_SND-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_SN-VALID_FROM =
/ADESSO/MDC_SND-VALID_FROM .
/ADESSO/V_MDC_SN-SEND =
/ADESSO/MDC_SND-SEND .
/ADESSO/V_MDC_SN-SEND_DELAY =
/ADESSO/MDC_SND-SEND_DELAY .
/ADESSO/V_MDC_SN-USER_COMMENT =
/ADESSO/MDC_SND-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_MDC_SN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_MDC_SN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_MDC_SN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_MDC_SN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_SND WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_SN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_SN-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/MDC_SND .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/MDC_SND WHERE
  EDIFACT_STRUCTUR = /ADESSO/V_MDC_SN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADESSO/V_MDC_SN-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/MDC_SND.
    ENDIF.
/ADESSO/MDC_SND-MANDT =
/ADESSO/V_MDC_SN-MANDT .
/ADESSO/MDC_SND-EDIFACT_STRUCTUR =
/ADESSO/V_MDC_SN-EDIFACT_STRUCTUR .
/ADESSO/MDC_SND-VALID_FROM =
/ADESSO/V_MDC_SN-VALID_FROM .
/ADESSO/MDC_SND-SEND =
/ADESSO/V_MDC_SN-SEND .
/ADESSO/MDC_SND-SEND_DELAY =
/ADESSO/V_MDC_SN-SEND_DELAY .
/ADESSO/MDC_SND-USER_COMMENT =
/ADESSO/V_MDC_SN-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/MDC_SND .
    ELSE.
    INSERT /ADESSO/MDC_SND .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_MDC_SN-UPD_FLAG,
STATUS_/ADESSO/V_MDC_SN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_MDC_SN.
  SELECT SINGLE * FROM /ADESSO/MDC_SND WHERE
EDIFACT_STRUCTUR = /ADESSO/V_MDC_SN-EDIFACT_STRUCTUR AND
VALID_FROM = /ADESSO/V_MDC_SN-VALID_FROM .
/ADESSO/V_MDC_SN-MANDT =
/ADESSO/MDC_SND-MANDT .
/ADESSO/V_MDC_SN-EDIFACT_STRUCTUR =
/ADESSO/MDC_SND-EDIFACT_STRUCTUR .
/ADESSO/V_MDC_SN-VALID_FROM =
/ADESSO/MDC_SND-VALID_FROM .
/ADESSO/V_MDC_SN-SEND =
/ADESSO/MDC_SND-SEND .
/ADESSO/V_MDC_SN-SEND_DELAY =
/ADESSO/MDC_SND-SEND_DELAY .
/ADESSO/V_MDC_SN-USER_COMMENT =
/ADESSO/MDC_SND-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_MDC_SN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_MDC_SN-EDIFACT_STRUCTUR TO
/ADESSO/MDC_SND-EDIFACT_STRUCTUR .
MOVE /ADESSO/V_MDC_SN-VALID_FROM TO
/ADESSO/MDC_SND-VALID_FROM .
MOVE /ADESSO/V_MDC_SN-MANDT TO
/ADESSO/MDC_SND-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/MDC_SND'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/MDC_SND TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/MDC_SND'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
