*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 13.06.2017 at 16:33:06
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/MDC_ODPM................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_ODPM              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_ODPM              .
CONTROLS: TCTRL_/ADESSO/MDC_ODPM
            TYPE TABLEVIEW USING SCREEN '0016'.
*...processing: /ADESSO/MDC_OFRW................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_OFRW              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_OFRW              .
CONTROLS: TCTRL_/ADESSO/MDC_OFRW
            TYPE TABLEVIEW USING SCREEN '0004'.
*...processing: /ADESSO/MDC_ORSP................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_ORSP              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_ORSP              .
CONTROLS: TCTRL_/ADESSO/MDC_ORSP
            TYPE TABLEVIEW USING SCREEN '0003'.
*...processing: /ADESSO/MDC_OUT.................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_OUT               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_OUT               .
CONTROLS: TCTRL_/ADESSO/MDC_OUT
            TYPE TABLEVIEW USING SCREEN '0001'.
*...processing: /ADESSO/MDC_PDOC................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_PDOC              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_PDOC              .
CONTROLS: TCTRL_/ADESSO/MDC_PDOC
            TYPE TABLEVIEW USING SCREEN '0033'.
*...processing: /ADESSO/MDC_PQAL................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_PQAL              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_PQAL              .
CONTROLS: TCTRL_/ADESSO/MDC_PQAL
            TYPE TABLEVIEW USING SCREEN '0014'.
*...processing: /ADESSO/MDC_SND.................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_SND               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_SND               .
CONTROLS: TCTRL_/ADESSO/MDC_SND
            TYPE TABLEVIEW USING SCREEN '0011'.
*...processing: /ADESSO/MDC_SNDA................................*
DATA:  BEGIN OF STATUS_/ADESSO/MDC_SNDA              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/ADESSO/MDC_SNDA              .
CONTROLS: TCTRL_/ADESSO/MDC_SNDA
            TYPE TABLEVIEW USING SCREEN '0010'.
*...processing: /ADESSO/V_MDC_IA................................*
TABLES: /ADESSO/V_MDC_IA, */ADESSO/V_MDC_IA. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_IA
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_IA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_IA.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_IA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_IA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_IA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_IA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_IA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_IA_TOTAL.

*...processing: /ADESSO/V_MDC_IN................................*
TABLES: /ADESSO/V_MDC_IN, */ADESSO/V_MDC_IN. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_IN
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_IN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_IN.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_IN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_IN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_IN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_IN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_IN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_IN_TOTAL.

*...processing: /ADESSO/V_MDC_MA................................*
TABLES: /ADESSO/V_MDC_MA, */ADESSO/V_MDC_MA. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_MA
TYPE TABLEVIEW USING SCREEN '0027'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_MA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_MA.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_MA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_MA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MA_TOTAL.

*...processing: /ADESSO/V_MDC_MG................................*
TABLES: /ADESSO/V_MDC_MG, */ADESSO/V_MDC_MG. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_MG
TYPE TABLEVIEW USING SCREEN '0024'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_MG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_MG.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_MG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_MG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MG_TOTAL.

*...processing: /ADESSO/V_MDC_MS................................*
TABLES: /ADESSO/V_MDC_MS, */ADESSO/V_MDC_MS. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_MS
TYPE TABLEVIEW USING SCREEN '0026'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_MS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_MS.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_MS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_MS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_MS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_MS_TOTAL.

*...processing: /ADESSO/V_MDC_OP................................*
TABLES: /ADESSO/V_MDC_OP, */ADESSO/V_MDC_OP. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_OP
TYPE TABLEVIEW USING SCREEN '0029'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_OP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_OP.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_OP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_OP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_OP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_OP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_OP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_OP_TOTAL.

*...processing: /ADESSO/V_MDC_OU................................*
TABLES: /ADESSO/V_MDC_OU, */ADESSO/V_MDC_OU. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_OU
TYPE TABLEVIEW USING SCREEN '0031'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_OU. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_OU.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_OU_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_OU_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_OU_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_OU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_OU_TOTAL.

*...processing: /ADESSO/V_MDC_PD................................*
TABLES: /ADESSO/V_MDC_PD, */ADESSO/V_MDC_PD. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_PD
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_PD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_PD.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_PD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_PD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_PD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_PD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_PD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_PD_TOTAL.

*...processing: /ADESSO/V_MDC_RE................................*
TABLES: /ADESSO/V_MDC_RE, */ADESSO/V_MDC_RE. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_RE
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_RE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_RE.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_RE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_RE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_RE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_RE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_RE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_RE_TOTAL.

*...processing: /ADESSO/V_MDC_RI................................*
TABLES: /ADESSO/V_MDC_RI, */ADESSO/V_MDC_RI. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_RI
TYPE TABLEVIEW USING SCREEN '0020'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_RI. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_RI.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_RI_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_RI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_RI_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_RI_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_RI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_RI_TOTAL.

*...processing: /ADESSO/V_MDC_SA................................*
TABLES: /ADESSO/V_MDC_SA, */ADESSO/V_MDC_SA. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_SA
TYPE TABLEVIEW USING SCREEN '0022'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_SA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_SA.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_SA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_SA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_SA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_SA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_SA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_SA_TOTAL.

*...processing: /ADESSO/V_MDC_SN................................*
TABLES: /ADESSO/V_MDC_SN, */ADESSO/V_MDC_SN. "view work areas
CONTROLS: TCTRL_/ADESSO/V_MDC_SN
TYPE TABLEVIEW USING SCREEN '0019'.
DATA: BEGIN OF STATUS_/ADESSO/V_MDC_SN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/ADESSO/V_MDC_SN.
* Table for entries selected to show on screen
DATA: BEGIN OF /ADESSO/V_MDC_SN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_SN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_SN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /ADESSO/V_MDC_SN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /ADESSO/V_MDC_SN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /ADESSO/V_MDC_SN_TOTAL.

*.........table declarations:.................................*
TABLES: */ADESSO/MDC_ODPM              .
TABLES: */ADESSO/MDC_OFRW              .
TABLES: */ADESSO/MDC_ORSP              .
TABLES: */ADESSO/MDC_OUT               .
TABLES: */ADESSO/MDC_PDOC              .
TABLES: */ADESSO/MDC_PQAL              .
TABLES: */ADESSO/MDC_SND               .
TABLES: */ADESSO/MDC_SNDA              .
TABLES: /ADESSO/MDC_IN                 .
TABLES: /ADESSO/MDC_INA                .
TABLES: /ADESSO/MDC_MAIN               .
TABLES: /ADESSO/MDC_MPGR               .
TABLES: /ADESSO/MDC_MPSP               .
TABLES: /ADESSO/MDC_ODP                .
TABLES: /ADESSO/MDC_ODPM               .
TABLES: /ADESSO/MDC_OFRW               .
TABLES: /ADESSO/MDC_ORSP               .
TABLES: /ADESSO/MDC_OUT                .
TABLES: /ADESSO/MDC_PDOC               .
TABLES: /ADESSO/MDC_PQAL               .
TABLES: /ADESSO/MDC_RAED               .
TABLES: /ADESSO/MDC_RAID               .
TABLES: /ADESSO/MDC_SND                .
TABLES: /ADESSO/MDC_SNDA               .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
