sap.ui.jsview("hellooworld2.bib2", {                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
	/** Specifies the Controller belonging to this View.&nbsp;                                                                                                                                                                                                    
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.                                                                                                                                                   
	* @memberOf hellooworld2.bib2                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	getControllerName : function() {                                                                                                                                                                                                                              
		return "hellooworld2.bib2";                                                                                                                                                                                                                                  
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed.&nbsp;                                                                                                                                   
	* Since the Controller is given to this method, its event handlers can be attached right away.&nbsp;                                                                                                                                                          
	* @memberOf hellooworld2.bib2                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	createContent : function(oController) {                                                                                                                                                                                                                       
		//---------------------------                                                                                                                                                                                                                                
		this.oPage = this.byId("p");                                                                                                                                                                                                                                 
	    /*  var oVBI = new sap.ui.vbm.GeoMap(  vos : [ new sap.ui.vbm.Spots({	                                                                                                                                                                                    
	          items : [ new sap.ui.vbm.Spot({ position : "20;0;0" }) ]                                                                                                                                                                                            
	      }) ] );*/                                                                                                                                                                                                                                               
		var oVBI = new sap.ui.vbm.GeoMap({                                                                                                                                                                                                                           
			   vos : [ new sap.ui.vbm.Spots({	                                                                                                                                                                                                                          
			      items : [ new sap.ui.vbm.Spot({ position : "20;0;0" }) ]                                                                                                                                                                                              
			   }) ]                                                                                                                                                                                                                                                     
			});                                                                                                                                                                                                                                                         
	      var conf = {&nbsp;                                                                                                                                                                                                                                      
	              "MapProvider":[                                                                                                                                                                                                                                 
	                {                                                                                                                                                                                                                                             
	                	"Id" : "OSM",                                                                                                                                                                                                                                
	                  "name" : "Open Street Map",                                                                                                                                                                                                                 
	                  "tileX" : "256",                                                                                                                                                                                                                            
	                  "tileY" : "256",                                                                                                                                                                                                                            
	                  "minLOD" : "1",                                                                                                                                                                                                                             
	                  "maxLOD" : "19",                                                                                                                                                                                                                            
	                  "copyright" : "OpenStreetMap",                                                                                                                                                                                                              
	                  "Source" : [{                                                                                                                                                                                                                               
	                  	"id" : "a",                                                                                                                                                                                                                                
	                    "url" : "https://a.tile.openstreetmap.org/{LOD}/{X}/{Y}.png"                                                                                                                                                                              
	                  }]                                                                                                                                                                                                                                          
	                }                                                                                                                                                                                                                                             
	              ],                                                                                                                                                                                                                                              
	              "MapLayerStacks":&nbsp;                                                                                                                                                                                                                         
	              [                                                                                                                                                                                                                                               
	                {&nbsp;&nbsp;                                                                                                                                                                                                                                 
	                	"name" : "Default",                                                                                                                                                                                                                          
	                  "MapLayer": [                                                                                                                                                                                                                               
	                  	{                                                                                                                                                                                                                                          
	                    	"name": "Default",                                                                                                                                                                                                                       
	                  		"refMapProvider": "Open Street Map",                                                                                                                                                                                                      
	                  		"opacity": "1.0",                                                                                                                                                                                                                         
	                  		"colBkgnd": "RGB(255,255,255)"&nbsp;                                                                                                                                                                                                      
	                    }                                                                                                                                                                                                                                         
	                  ]&nbsp;&nbsp;                                                                                                                                                                                                                               
	                }                                                                                                                                                                                                                                             
	              ]                                                                                                                                                                                                                                               
	  			};                                                                                                                                                                                                                                                       
	        oVBI.setMapConfiguration(conf);                                                                                                                                                                                                                       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                              
	    //    this.addContent(rPannel_button);                                                                                                                                                                                                                    
	        this.addContent(oVBI);                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
	//      }                                                                                                                                                                                                                                                     
	//  });                                                                                                                                                                                                                                                       
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                          
	    //----------------------------&nbsp;&nbsp;                                                                                                                                                                                                                
		/*var button_opst = new sap.ui.commons.Button("Button1",{                                                                                                                                                                                                    
			text: "Open Streetmaps",                                                                                                                                                                                                                                    
			press: function(oEvent)                                                                                                                                                                                                                                     
					{                                                                                                                                                                                                                                                         
			//	app.back();                                                                                                                                                                                                                                              
				//oController.Save();                                                                                                                                                                                                                                      
					//oController.opstr();                                                                                                                                                                                                                                    
					}                                                                                                                                                                                                                                                         
		});                                                                                                                                                                                                                                                          
		this.addContent(button_opst);*/                                                                                                                                                                                                                              
 		return new sap.m.Page({                                                                                                                                                                                                                                     
			title: "Open Streetmap",                                                                                                                                                                                                                                    
			content: [                                                                                                                                                                                                                                                  
				                                                                                                                                                                                                                                                           
				                                                                                                                                                                                                                                                           
				                                                                                                                                                                                                                                                           
				new sap.m.Button({                                                                                                                                                                                                                                         
				text:"Go to Page2",                                                                                                                                                                                                                                        
				tap: function(){                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
					app.back();                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
				}                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
				}),                                                                                                                                                                                                                                                        
				new sap.m.Button({                                                                                                                                                                                                                                         
					text:"Go to Page3",                                                                                                                                                                                                                                       
					tap: function(){                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
						app.back();                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
					}                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
					})                                                                                                                                                                                                                                                        
					                                                                                                                                                                                                                                                          
			                                                                                                                                                                                                                                                            
			]                                                                                                                                                                                                                                                           
		});                                                                                                                                                                                                                                                          
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            