sap.ui.jsview("hellooworld2.TEST", {                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
	/** Specifies the Controller belonging to this View.&nbsp;                                                                                                                                                                                                    
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.                                                                                                                                                   
	* @memberOf hellooworld2.TEST                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	                                                                                                                                                                                                                                                              
	getControllerName : function() {                                                                                                                                                                                                                              
		return "hellooworld2.TEST";                                                                                                                                                                                                                                  
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed.&nbsp;                                                                                                                                   
	* Since the Controller is given to this method, its event handlers can be attached right away.&nbsp;                                                                                                                                                          
	* @memberOf hellooworld2.TEST                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	createContent : function(oController) {                                                                                                                                                                                                                       
		                                                                                                                                                                                                                                                             
		var gv_idx = 0;                                                                                                                                                                                                                                              
		var layout = new sap.ui.commons.layout.MatrixLayout("layout");                                                                                                                                                                                               
		layout.setWidth("100%");                                                                                                                                                                                                                                     
		var rPannel = new sap.ui.commons.Panel("rPannel");                                                                                                                                                                                                           
		var rTitle = new sap.ui.commons.Title("rTitle");                                                                                                                                                                                                             
		//<Title text="Items ({/zmeins_dbSet/length})" />                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
		                                                                                                                                                                                                                                                             
		rTitle.setText("Hello GUYS!!! ");                                                                                                                                                                                                                            
		rPannel.setTitle(rTitle);                                                                                                                                                                                                                                    
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
//		debugger;                                                                                                                                                                                                                                                  
		var oTable = new sap.ui.table.Table("Table",{                                                                                                                                                                                                                
			//headerToolbar : oTableHeader,                                                                                                                                                                                                                             
		    selectionMode : sap.ui.table.SelectionMode.Single,                                                                                                                                                                                                       
		    rowSelectionChange: function(e) {		    	                                                                                                                                                                                                                 
	    	                                                                                                                                                                                                                                                         
		        var idx = e.getParameter('rowIndex');                                                                                                                                                                                                                
		       // var rows = e.byId('Table').getRows();                                                                                                                                                                                                              
		       // alert(rows);                                                                                                                                                                                                                                       
		       // var data = oTable.getData();                                                                                                                                                                                                                       
		        //var sel = data[0];                                                                                                                                                                                                                                 
		        //console.log(sel);                                                                                                                                                                                                                                  
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                             
		        //-----Lesen von der Tabelle einzelne Zeilen                                                                                                                                                                                                         
		        var oModel = new sap.ui.model.odata.ODataModel("proxy/https/sap-ae1.test-server.ag:50041/sap/opu/odata/SAP/ZHELLOOWORLD2_SRV_01", true);                                                                                                             
                                                                                                                                                                                                                                                               
		        //sap.ui.getCore().setModel(oModel,”Model”);                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
		        oModel.read("/zmeins_dbSet", null, null, true,                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
		        function(value, response){                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		        //oModel.setProperty(“People” ,JSON.parse(response.body));&nbsp;                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
		            //console.log(JSON.parse(response.body));                                                                                                                                                                                                        
		            console.log(value);                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
		          },                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
		            function(err){                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
		         alert("Error");                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
		        }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
		        );                                                                                                                                                                                                                                                   
		        // ---- ende&nbsp;                                                                                                                                                                                                                                   
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                             
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                             
		        if (oTable.isIndexSelected(idx)) {                                                                                                                                                                                                                   
		          var cxt = oTable.getContextByIndex(idx);                                                                                                                                                                                                           
		          var path = cxt.sPath;                                                                                                                                                                                                                              
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                       
		          var obj = oTable.getModel().getProperty(path);                                                                                                                                                                                                     
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                 
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                 
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                 
		  		//var users = [];                                                                                                                                                                                                                                        
				//users.push({Id: 'Id' + idx,  firstName: 'firstName' + idx});                                                                                                                                                                                             
		        //  var rows = oTable.getModel().getRows();                                                                                                                                                                                                          
		       //   alert(rows);                                                                                                                                                                                                                                     
		          //Var oData = oModel.getProperty(« /menu/value ») ;                                                                                                                                                                                                
		          console.log(obj.results+"(0)");                                                                                                                                                                                                                    
		          //    alert(obj.value);&nbsp;&nbsp;                                                                                                                                                                                                                
		              gv_idx = idx;                                                                                                                                                                                                                                  
		            //  console.log(JSON.stringify(obj));                                                                                                                                                                                                            
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                     
		              var item = oTable.getRows()[idx];                                                                                                                                                                                                              
		              var oRowData = item.getBindingContext();//.getObject();                                                                                                                                                                                        
		              var oSelectedItemData = oRowData.getObject();                                                                                                                                                                                                  
		              //var aPath = item.getBindingContext();                                                                                                                                                                                                        
		             // var entryID = oModel.getProperty(aPath + "/Name");                                                                                                                                                                                           
		              console.log("TEST1:"+oSelectedItemData.Name);                                                                                                                                                                                                  
		              console.log("TEST2:"+oSelectedItemData.Nachname);                                                                                                                                                                                              
		              console.log("TEST3:"+oSelectedItemData.Id);                                                                                                                                                                                                    
		              console.log("TEST4:"+oSelectedItemData.Dokument);                                                                                                                                                                                              
		        }                                                                                                                                                                                                                                                    
		      }                                                                                                                                                                                                                                                      
		});                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
		oTable.addColumn(new sap.ui.table.Column({                                                                                                                                                                                                                   
			label : new sap.ui.commons.Label({                                                                                                                                                                                                                          
			text : "DB"                                                                                                                                                                                                                                                 
			}),                                                                                                                                                                                                                                                         
			template : new sap.ui.commons.TextField().bindProperty("value",                                                                                                                                                                                             
			"Id"),                                                                                                                                                                                                                                                      
			sortProperty : "Id"                                                                                                                                                                                                                                         
			}));                                                                                                                                                                                                                                                        
			oTable.addColumn(new sap.ui.table.Column({                                                                                                                                                                                                                  
			label : new sap.ui.commons.Label({                                                                                                                                                                                                                          
			text : "Dokument"                                                                                                                                                                                                                                           
			}),                                                                                                                                                                                                                                                         
			template : new sap.ui.commons.TextField().bindProperty("value",                                                                                                                                                                                             
			"Dokument"),                                                                                                                                                                                                                                                
			sortProperty : "Dokument"                                                                                                                                                                                                                                   
			}));                                                                                                                                                                                                                                                        
			oTable.addColumn(new sap.ui.table.Column({                                                                                                                                                                                                                  
			label : new sap.ui.commons.Label({                                                                                                                                                                                                                          
			text : "Vorname"                                                                                                                                                                                                                                            
			}),                                                                                                                                                                                                                                                         
			template : new sap.ui.commons.TextField().bindProperty("value",                                                                                                                                                                                             
			"Name"),                                                                                                                                                                                                                                                    
			sortProperty : "Name"                                                                                                                                                                                                                                       
			}));                                                                                                                                                                                                                                                        
			oTable.addColumn(new sap.ui.table.Column({                                                                                                                                                                                                                  
			label : new sap.ui.commons.Label({                                                                                                                                                                                                                          
			text : "Nachname"                                                                                                                                                                                                                                           
			}),                                                                                                                                                                                                                                                         
			template : new sap.ui.commons.TextField().bindProperty("value",                                                                                                                                                                                             
			"Nachname"),                                                                                                                                                                                                                                                
			sortProperty : "Nachname"                                                                                                                                                                                                                                   
			}));                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			oTable.addColumn(new sap.ui.table.Column({                                                                                                                                                                                                                  
				label : new sap.ui.commons.Label({                                                                                                                                                                                                                         
				text : "Ort"                                                                                                                                                                                                                                               
				}),                                                                                                                                                                                                                                                        
				template : new sap.ui.commons.TextField().bindProperty("value",                                                                                                                                                                                            
				"Ort"),                                                                                                                                                                                                                                                    
				sortProperty : "Ort"                                                                                                                                                                                                                                       
				}));                                                                                                                                                                                                                                                       
	//    var serviceUrl = "proxy/https/sap-ae1.test-server.ag:50041/sap/opu/odata/SAP/ZHELLOOWORLD2_SRV_01";                                                                                                                                                     
	 //	oTable.setModel(oModel);	                                                                                                                                                                                                                                 
		//var tableModel = new sap.ui.model.json.JSONModel();                                                                                                                                                                                                        
		//var oModel = new sap.ui.model.odata.ODataModel(sServiceUrl, false);                                                                                                                                                                                        
		//tableModel.setData({modelData: ""});                                                                                                                                                                                                                       
		//oTable.setModel(tableModel);                                                                                                                                                                                                                               
			var serviceUrl = "proxy/https/sap-ae1.test-server.ag:50041/sap/opu/odata/SAP/ZHELLOOWORLD2_SRV_01";                                                                                                                                                         
			                                                                                                                                                                                                                                                            
			var oModel = new sap.ui.model.odata.ODataModel(serviceUrl, false);                                                                                                                                                                                          
			//Setting model to the table                                                                                                                                                                                                                                
				oTable.setModel(oModel);                                                                                                                                                                                                                                   
		oTable.bindRows("/zmeins_dbSet");                                                                                                                                                                                                                            
		rPannel.addContent(oTable);                                                                                                                                                                                                                                  
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		//ende Part ohne table                                                                                                                                                                                                                                       
		layout.createRow(rPannel);		                                                                                                                                                                                                                                 
		this.addContent(layout);                                                                                                                                                                                                                                     
		                                                                                                                                                                                                                                                             
		// Gibt mir die Anzahl der Zeilen mit length                                                                                                                                                                                                                 
		//---BOI                                                                                                                                                                                                                                                     
	    var oRowsBinding = oTable.getBinding("rows");                                                                                                                                                                                                             
			rTitle.setText("Hello GUYS!!! ROWS ("+oRowsBinding.getLength()+")");                                                                                                                                                                                        
		oRowsBinding.attachChange(function(){                                                                                                                                                                                                                        
		     var oLength = oRowsBinding.getLength();          //Gets you the rows length                                                                                                                                                                             
		    // alert(oLength);                                                                                                                                                                                                                                       
		});                                                                                                                                                                                                                                                          
			                                                                                                                                                                                                                                                            
	    //---EOI                                                                                                                                                                                                                                                  
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		var rPannel_button = new sap.ui.commons.Panel("rPannel1");                                                                                                                                                                                                   
		var button = new sap.ui.commons.Button("Button",{                                                                                                                                                                                                            
			text: "click mich",                                                                                                                                                                                                                                         
			press: function(oEvent)                                                                                                                                                                                                                                     
					{                                                                                                                                                                                                                                                         
				//var count= oTable.getView().byId("Table").getItems().length;                                                                                                                                                                                             
				//var oItemsLength = oItemsBinding.getLength();                                                                                                                                                                                                            
		                                                                                                                                                                                                                                                             
				//alert(oTable.selectedRow());                                                                                                                                                                                                                             
				//oModel = oTable.getModel(),                                                                                                                                                                                                                              
			    //aItems = oTable.getItems();                                                                                                                                                                                                                           
				//alert(aItems.length);                                                                                                                                                                                                                                    
				// var m = oTable.getModel();                                                                                                                                                                                                                              
		        //  var data = m.getData();                                                                                                                                                                                                                          
		        //  var removed = data.splice(id, 1);                                                                                                                                                                                                                
		       //   m.setData(data);                                                                                                                                                                                                                                 
				                                                                                                                                                                                                                                                           
						                                                                                                                                                                                                                                                         
				//alert(oEvent.getSource().getSelectedItem().getBindingContext().getObject().Name);                                                                                                                                                                        
				//debugger;                                                                                                                                                                                                                                                
				//oController.Save();                                                                                                                                                                                                                                      
				  var item = oTable.getRows()[gv_idx];                                                                                                                                                                                                                     
	              var oRowData = item.getBindingContext();//.getObject();                                                                                                                                                                                         
	              var oSelectedItemData = oRowData.getObject();                                                                                                                                                                                                   
	              //var aPath = item.getBindingContext();                                                                                                                                                                                                         
	             // var entryID = oModel.getProperty(aPath + "/Name");                                                                                                                                                                                            
	              console.log("TEST1:"+oSelectedItemData.Name);                                                                                                                                                                                                   
	              console.log("TEST2:"+oSelectedItemData.Nachname);                                                                                                                                                                                               
	              console.log("TEST3:"+oSelectedItemData.Id);                                                                                                                                                                                                     
	              console.log("TEST4:"+oSelectedItemData.Dokument);                                                                                                                                                                                               
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                          
					oController.create(oSelectedItemData.Id, oSelectedItemData.Dokument, oSelectedItemData.Name , oSelectedItemData.Nachname , oModel );                                                                                                                      
					}                                                                                                                                                                                                                                                         
		});                                                                                                                                                                                                                                                          
		rPannel_button.addContent(button);                                                                                                                                                                                                                           
		//this.addContent(button);                                                                                                                                                                                                                                   
		                                                                                                                                                                                                                                                             
		var button_opst = new sap.ui.commons.Button("Button1",{                                                                                                                                                                                                      
			text: "Open Streetmaps",                                                                                                                                                                                                                                    
			press: function(oEvent)                                                                                                                                                                                                                                     
					{                                                                                                                                                                                                                                                         
				                                                                                                                                                                                                                                                           
				//oController.Save();                                                                                                                                                                                                                                      
					oController.opstr();                                                                                                                                                                                                                                      
					}                                                                                                                                                                                                                                                         
		});                                                                                                                                                                                                                                                          
		                                                                                                                                                                                                                                                             
		rPannel_button.addContent(button_opst);                                                                                                                                                                                                                      
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		var button_dummy = new sap.ui.commons.Button("Button2",{                                                                                                                                                                                                     
			text: "Dummy",                                                                                                                                                                                                                                              
			press: function(oEvent)                                                                                                                                                                                                                                     
					{                                                                                                                                                                                                                                                         
			//	var rowItems = oTable.getSelectedItems();                                                                                                                                                                                                                
				                                                                                                                                                                                                                                                           
		                                                                                                                                                                                                                                                             
			//	alert(rowItems);                                                                                                                                                                                                                                         
			//	console.log(rowItems);                                                                                                                                                                                                                                   
			 	                                                                                                                                                                                                                                                          
				var idx = oTable.getSelectedIndex();                                                                                                                                                                                                                       
				//var theName = oModel.getProperty(spath);                                                                                                                                                                                                                 
				                                                                                                                                                                                                                                                           
				//var cxt = oTable.getContextByIndex(idx);                                                                                                                                                                                                                 
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                             
		        //var oModeln = sap.ui.getCore().getModel();                                                                                                                                                                                                         
		        //var theName = oModeln.getProperty(path);                                                                                                                                                                                                           
		       // alert(theName);                                                                                                                                                                                                                                    
				//alert(aItems[idx].getAggregation("cells")[0].getProperty("Id"));                                                                                                                                                                                         
				//var row = oTable.getRows()[gv_idx];                                                                                                                                                                                                                      
				//var aItems = oTable.getItems();                                                                                                                                                                                                                          
				//var oModel = oTable.getModel();                                                                                                                                                                                                                          
				//var data  = oModel.getData();                                                                                                                                                                                                                            
				                                                                                                                                                                                                                                                           
				//console.log(idx);                                                                                                                                                                                                                                        
				//	var arrayValues = data.modelData;                                                                                                                                                                                                                       
			//	var selectedRow = arrayValues[idx];                                                                                                                                                                                                                      
				//		alert(aItems[idx].getBindingContext());                                                                                                                                                                                                                
				//oController.Save();                                                                                                                                                                                                                                      
				 var item = oTable.getRows()[gv_idx];                                                                                                                                                                                                                      
	              var oRowData = item.getBindingContext();//.getObject();                                                                                                                                                                                         
	              var oSelectedItemData = oRowData.getObject();                                                                                                                                                                                                   
					oController.dummy(oSelectedItemData.Id, oSelectedItemData.Dokument, oSelectedItemData.Name , oSelectedItemData.Nachname  );                                                                                                                               
					}                                                                                                                                                                                                                                                         
		});                                                                                                                                                                                                                                                          
		rPannel_button.addContent(button_dummy);                                                                                                                                                                                                                     
		this.addContent(rPannel_button);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               