sap.ui.jsview("hellooworld2.bib", {                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Specifies the Controller belonging to this View.&nbsp;                                                                                                                                                                                                    
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.                                                                                                                                                   
	* @memberOf hellooworld2.TEST                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	                                                                                                                                                                                                                                                              
	getControllerName : function() {                                                                                                                                                                                                                              
		//var id = sessionStorage.getItem('Id'); //Set value                                                                                                                                                                                                         
		//alert(id);                                                                                                                                                                                                                                                 
	                                                                                                                                                                                                                                                              
		return "hellooworld2.bib";                                                                                                                                                                                                                                   
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed.&nbsp;                                                                                                                                   
	* Since the Controller is given to this method, its event handlers can be attached right away.&nbsp;                                                                                                                                                          
	* @memberOf hellooworld2.TEST                                                                                                                                                                                                                                 
	*/&nbsp;                                                                                                                                                                                                                                                      
	createContent : function(oController) {                                                                                                                                                                                                                       
		var c = sap.ui.commons;                                                                                                                                                                                                                                      
		                                                                                                                                                                                                                                                             
		var tf1 = new sap.ui.commons.TextField({                                                                                                                                                                                                                     
		    // your configuration                                                                                                                                                                                                                                    
		    liveChange: function(){                                                                                                                                                                                                                                  
		        if(this.getValue() === "")                                                                                                                                                                                                                           
		            this.setValueState(sap.ui.core.ValueState.Error);                                                                                                                                                                                                
		        else                                                                                                                                                                                                                                                 
		            this.setValueState(sap.ui.core.ValueState.Success);                                                                                                                                                                                              
		    }                                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
		var tf2 = new sap.ui.commons.TextField({                                                                                                                                                                                                                     
		    // your configuration                                                                                                                                                                                                                                    
		    liveChange: function(){                                                                                                                                                                                                                                  
		        if(this.getValue() === "")                                                                                                                                                                                                                           
		            this.setValueState(sap.ui.core.ValueState.Error);                                                                                                                                                                                                
		        else                                                                                                                                                                                                                                                 
		            this.setValueState(sap.ui.core.ValueState.Success);                                                                                                                                                                                              
		    }                                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
		var tf3 = new sap.ui.commons.TextField({                                                                                                                                                                                                                     
		    // your configuration                                                                                                                                                                                                                                    
		    liveChange: function(){                                                                                                                                                                                                                                  
		        if(this.getValue() === "")                                                                                                                                                                                                                           
		            this.setValueState(sap.ui.core.ValueState.Error);                                                                                                                                                                                                
		        else                                                                                                                                                                                                                                                 
		            this.setValueState(sap.ui.core.ValueState.Success);                                                                                                                                                                                              
		    }                                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
		var tf4 = new sap.ui.commons.TextField({                                                                                                                                                                                                                     
		    // your configuration                                                                                                                                                                                                                                    
		    liveChange: function(){                                                                                                                                                                                                                                  
		        if(this.getValue() === "")                                                                                                                                                                                                                           
		            this.setValueState(sap.ui.core.ValueState.Error);                                                                                                                                                                                                
		        else                                                                                                                                                                                                                                                 
		            this.setValueState(sap.ui.core.ValueState.Success);                                                                                                                                                                                              
		    }                                                                                                                                                                                                                                                        
		});                                                                                                                                                                                                                                                          
		  //var item = oTable.getRows()[gv_idx];                                                                                                                                                                                                                     
          /*var oRowData = item.getBindingContext();//.getObject();                                                                                                                                                                                            
          var oSelectedItemData = oRowData.getObject();                                                                                                                                                                                                        
          //var aPath = item.getBindingContext();                                                                                                                                                                                                              
         // var entryID = oModel.getProperty(aPath + "/Name");                                                                                                                                                                                                 
          console.log("TEST1:"+oSelectedItemData.Name);                                                                                                                                                                                                        
          console.log("TEST2:"+oSelectedItemData.Nachname);                                                                                                                                                                                                    
          console.log("TEST3:"+oSelectedItemData.Id);                                                                                                                                                                                                          
          console.log("TEST4:"+oSelectedItemData.Dokument);*/                                                                                                                                                                                                  
		//var test = sessionStorage.getItem('myKeyString');                                                                                                                                                                                                          
		var idd = sessionStorage.getItem('myKeyString');  // Get saved string                                                                                                                                                                                        
		//var id = sessionStorage.getItem('Id'); //Set value                                                                                                                                                                                                         
		//var tt = sessionStorage.getItem('myObject');                                                                                                                                                                                                               
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
		//alert("idd:"+idd);                                                                                                                                                                                                                                         
		//var dok = sessionStorage.getItem('Dokument'); //Set value                                                                                                                                                                                                  
		//var name = sessionStorage.getItem('name'); //Set value                                                                                                                                                                                                     
		//var nachname = sessionStorage.getItem('nachname'); //Set value                                                                                                                                                                                             
		oController.Id( tf1 ,tf2 , tf3, tf4)                                                                                                                                                                                                                         
		/*tf1.setValue(oController.Id( tf1 ,tf2 , tf3, tf4));                                                                                                                                                                                                        
		tf2.setValue("dok");                                                                                                                                                                                                                                         
		tf3.setValue("name");                                                                                                                                                                                                                                        
		tf4.setValue("nachname");*/                                                                                                                                                                                                                                  
		var rPannel_button = new sap.ui.commons.Panel("P1");                                                                                                                                                                                                         
				                                                                                                                                                                                                                                                           
				var button = new sap.ui.commons.Button("Speichern",{                                                                                                                                                                                                       
					text: "click mich",                                                                                                                                                                                                                                       
					press: function(oEvent)                                                                                                                                                                                                                                   
							{                                                                                                                                                                                                                                                       
						var lv_id = tf1.getValue();                                                                                                                                                                                                                              
						var lv_do = tf2.getValue();                                                                                                                                                                                                                              
						var lv_name = tf3.getValue();                                                                                                                                                                                                                            
						var lv_nachn = tf4.getValue();                                                                                                                                                                                                                           
						var method = "POST";                                                                                                                                                                                                                                     
						var newData = {                                                                                                                                                                                                                                          
								//"odata.type": "OData.scarrSet",				                                                                                                                                                                                                                  
								"Id":  lv_id,                                                                                                                                                                                                                                          
								"Dokument": lv_do,                                                                                                                                                                                                                                     
								"Name": lv_name,                                                                                                                                                                                                                                       
								"Nachname":	 lv_nachn                                                                                                                                                                                                                                  
							};                                                                                                                                                                                                                                                      
						var serviceUrl = "proxy/https/sap-ae1.test-server.ag:50041/sap/opu/odata/SAP/ZHELLOOWORLD2_SRV_01";                                                                                                                                                      
					//	var serviceUrl = "https/sap-ae1.test-server.ag:50041/sap/opu/odata/SAP/ZHELLOOWORLD2_SRV_01";                                                                                                                                                          
								                                                                                                                                                                                                                                                       
						var oModel = new sap.ui.model.odata.ODataModel(serviceUrl, false);                                                                                                                                                                                       
				                                                                                                                                                                                                                                                           
						//var oModel = oModel.getView().getModel();                                                                                                                                                                                                              
						oModel.update("/zmeins_dbSet(Id=1)", newData,                                                                                                                                                                                                            
								null, function(){                                                                                                                                                                                                                                      
							var msg = "OK";                                                                                                                                                                                                                                         
							window.location.reload();                                                                                                                                                                                                                               
							app.back();                                                                                                                                                                                                                                             
							//sap.m.MessageBox.show(msg);                                                                                                                                                                                                                           
							},                                                                                                                                                                                                                                                      
							function (){                                                                                                                                                                                                                                            
								alert("Fail");                                                                                                                                                                                                                                         
							                                                                                                                                                                                                                                                        
						                                                                                                                                                                                                                                                         
							                                                                                                                                                                                                                                                        
							});                                                                                                                                                                                                                                                     
							                                                                                                                                                                                                                                                        
						/*oModel.create("/zmeins_dbSet", newData,                                                                                                                                                                                                                
								{                                                                                                                                                                                                                                                      
								success: function(oData,oResponse)                                                                                                                                                                                                                     
								  {                                                                                                                                                                                                                                                    
									alert("success");                                                                                                                                                                                                                                     
								  },                                                                                                                                                                                                                                                   
				    			 error : function(oError)&nbsp;                                                                                                                                                                                                                     
				    			 {&nbsp;                                                                                                                                                                                                                                            
								    alert("Failed");                                                                                                                                                                                                                                   
				    			 }                                                                                                                                                                                                                                                  
								});*/                                                                                                                                                                                                                                                  
	                                                                                                                                                                                                                                                              
								                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
								//alert("sdfsdf");                                                                                                                                                                                                                                     
							}                                                                                                                                                                                                                                                       
				});                                                                                                                                                                                                                                                        
				rPannel_button.addContent(tf1);                                                                                                                                                                                                                            
				rPannel_button.addContent(tf2);                                                                                                                                                                                                                            
				rPannel_button.addContent(tf3);                                                                                                                                                                                                                            
				rPannel_button.addContent(tf4);                                                                                                                                                                                                                            
				rPannel_button.addContent(button);                                                                                                                                                                                                                         
				this.addContent(rPannel_button);                                                                                                                                                                                                                           
				                                                                                                                                                                                                                                                           
				                                                                                                                                                                                                                                                           
			/*	var button_opst = new sap.ui.commons.Button("Zurück",{                                                                                                                                                                                                   
					text: "Open Streetmaps",                                                                                                                                                                                                                                  
					press: function(oEvent)                                                                                                                                                                                                                                   
							{                                                                                                                                                                                                                                                       
						                                                                                                                                                                                                                                                         
						//oController.Save();                                                                                                                                                                                                                                    
						app.back();                                                                                                                                                                                                                                              
							}                                                                                                                                                                                                                                                       
				});*/                                                                                                                                                                                                                                                      
		return new sap.m.Page({                                                                                                                                                                                                                                      
			title: "Daten bearbeiten",                                                                                                                                                                                                                                  
			content: [                                                                                                                                                                                                                                                  
				new sap.m.Button({                                                                                                                                                                                                                                         
				text:"Zurück",                                                                                                                                                                                                                                             
				tap: function(){                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
					app.back();                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
				}                                                                                                                                                                                                                                                          
				}),                                                                                                                                                                                                                                                        
				new sap.m.Button({                                                                                                                                                                                                                                         
					text:"Back",                                                                                                                                                                                                                                              
					tap: function(){                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
						app.back();                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
					}                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
					})                                                                                                                                                                                                                                                        
				]                                                                                                                                                                                                                                                          
			});                                                                                                                                                                                                                                                         
	                                                                                                                                                                                                                                                              
		                                                                                                                                                                                                                                                             
		                                                                                                                                                                                                                                                             
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               