interface ZIF_AGC_DATEX_CO
  public .


  constants GC_ADR_KIND_DEFAULT type BU_ADRKIND value 'XXDEFAULT'. "#EC NOTEXT
  constants GC_ADR_KIND_MREAD_CARD type BU_ADRKIND value 'MREAD_CARD'. "#EC NOTEXT
  constants GC_BASICPROC_IMPRESMDCH type E_DEXBASICPROC value 'IMPRESMDCH'. "#EC NOTEXT
  constants GC_BASICPROC_IMPREQBSUP type E_DEXBASICPROC value 'IMPREQBSUP'. "#EC NOTEXT
  constants GC_BASICPROC_IMPRESBSUP type E_DEXBASICPROC value 'IMPRESBSUP'. "#EC NOTEXT
  constants GC_BASICPROC_IMPREQSWT type E_DEXBASICPROC value 'IMPREQSWT'. "#EC NOTEXT
  constants GC_BASICPROC_IMPRESSWT type E_DEXBASICPROC value 'IMPRESSWT'. "#EC NOTEXT
  constants GC_BASICPROC_EXPRESMDCH type E_DEXBASICPROC value 'EXPRESMDCH'. "#EC NOTEXT
  constants GC_BASICPROC_REQ_CHANGE type E_DEXBASICPROC value 'REQ_CHANGE'. "#EC NOTEXT
  constants GC_BASICPROC_CHCD_OUT type E_DEXBASICPROC value 'CHCD_OUT'. "#EC NOTEXT
  constants GC_BASICPROC_EXBDRRES type E_DEXBASICPROC value 'EXBDRRES'. "#EC NOTEXT
  constants GC_BASICPROC_EXPREQBSUP type E_DEXBASICPROC value 'EXPREQBSUP'. "#EC NOTEXT
  constants GC_BASICPROC_EXPRESBSUP type E_DEXBASICPROC value 'EXPRESBSUP'. "#EC NOTEXT
  constants GC_BASICPROC_EXPREQSWT type E_DEXBASICPROC value 'EXPREQSWT'. "#EC NOTEXT
  constants GC_BASICPROC_EXPRESSWT type E_DEXBASICPROC value 'EXPRESSWT'. "#EC NOTEXT
  constants GC_BASICPROC_ZEXPKOMMF type E_DEXBASICPROC value 'ZEXPKOMMF'. "#EC NOTEXT
  constants GC_BASICPROC_EXMDCHANGE type E_DEXBASICPROC value 'EXMDCHANGE'. "#EC NOTEXT
  constants GC_MANDT_110 type MANDT value '110'. "#EC NOTEXT
  constants GC_MANDT_210 type MANDT value '210'. "#EC NOTEXT
  constants GC_MSG_CATEGORY_Z99 type /IDXGC/DE_DOCNAME_CODE value 'Z99'. "#EC NOTEXT
  constants GC_NAD_NAME_FORMAT_Z01 type /IDXGC/DE_NAME_FORMAT_CODE value 'Z01'. "#EC NOTEXT
  constants GC_NAD_NAME_FORMAT_Z02 type /IDXGC/DE_NAME_FORMAT_CODE value 'Z02'. "#EC NOTEXT
  constants GC_PROC_TYPE_21 type /IDXGC/DE_PROC_TYPE value '21'. "#EC NOTEXT
  constants GC_PROC_TYPE_22 type /IDXGC/DE_PROC_TYPE value '22'. "#EC NOTEXT
  constants GC_SERVICE_ID_N100001 type SERVICE_PROV value 'N100001'. "#EC NOTEXT
  constants GC_SERVICE_ID_N200001 type SERVICE_PROV value 'N200001'. "#EC NOTEXT
  constants GC_SERVICE_ID_N300001 type SERVICE_PROV value 'N300001'. "#EC NOTEXT
  constants GC_SERVICE_ID_N800001 type SERVICE_PROV value 'N800001'. "#EC NOTEXT
  constants GC_SERVICE_ID_N900001 type SERVICE_PROV value 'N900001'. "#EC NOTEXT
  constants GC_SERVICE_ID_L100014 type SERVICE_PROV value 'L100014'. "#EC NOTEXT
  constants GC_SERVICE_ID_L200001 type SERVICE_PROV value 'L200001'. "#EC NOTEXT
  constants GC_SERVICE_ID_L300001 type SERVICE_PROV value 'L300001'. "#EC NOTEXT
  constants GC_SERVICE_ID_L800001 type SERVICE_PROV value 'L800001'. "#EC NOTEXT
  constants GC_SERVICE_ID_L900001 type SERVICE_PROV value 'L900001'. "#EC NOTEXT
  constants GC_PROC_ID_MDCHG_BLIST_DSO type /IDXGC/DE_PROC_ID value '9800'. "#EC NOTEXT
endinterface.
