FUNCTION-POOL /ADESSO/EA_BOR_METHODEN.      "MESSAGE-ID ..
* INCLUDE /ADESSO/LEA_BOR_METHODEND...       " Local class definition
TYPES: ZEAGP_T_DDTEXT TYPE TABLE OF DD04T-DDTEXT.

INCLUDE cntn01_swc.
INCLUDE /ADESSO/SPT_CONST.
