*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 20.07.2017 at 17:36:13
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_CC................................*
FORM GET_DATA_/ADESSO/V_BPU_CC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_CCAT WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_CC .
/ADESSO/V_BPU_CC-MANDT =
/ADESSO/BPU_CCAT-MANDT .
/ADESSO/V_BPU_CC-PROC_ID =
/ADESSO/BPU_CCAT-PROC_ID .
/ADESSO/V_BPU_CC-PROC_VERSION =
/ADESSO/BPU_CCAT-PROC_VERSION .
/ADESSO/V_BPU_CC-PROC_STEP_NO =
/ADESSO/BPU_CCAT-PROC_STEP_NO .
/ADESSO/V_BPU_CC-CHECK_ID =
/ADESSO/BPU_CCAT-CHECK_ID .
/ADESSO/V_BPU_CC-CHECK_RESULT =
/ADESSO/BPU_CCAT-CHECK_RESULT .
/ADESSO/V_BPU_CC-CCAT =
/ADESSO/BPU_CCAT-CCAT .
/ADESSO/V_BPU_CC-USER_COMMENT =
/ADESSO/BPU_CCAT-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_CC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_CC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_CC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_CC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_CCAT WHERE
  PROC_ID = /ADESSO/V_BPU_CC-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_CC-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_CC-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_CC-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_CC-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_CCAT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_CCAT WHERE
  PROC_ID = /ADESSO/V_BPU_CC-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_CC-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_CC-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_CC-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_CC-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_CCAT.
    ENDIF.
/ADESSO/BPU_CCAT-MANDT =
/ADESSO/V_BPU_CC-MANDT .
/ADESSO/BPU_CCAT-PROC_ID =
/ADESSO/V_BPU_CC-PROC_ID .
/ADESSO/BPU_CCAT-PROC_VERSION =
/ADESSO/V_BPU_CC-PROC_VERSION .
/ADESSO/BPU_CCAT-PROC_STEP_NO =
/ADESSO/V_BPU_CC-PROC_STEP_NO .
/ADESSO/BPU_CCAT-CHECK_ID =
/ADESSO/V_BPU_CC-CHECK_ID .
/ADESSO/BPU_CCAT-CHECK_RESULT =
/ADESSO/V_BPU_CC-CHECK_RESULT .
/ADESSO/BPU_CCAT-CCAT =
/ADESSO/V_BPU_CC-CCAT .
/ADESSO/BPU_CCAT-USER_COMMENT =
/ADESSO/V_BPU_CC-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_CCAT .
    ELSE.
    INSERT /ADESSO/BPU_CCAT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_CC-UPD_FLAG,
STATUS_/ADESSO/V_BPU_CC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_CC.
  SELECT SINGLE * FROM /ADESSO/BPU_CCAT WHERE
PROC_ID = /ADESSO/V_BPU_CC-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_CC-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_CC-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_CC-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_CC-CHECK_RESULT .
/ADESSO/V_BPU_CC-MANDT =
/ADESSO/BPU_CCAT-MANDT .
/ADESSO/V_BPU_CC-PROC_ID =
/ADESSO/BPU_CCAT-PROC_ID .
/ADESSO/V_BPU_CC-PROC_VERSION =
/ADESSO/BPU_CCAT-PROC_VERSION .
/ADESSO/V_BPU_CC-PROC_STEP_NO =
/ADESSO/BPU_CCAT-PROC_STEP_NO .
/ADESSO/V_BPU_CC-CHECK_ID =
/ADESSO/BPU_CCAT-CHECK_ID .
/ADESSO/V_BPU_CC-CHECK_RESULT =
/ADESSO/BPU_CCAT-CHECK_RESULT .
/ADESSO/V_BPU_CC-CCAT =
/ADESSO/BPU_CCAT-CCAT .
/ADESSO/V_BPU_CC-USER_COMMENT =
/ADESSO/BPU_CCAT-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_CC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_CC-PROC_ID TO
/ADESSO/BPU_CCAT-PROC_ID .
MOVE /ADESSO/V_BPU_CC-PROC_VERSION TO
/ADESSO/BPU_CCAT-PROC_VERSION .
MOVE /ADESSO/V_BPU_CC-PROC_STEP_NO TO
/ADESSO/BPU_CCAT-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_CC-CHECK_ID TO
/ADESSO/BPU_CCAT-CHECK_ID .
MOVE /ADESSO/V_BPU_CC-CHECK_RESULT TO
/ADESSO/BPU_CCAT-CHECK_RESULT .
MOVE /ADESSO/V_BPU_CC-MANDT TO
/ADESSO/BPU_CCAT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_CCAT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_CCAT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_CCAT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_DD................................*
FORM GET_DATA_/ADESSO/V_BPU_DD.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_DUED WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_DD .
/ADESSO/V_BPU_DD-MANDT =
/ADESSO/BPU_DUED-MANDT .
/ADESSO/V_BPU_DD-PROC_ID =
/ADESSO/BPU_DUED-PROC_ID .
/ADESSO/V_BPU_DD-PROC_VERSION =
/ADESSO/BPU_DUED-PROC_VERSION .
/ADESSO/V_BPU_DD-PROC_STEP_NO =
/ADESSO/BPU_DUED-PROC_STEP_NO .
/ADESSO/V_BPU_DD-CHECK_ID =
/ADESSO/BPU_DUED-CHECK_ID .
/ADESSO/V_BPU_DD-CHECK_RESULT =
/ADESSO/BPU_DUED-CHECK_RESULT .
/ADESSO/V_BPU_DD-TIMTYP =
/ADESSO/BPU_DUED-TIMTYP .
/ADESSO/V_BPU_DD-TIMQTY =
/ADESSO/BPU_DUED-TIMQTY .
/ADESSO/V_BPU_DD-USER_COMMENT =
/ADESSO/BPU_DUED-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_DD.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_DD .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_DD.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_DD-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_DUED WHERE
  PROC_ID = /ADESSO/V_BPU_DD-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_DD-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_DD-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_DD-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_DD-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_DUED .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_DUED WHERE
  PROC_ID = /ADESSO/V_BPU_DD-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_DD-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_DD-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_DD-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_DD-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_DUED.
    ENDIF.
/ADESSO/BPU_DUED-MANDT =
/ADESSO/V_BPU_DD-MANDT .
/ADESSO/BPU_DUED-PROC_ID =
/ADESSO/V_BPU_DD-PROC_ID .
/ADESSO/BPU_DUED-PROC_VERSION =
/ADESSO/V_BPU_DD-PROC_VERSION .
/ADESSO/BPU_DUED-PROC_STEP_NO =
/ADESSO/V_BPU_DD-PROC_STEP_NO .
/ADESSO/BPU_DUED-CHECK_ID =
/ADESSO/V_BPU_DD-CHECK_ID .
/ADESSO/BPU_DUED-CHECK_RESULT =
/ADESSO/V_BPU_DD-CHECK_RESULT .
/ADESSO/BPU_DUED-TIMTYP =
/ADESSO/V_BPU_DD-TIMTYP .
/ADESSO/BPU_DUED-TIMQTY =
/ADESSO/V_BPU_DD-TIMQTY .
/ADESSO/BPU_DUED-USER_COMMENT =
/ADESSO/V_BPU_DD-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_DUED .
    ELSE.
    INSERT /ADESSO/BPU_DUED .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_DD-UPD_FLAG,
STATUS_/ADESSO/V_BPU_DD-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_DD.
  SELECT SINGLE * FROM /ADESSO/BPU_DUED WHERE
PROC_ID = /ADESSO/V_BPU_DD-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_DD-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_DD-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_DD-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_DD-CHECK_RESULT .
/ADESSO/V_BPU_DD-MANDT =
/ADESSO/BPU_DUED-MANDT .
/ADESSO/V_BPU_DD-PROC_ID =
/ADESSO/BPU_DUED-PROC_ID .
/ADESSO/V_BPU_DD-PROC_VERSION =
/ADESSO/BPU_DUED-PROC_VERSION .
/ADESSO/V_BPU_DD-PROC_STEP_NO =
/ADESSO/BPU_DUED-PROC_STEP_NO .
/ADESSO/V_BPU_DD-CHECK_ID =
/ADESSO/BPU_DUED-CHECK_ID .
/ADESSO/V_BPU_DD-CHECK_RESULT =
/ADESSO/BPU_DUED-CHECK_RESULT .
/ADESSO/V_BPU_DD-TIMTYP =
/ADESSO/BPU_DUED-TIMTYP .
/ADESSO/V_BPU_DD-TIMQTY =
/ADESSO/BPU_DUED-TIMQTY .
/ADESSO/V_BPU_DD-USER_COMMENT =
/ADESSO/BPU_DUED-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_DD USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_DD-PROC_ID TO
/ADESSO/BPU_DUED-PROC_ID .
MOVE /ADESSO/V_BPU_DD-PROC_VERSION TO
/ADESSO/BPU_DUED-PROC_VERSION .
MOVE /ADESSO/V_BPU_DD-PROC_STEP_NO TO
/ADESSO/BPU_DUED-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_DD-CHECK_ID TO
/ADESSO/BPU_DUED-CHECK_ID .
MOVE /ADESSO/V_BPU_DD-CHECK_RESULT TO
/ADESSO/BPU_DUED-CHECK_RESULT .
MOVE /ADESSO/V_BPU_DD-MANDT TO
/ADESSO/BPU_DUED-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_DUED'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_DUED TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_DUED'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_ES................................*
FORM GET_DATA_/ADESSO/V_BPU_ES.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_ESM WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_ES .
/ADESSO/V_BPU_ES-MANDT =
/ADESSO/BPU_ESM-MANDT .
/ADESSO/V_BPU_ES-PROC_ID =
/ADESSO/BPU_ESM-PROC_ID .
/ADESSO/V_BPU_ES-PROC_VERSION =
/ADESSO/BPU_ESM-PROC_VERSION .
/ADESSO/V_BPU_ES-PROC_STEP_NO =
/ADESSO/BPU_ESM-PROC_STEP_NO .
/ADESSO/V_BPU_ES-CHECK_ID =
/ADESSO/BPU_ESM-CHECK_ID .
/ADESSO/V_BPU_ES-CHECK_RESULT =
/ADESSO/BPU_ESM-CHECK_RESULT .
/ADESSO/V_BPU_ES-EXEC_SOL_MET_TYPE =
/ADESSO/BPU_ESM-EXEC_SOL_MET_TYPE .
/ADESSO/V_BPU_ES-USER_COMMENT =
/ADESSO/BPU_ESM-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_ES.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_ES .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_ES.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_ES-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_ESM WHERE
  PROC_ID = /ADESSO/V_BPU_ES-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_ES-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_ES-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_ES-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_ES-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_ESM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_ESM WHERE
  PROC_ID = /ADESSO/V_BPU_ES-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_ES-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_ES-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_ES-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_ES-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_ESM.
    ENDIF.
/ADESSO/BPU_ESM-MANDT =
/ADESSO/V_BPU_ES-MANDT .
/ADESSO/BPU_ESM-PROC_ID =
/ADESSO/V_BPU_ES-PROC_ID .
/ADESSO/BPU_ESM-PROC_VERSION =
/ADESSO/V_BPU_ES-PROC_VERSION .
/ADESSO/BPU_ESM-PROC_STEP_NO =
/ADESSO/V_BPU_ES-PROC_STEP_NO .
/ADESSO/BPU_ESM-CHECK_ID =
/ADESSO/V_BPU_ES-CHECK_ID .
/ADESSO/BPU_ESM-CHECK_RESULT =
/ADESSO/V_BPU_ES-CHECK_RESULT .
/ADESSO/BPU_ESM-EXEC_SOL_MET_TYPE =
/ADESSO/V_BPU_ES-EXEC_SOL_MET_TYPE .
/ADESSO/BPU_ESM-USER_COMMENT =
/ADESSO/V_BPU_ES-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_ESM .
    ELSE.
    INSERT /ADESSO/BPU_ESM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_ES-UPD_FLAG,
STATUS_/ADESSO/V_BPU_ES-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_ES.
  SELECT SINGLE * FROM /ADESSO/BPU_ESM WHERE
PROC_ID = /ADESSO/V_BPU_ES-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_ES-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_ES-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_ES-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_ES-CHECK_RESULT .
/ADESSO/V_BPU_ES-MANDT =
/ADESSO/BPU_ESM-MANDT .
/ADESSO/V_BPU_ES-PROC_ID =
/ADESSO/BPU_ESM-PROC_ID .
/ADESSO/V_BPU_ES-PROC_VERSION =
/ADESSO/BPU_ESM-PROC_VERSION .
/ADESSO/V_BPU_ES-PROC_STEP_NO =
/ADESSO/BPU_ESM-PROC_STEP_NO .
/ADESSO/V_BPU_ES-CHECK_ID =
/ADESSO/BPU_ESM-CHECK_ID .
/ADESSO/V_BPU_ES-CHECK_RESULT =
/ADESSO/BPU_ESM-CHECK_RESULT .
/ADESSO/V_BPU_ES-EXEC_SOL_MET_TYPE =
/ADESSO/BPU_ESM-EXEC_SOL_MET_TYPE .
/ADESSO/V_BPU_ES-USER_COMMENT =
/ADESSO/BPU_ESM-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_ES USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_ES-PROC_ID TO
/ADESSO/BPU_ESM-PROC_ID .
MOVE /ADESSO/V_BPU_ES-PROC_VERSION TO
/ADESSO/BPU_ESM-PROC_VERSION .
MOVE /ADESSO/V_BPU_ES-PROC_STEP_NO TO
/ADESSO/BPU_ESM-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_ES-CHECK_ID TO
/ADESSO/BPU_ESM-CHECK_ID .
MOVE /ADESSO/V_BPU_ES-CHECK_RESULT TO
/ADESSO/BPU_ESM-CHECK_RESULT .
MOVE /ADESSO/V_BPU_ES-MANDT TO
/ADESSO/BPU_ESM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_ESM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_ESM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_ESM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_GE................................*
FORM GET_DATA_/ADESSO/V_BPU_GE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_GEN WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_GE .
/ADESSO/V_BPU_GE-MANDT =
/ADESSO/BPU_GEN-MANDT .
/ADESSO/V_BPU_GE-BPAREA =
/ADESSO/BPU_GEN-BPAREA .
/ADESSO/V_BPU_GE-DATA_PROV_CLASS =
/ADESSO/BPU_GEN-DATA_PROV_CLASS .
/ADESSO/V_BPU_GE-OBJ_DISPLAY_CLASS =
/ADESSO/BPU_GEN-OBJ_DISPLAY_CLASS .
/ADESSO/V_BPU_GE-WMODE_START_EMMACL =
/ADESSO/BPU_GEN-WMODE_START_EMMACL .
/ADESSO/V_BPU_GE-WMODE_START_EMMACLS =
/ADESSO/BPU_GEN-WMODE_START_EMMACLS .
/ADESSO/V_BPU_GE-START_SCREEN =
/ADESSO/BPU_GEN-START_SCREEN .
/ADESSO/V_BPU_GE-EXEC_SOL_MET_TYPE_STD =
/ADESSO/BPU_GEN-EXEC_SOL_MET_TYPE_STD .
/ADESSO/V_BPU_GE-CASETXT_SOURCE_STD =
/ADESSO/BPU_GEN-CASETXT_SOURCE_STD .
/ADESSO/V_BPU_GE-BUFFER_SIZE_CASE =
/ADESSO/BPU_GEN-BUFFER_SIZE_CASE .
/ADESSO/V_BPU_GE-USER_COMMENT =
/ADESSO/BPU_GEN-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_GE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_GE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_GE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_GE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_GEN WHERE
  BPAREA = /ADESSO/V_BPU_GE-BPAREA .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_GEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_GEN WHERE
  BPAREA = /ADESSO/V_BPU_GE-BPAREA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_GEN.
    ENDIF.
/ADESSO/BPU_GEN-MANDT =
/ADESSO/V_BPU_GE-MANDT .
/ADESSO/BPU_GEN-BPAREA =
/ADESSO/V_BPU_GE-BPAREA .
/ADESSO/BPU_GEN-DATA_PROV_CLASS =
/ADESSO/V_BPU_GE-DATA_PROV_CLASS .
/ADESSO/BPU_GEN-OBJ_DISPLAY_CLASS =
/ADESSO/V_BPU_GE-OBJ_DISPLAY_CLASS .
/ADESSO/BPU_GEN-WMODE_START_EMMACL =
/ADESSO/V_BPU_GE-WMODE_START_EMMACL .
/ADESSO/BPU_GEN-WMODE_START_EMMACLS =
/ADESSO/V_BPU_GE-WMODE_START_EMMACLS .
/ADESSO/BPU_GEN-START_SCREEN =
/ADESSO/V_BPU_GE-START_SCREEN .
/ADESSO/BPU_GEN-EXEC_SOL_MET_TYPE_STD =
/ADESSO/V_BPU_GE-EXEC_SOL_MET_TYPE_STD .
/ADESSO/BPU_GEN-CASETXT_SOURCE_STD =
/ADESSO/V_BPU_GE-CASETXT_SOURCE_STD .
/ADESSO/BPU_GEN-BUFFER_SIZE_CASE =
/ADESSO/V_BPU_GE-BUFFER_SIZE_CASE .
/ADESSO/BPU_GEN-USER_COMMENT =
/ADESSO/V_BPU_GE-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_GEN .
    ELSE.
    INSERT /ADESSO/BPU_GEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_GE-UPD_FLAG,
STATUS_/ADESSO/V_BPU_GE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_GE.
  SELECT SINGLE * FROM /ADESSO/BPU_GEN WHERE
BPAREA = /ADESSO/V_BPU_GE-BPAREA .
/ADESSO/V_BPU_GE-MANDT =
/ADESSO/BPU_GEN-MANDT .
/ADESSO/V_BPU_GE-BPAREA =
/ADESSO/BPU_GEN-BPAREA .
/ADESSO/V_BPU_GE-DATA_PROV_CLASS =
/ADESSO/BPU_GEN-DATA_PROV_CLASS .
/ADESSO/V_BPU_GE-OBJ_DISPLAY_CLASS =
/ADESSO/BPU_GEN-OBJ_DISPLAY_CLASS .
/ADESSO/V_BPU_GE-WMODE_START_EMMACL =
/ADESSO/BPU_GEN-WMODE_START_EMMACL .
/ADESSO/V_BPU_GE-WMODE_START_EMMACLS =
/ADESSO/BPU_GEN-WMODE_START_EMMACLS .
/ADESSO/V_BPU_GE-START_SCREEN =
/ADESSO/BPU_GEN-START_SCREEN .
/ADESSO/V_BPU_GE-EXEC_SOL_MET_TYPE_STD =
/ADESSO/BPU_GEN-EXEC_SOL_MET_TYPE_STD .
/ADESSO/V_BPU_GE-CASETXT_SOURCE_STD =
/ADESSO/BPU_GEN-CASETXT_SOURCE_STD .
/ADESSO/V_BPU_GE-BUFFER_SIZE_CASE =
/ADESSO/BPU_GEN-BUFFER_SIZE_CASE .
/ADESSO/V_BPU_GE-USER_COMMENT =
/ADESSO/BPU_GEN-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_GE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_GE-BPAREA TO
/ADESSO/BPU_GEN-BPAREA .
MOVE /ADESSO/V_BPU_GE-MANDT TO
/ADESSO/BPU_GEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_GEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_GEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_GEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_ID................................*
FORM GET_DATA_/ADESSO/V_BPU_ID.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_ID WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_ID .
/ADESSO/V_BPU_ID-MANDT =
/ADESSO/BPU_ID-MANDT .
/ADESSO/V_BPU_ID-BPAREA =
/ADESSO/BPU_ID-BPAREA .
/ADESSO/V_BPU_ID-OBJ_GROUP_ID =
/ADESSO/BPU_ID-OBJ_GROUP_ID .
/ADESSO/V_BPU_ID-OBJ_GROUP_DESCRIPTION =
/ADESSO/BPU_ID-OBJ_GROUP_DESCRIPTION .
/ADESSO/V_BPU_ID-USER_COMMENT =
/ADESSO/BPU_ID-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_ID.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_ID .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_ID.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_ID-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_ID WHERE
  BPAREA = /ADESSO/V_BPU_ID-BPAREA AND
  OBJ_GROUP_ID = /ADESSO/V_BPU_ID-OBJ_GROUP_ID .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_ID .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_ID WHERE
  BPAREA = /ADESSO/V_BPU_ID-BPAREA AND
  OBJ_GROUP_ID = /ADESSO/V_BPU_ID-OBJ_GROUP_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_ID.
    ENDIF.
/ADESSO/BPU_ID-MANDT =
/ADESSO/V_BPU_ID-MANDT .
/ADESSO/BPU_ID-BPAREA =
/ADESSO/V_BPU_ID-BPAREA .
/ADESSO/BPU_ID-OBJ_GROUP_ID =
/ADESSO/V_BPU_ID-OBJ_GROUP_ID .
/ADESSO/BPU_ID-OBJ_GROUP_DESCRIPTION =
/ADESSO/V_BPU_ID-OBJ_GROUP_DESCRIPTION .
/ADESSO/BPU_ID-USER_COMMENT =
/ADESSO/V_BPU_ID-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_ID .
    ELSE.
    INSERT /ADESSO/BPU_ID .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_ID-UPD_FLAG,
STATUS_/ADESSO/V_BPU_ID-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_ID.
  SELECT SINGLE * FROM /ADESSO/BPU_ID WHERE
BPAREA = /ADESSO/V_BPU_ID-BPAREA AND
OBJ_GROUP_ID = /ADESSO/V_BPU_ID-OBJ_GROUP_ID .
/ADESSO/V_BPU_ID-MANDT =
/ADESSO/BPU_ID-MANDT .
/ADESSO/V_BPU_ID-BPAREA =
/ADESSO/BPU_ID-BPAREA .
/ADESSO/V_BPU_ID-OBJ_GROUP_ID =
/ADESSO/BPU_ID-OBJ_GROUP_ID .
/ADESSO/V_BPU_ID-OBJ_GROUP_DESCRIPTION =
/ADESSO/BPU_ID-OBJ_GROUP_DESCRIPTION .
/ADESSO/V_BPU_ID-USER_COMMENT =
/ADESSO/BPU_ID-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_ID USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_ID-BPAREA TO
/ADESSO/BPU_ID-BPAREA .
MOVE /ADESSO/V_BPU_ID-OBJ_GROUP_ID TO
/ADESSO/BPU_ID-OBJ_GROUP_ID .
MOVE /ADESSO/V_BPU_ID-MANDT TO
/ADESSO/BPU_ID-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_ID'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_ID TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_ID'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_OB................................*
FORM GET_DATA_/ADESSO/V_BPU_OB.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_OBJ WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_OB .
/ADESSO/V_BPU_OB-MANDT =
/ADESSO/BPU_OBJ-MANDT .
/ADESSO/V_BPU_OB-BPAREA =
/ADESSO/BPU_OBJ-BPAREA .
/ADESSO/V_BPU_OB-OBJ_GROUP_ID =
/ADESSO/BPU_OBJ-OBJ_GROUP_ID .
/ADESSO/V_BPU_OB-OBJECT =
/ADESSO/BPU_OBJ-OBJECT .
/ADESSO/V_BPU_OB-REFOBJTYPE =
/ADESSO/BPU_OBJ-REFOBJTYPE .
/ADESSO/V_BPU_OB-REFSTRUCT =
/ADESSO/BPU_OBJ-REFSTRUCT .
/ADESSO/V_BPU_OB-REFFIELD =
/ADESSO/BPU_OBJ-REFFIELD .
/ADESSO/V_BPU_OB-METHOD =
/ADESSO/BPU_OBJ-METHOD .
/ADESSO/V_BPU_OB-DISPLAY_METHOD =
/ADESSO/BPU_OBJ-DISPLAY_METHOD .
/ADESSO/V_BPU_OB-USER_COMMENT =
/ADESSO/BPU_OBJ-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_OB.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_OB .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_OB.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_OB-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_OBJ WHERE
  BPAREA = /ADESSO/V_BPU_OB-BPAREA AND
  OBJ_GROUP_ID = /ADESSO/V_BPU_OB-OBJ_GROUP_ID AND
  OBJECT = /ADESSO/V_BPU_OB-OBJECT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_OBJ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_OBJ WHERE
  BPAREA = /ADESSO/V_BPU_OB-BPAREA AND
  OBJ_GROUP_ID = /ADESSO/V_BPU_OB-OBJ_GROUP_ID AND
  OBJECT = /ADESSO/V_BPU_OB-OBJECT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_OBJ.
    ENDIF.
/ADESSO/BPU_OBJ-MANDT =
/ADESSO/V_BPU_OB-MANDT .
/ADESSO/BPU_OBJ-BPAREA =
/ADESSO/V_BPU_OB-BPAREA .
/ADESSO/BPU_OBJ-OBJ_GROUP_ID =
/ADESSO/V_BPU_OB-OBJ_GROUP_ID .
/ADESSO/BPU_OBJ-OBJECT =
/ADESSO/V_BPU_OB-OBJECT .
/ADESSO/BPU_OBJ-REFOBJTYPE =
/ADESSO/V_BPU_OB-REFOBJTYPE .
/ADESSO/BPU_OBJ-REFSTRUCT =
/ADESSO/V_BPU_OB-REFSTRUCT .
/ADESSO/BPU_OBJ-REFFIELD =
/ADESSO/V_BPU_OB-REFFIELD .
/ADESSO/BPU_OBJ-METHOD =
/ADESSO/V_BPU_OB-METHOD .
/ADESSO/BPU_OBJ-DISPLAY_METHOD =
/ADESSO/V_BPU_OB-DISPLAY_METHOD .
/ADESSO/BPU_OBJ-USER_COMMENT =
/ADESSO/V_BPU_OB-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_OBJ .
    ELSE.
    INSERT /ADESSO/BPU_OBJ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_OB-UPD_FLAG,
STATUS_/ADESSO/V_BPU_OB-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_OB.
  SELECT SINGLE * FROM /ADESSO/BPU_OBJ WHERE
BPAREA = /ADESSO/V_BPU_OB-BPAREA AND
OBJ_GROUP_ID = /ADESSO/V_BPU_OB-OBJ_GROUP_ID AND
OBJECT = /ADESSO/V_BPU_OB-OBJECT .
/ADESSO/V_BPU_OB-MANDT =
/ADESSO/BPU_OBJ-MANDT .
/ADESSO/V_BPU_OB-BPAREA =
/ADESSO/BPU_OBJ-BPAREA .
/ADESSO/V_BPU_OB-OBJ_GROUP_ID =
/ADESSO/BPU_OBJ-OBJ_GROUP_ID .
/ADESSO/V_BPU_OB-OBJECT =
/ADESSO/BPU_OBJ-OBJECT .
/ADESSO/V_BPU_OB-REFOBJTYPE =
/ADESSO/BPU_OBJ-REFOBJTYPE .
/ADESSO/V_BPU_OB-REFSTRUCT =
/ADESSO/BPU_OBJ-REFSTRUCT .
/ADESSO/V_BPU_OB-REFFIELD =
/ADESSO/BPU_OBJ-REFFIELD .
/ADESSO/V_BPU_OB-METHOD =
/ADESSO/BPU_OBJ-METHOD .
/ADESSO/V_BPU_OB-DISPLAY_METHOD =
/ADESSO/BPU_OBJ-DISPLAY_METHOD .
/ADESSO/V_BPU_OB-USER_COMMENT =
/ADESSO/BPU_OBJ-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_OB USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_OB-BPAREA TO
/ADESSO/BPU_OBJ-BPAREA .
MOVE /ADESSO/V_BPU_OB-OBJ_GROUP_ID TO
/ADESSO/BPU_OBJ-OBJ_GROUP_ID .
MOVE /ADESSO/V_BPU_OB-OBJECT TO
/ADESSO/BPU_OBJ-OBJECT .
MOVE /ADESSO/V_BPU_OB-MANDT TO
/ADESSO/BPU_OBJ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_OBJ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_OBJ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_OBJ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_PI................................*
FORM GET_DATA_/ADESSO/V_BPU_PI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_PID WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_PI .
/ADESSO/V_BPU_PI-MANDT =
/ADESSO/BPU_PID-MANDT .
/ADESSO/V_BPU_PI-PROC_ID =
/ADESSO/BPU_PID-PROC_ID .
/ADESSO/V_BPU_PI-PROC_VERSION =
/ADESSO/BPU_PID-PROC_VERSION .
/ADESSO/V_BPU_PI-PROC_STEP_NO =
/ADESSO/BPU_PID-PROC_STEP_NO .
/ADESSO/V_BPU_PI-CHECK_ID =
/ADESSO/BPU_PID-CHECK_ID .
/ADESSO/V_BPU_PI-CHECK_RESULT =
/ADESSO/BPU_PID-CHECK_RESULT .
/ADESSO/V_BPU_PI-OBJ_GROUP_ID =
/ADESSO/BPU_PID-OBJ_GROUP_ID .
/ADESSO/V_BPU_PI-USER_COMMENT =
/ADESSO/BPU_PID-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_PI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_PI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_PI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_PI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_PID WHERE
  PROC_ID = /ADESSO/V_BPU_PI-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_PI-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_PI-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_PI-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_PI-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_PID .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_PID WHERE
  PROC_ID = /ADESSO/V_BPU_PI-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_PI-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_PI-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_PI-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_PI-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_PID.
    ENDIF.
/ADESSO/BPU_PID-MANDT =
/ADESSO/V_BPU_PI-MANDT .
/ADESSO/BPU_PID-PROC_ID =
/ADESSO/V_BPU_PI-PROC_ID .
/ADESSO/BPU_PID-PROC_VERSION =
/ADESSO/V_BPU_PI-PROC_VERSION .
/ADESSO/BPU_PID-PROC_STEP_NO =
/ADESSO/V_BPU_PI-PROC_STEP_NO .
/ADESSO/BPU_PID-CHECK_ID =
/ADESSO/V_BPU_PI-CHECK_ID .
/ADESSO/BPU_PID-CHECK_RESULT =
/ADESSO/V_BPU_PI-CHECK_RESULT .
/ADESSO/BPU_PID-OBJ_GROUP_ID =
/ADESSO/V_BPU_PI-OBJ_GROUP_ID .
/ADESSO/BPU_PID-USER_COMMENT =
/ADESSO/V_BPU_PI-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_PID .
    ELSE.
    INSERT /ADESSO/BPU_PID .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_PI-UPD_FLAG,
STATUS_/ADESSO/V_BPU_PI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_PI.
  SELECT SINGLE * FROM /ADESSO/BPU_PID WHERE
PROC_ID = /ADESSO/V_BPU_PI-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_PI-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_PI-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_PI-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_PI-CHECK_RESULT .
/ADESSO/V_BPU_PI-MANDT =
/ADESSO/BPU_PID-MANDT .
/ADESSO/V_BPU_PI-PROC_ID =
/ADESSO/BPU_PID-PROC_ID .
/ADESSO/V_BPU_PI-PROC_VERSION =
/ADESSO/BPU_PID-PROC_VERSION .
/ADESSO/V_BPU_PI-PROC_STEP_NO =
/ADESSO/BPU_PID-PROC_STEP_NO .
/ADESSO/V_BPU_PI-CHECK_ID =
/ADESSO/BPU_PID-CHECK_ID .
/ADESSO/V_BPU_PI-CHECK_RESULT =
/ADESSO/BPU_PID-CHECK_RESULT .
/ADESSO/V_BPU_PI-OBJ_GROUP_ID =
/ADESSO/BPU_PID-OBJ_GROUP_ID .
/ADESSO/V_BPU_PI-USER_COMMENT =
/ADESSO/BPU_PID-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_PI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_PI-PROC_ID TO
/ADESSO/BPU_PID-PROC_ID .
MOVE /ADESSO/V_BPU_PI-PROC_VERSION TO
/ADESSO/BPU_PID-PROC_VERSION .
MOVE /ADESSO/V_BPU_PI-PROC_STEP_NO TO
/ADESSO/BPU_PID-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_PI-CHECK_ID TO
/ADESSO/BPU_PID-CHECK_ID .
MOVE /ADESSO/V_BPU_PI-CHECK_RESULT TO
/ADESSO/BPU_PID-CHECK_RESULT .
MOVE /ADESSO/V_BPU_PI-MANDT TO
/ADESSO/BPU_PID-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_PID'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_PID TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_PID'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_PR................................*
FORM GET_DATA_/ADESSO/V_BPU_PR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_PRIO WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_PR .
/ADESSO/V_BPU_PR-MANDT =
/ADESSO/BPU_PRIO-MANDT .
/ADESSO/V_BPU_PR-PROC_ID =
/ADESSO/BPU_PRIO-PROC_ID .
/ADESSO/V_BPU_PR-PROC_VERSION =
/ADESSO/BPU_PRIO-PROC_VERSION .
/ADESSO/V_BPU_PR-PROC_STEP_NO =
/ADESSO/BPU_PRIO-PROC_STEP_NO .
/ADESSO/V_BPU_PR-CHECK_ID =
/ADESSO/BPU_PRIO-CHECK_ID .
/ADESSO/V_BPU_PR-CHECK_RESULT =
/ADESSO/BPU_PRIO-CHECK_RESULT .
/ADESSO/V_BPU_PR-PRIO =
/ADESSO/BPU_PRIO-PRIO .
/ADESSO/V_BPU_PR-USER_COMMENT =
/ADESSO/BPU_PRIO-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_PR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_PR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_PR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_PR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_PRIO WHERE
  PROC_ID = /ADESSO/V_BPU_PR-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_PR-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_PR-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_PR-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_PR-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_PRIO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_PRIO WHERE
  PROC_ID = /ADESSO/V_BPU_PR-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_PR-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_PR-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_PR-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_PR-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_PRIO.
    ENDIF.
/ADESSO/BPU_PRIO-MANDT =
/ADESSO/V_BPU_PR-MANDT .
/ADESSO/BPU_PRIO-PROC_ID =
/ADESSO/V_BPU_PR-PROC_ID .
/ADESSO/BPU_PRIO-PROC_VERSION =
/ADESSO/V_BPU_PR-PROC_VERSION .
/ADESSO/BPU_PRIO-PROC_STEP_NO =
/ADESSO/V_BPU_PR-PROC_STEP_NO .
/ADESSO/BPU_PRIO-CHECK_ID =
/ADESSO/V_BPU_PR-CHECK_ID .
/ADESSO/BPU_PRIO-CHECK_RESULT =
/ADESSO/V_BPU_PR-CHECK_RESULT .
/ADESSO/BPU_PRIO-PRIO =
/ADESSO/V_BPU_PR-PRIO .
/ADESSO/BPU_PRIO-USER_COMMENT =
/ADESSO/V_BPU_PR-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_PRIO .
    ELSE.
    INSERT /ADESSO/BPU_PRIO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_PR-UPD_FLAG,
STATUS_/ADESSO/V_BPU_PR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_PR.
  SELECT SINGLE * FROM /ADESSO/BPU_PRIO WHERE
PROC_ID = /ADESSO/V_BPU_PR-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_PR-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_PR-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_PR-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_PR-CHECK_RESULT .
/ADESSO/V_BPU_PR-MANDT =
/ADESSO/BPU_PRIO-MANDT .
/ADESSO/V_BPU_PR-PROC_ID =
/ADESSO/BPU_PRIO-PROC_ID .
/ADESSO/V_BPU_PR-PROC_VERSION =
/ADESSO/BPU_PRIO-PROC_VERSION .
/ADESSO/V_BPU_PR-PROC_STEP_NO =
/ADESSO/BPU_PRIO-PROC_STEP_NO .
/ADESSO/V_BPU_PR-CHECK_ID =
/ADESSO/BPU_PRIO-CHECK_ID .
/ADESSO/V_BPU_PR-CHECK_RESULT =
/ADESSO/BPU_PRIO-CHECK_RESULT .
/ADESSO/V_BPU_PR-PRIO =
/ADESSO/BPU_PRIO-PRIO .
/ADESSO/V_BPU_PR-USER_COMMENT =
/ADESSO/BPU_PRIO-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_PR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_PR-PROC_ID TO
/ADESSO/BPU_PRIO-PROC_ID .
MOVE /ADESSO/V_BPU_PR-PROC_VERSION TO
/ADESSO/BPU_PRIO-PROC_VERSION .
MOVE /ADESSO/V_BPU_PR-PROC_STEP_NO TO
/ADESSO/BPU_PRIO-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_PR-CHECK_ID TO
/ADESSO/BPU_PRIO-CHECK_ID .
MOVE /ADESSO/V_BPU_PR-CHECK_RESULT TO
/ADESSO/BPU_PRIO-CHECK_RESULT .
MOVE /ADESSO/V_BPU_PR-MANDT TO
/ADESSO/BPU_PRIO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_PRIO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_PRIO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_PRIO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_RD................................*
FORM GET_DATA_/ADESSO/V_BPU_RD.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_RDP WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_RD .
/ADESSO/V_BPU_RD-MANDT =
/ADESSO/BPU_RDP-MANDT .
/ADESSO/V_BPU_RD-BPAREA =
/ADESSO/BPU_RDP-BPAREA .
/ADESSO/V_BPU_RD-CCRULE =
/ADESSO/BPU_RDP-CCRULE .
/ADESSO/V_BPU_RD-OBJECT =
/ADESSO/BPU_RDP-OBJECT .
/ADESSO/V_BPU_RD-METHOD =
/ADESSO/BPU_RDP-METHOD .
/ADESSO/V_BPU_RD-USER_COMMENT =
/ADESSO/BPU_RDP-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_RD.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_RD .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_RD.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_RD-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_RDP WHERE
  BPAREA = /ADESSO/V_BPU_RD-BPAREA AND
  CCRULE = /ADESSO/V_BPU_RD-CCRULE AND
  OBJECT = /ADESSO/V_BPU_RD-OBJECT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_RDP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_RDP WHERE
  BPAREA = /ADESSO/V_BPU_RD-BPAREA AND
  CCRULE = /ADESSO/V_BPU_RD-CCRULE AND
  OBJECT = /ADESSO/V_BPU_RD-OBJECT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_RDP.
    ENDIF.
/ADESSO/BPU_RDP-MANDT =
/ADESSO/V_BPU_RD-MANDT .
/ADESSO/BPU_RDP-BPAREA =
/ADESSO/V_BPU_RD-BPAREA .
/ADESSO/BPU_RDP-CCRULE =
/ADESSO/V_BPU_RD-CCRULE .
/ADESSO/BPU_RDP-OBJECT =
/ADESSO/V_BPU_RD-OBJECT .
/ADESSO/BPU_RDP-METHOD =
/ADESSO/V_BPU_RD-METHOD .
/ADESSO/BPU_RDP-USER_COMMENT =
/ADESSO/V_BPU_RD-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_RDP .
    ELSE.
    INSERT /ADESSO/BPU_RDP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_RD-UPD_FLAG,
STATUS_/ADESSO/V_BPU_RD-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_RD.
  SELECT SINGLE * FROM /ADESSO/BPU_RDP WHERE
BPAREA = /ADESSO/V_BPU_RD-BPAREA AND
CCRULE = /ADESSO/V_BPU_RD-CCRULE AND
OBJECT = /ADESSO/V_BPU_RD-OBJECT .
/ADESSO/V_BPU_RD-MANDT =
/ADESSO/BPU_RDP-MANDT .
/ADESSO/V_BPU_RD-BPAREA =
/ADESSO/BPU_RDP-BPAREA .
/ADESSO/V_BPU_RD-CCRULE =
/ADESSO/BPU_RDP-CCRULE .
/ADESSO/V_BPU_RD-OBJECT =
/ADESSO/BPU_RDP-OBJECT .
/ADESSO/V_BPU_RD-METHOD =
/ADESSO/BPU_RDP-METHOD .
/ADESSO/V_BPU_RD-USER_COMMENT =
/ADESSO/BPU_RDP-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_RD USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_RD-BPAREA TO
/ADESSO/BPU_RDP-BPAREA .
MOVE /ADESSO/V_BPU_RD-CCRULE TO
/ADESSO/BPU_RDP-CCRULE .
MOVE /ADESSO/V_BPU_RD-OBJECT TO
/ADESSO/BPU_RDP-OBJECT .
MOVE /ADESSO/V_BPU_RD-MANDT TO
/ADESSO/BPU_RDP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_RDP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_RDP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_RDP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_RU................................*
FORM GET_DATA_/ADESSO/V_BPU_RU.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_RULE WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_RU .
/ADESSO/V_BPU_RU-MANDT =
/ADESSO/BPU_RULE-MANDT .
/ADESSO/V_BPU_RU-PROC_ID =
/ADESSO/BPU_RULE-PROC_ID .
/ADESSO/V_BPU_RU-PROC_VERSION =
/ADESSO/BPU_RULE-PROC_VERSION .
/ADESSO/V_BPU_RU-PROC_STEP_NO =
/ADESSO/BPU_RULE-PROC_STEP_NO .
/ADESSO/V_BPU_RU-CHECK_ID =
/ADESSO/BPU_RULE-CHECK_ID .
/ADESSO/V_BPU_RU-CHECK_RESULT =
/ADESSO/BPU_RULE-CHECK_RESULT .
/ADESSO/V_BPU_RU-CCRULE =
/ADESSO/BPU_RULE-CCRULE .
/ADESSO/V_BPU_RU-USER_COMMENT =
/ADESSO/BPU_RULE-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_RU.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_RU .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_RU.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_RU-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_RULE WHERE
  PROC_ID = /ADESSO/V_BPU_RU-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_RU-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_RU-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_RU-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_RU-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_RULE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_RULE WHERE
  PROC_ID = /ADESSO/V_BPU_RU-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_RU-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_RU-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_RU-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_RU-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_RULE.
    ENDIF.
/ADESSO/BPU_RULE-MANDT =
/ADESSO/V_BPU_RU-MANDT .
/ADESSO/BPU_RULE-PROC_ID =
/ADESSO/V_BPU_RU-PROC_ID .
/ADESSO/BPU_RULE-PROC_VERSION =
/ADESSO/V_BPU_RU-PROC_VERSION .
/ADESSO/BPU_RULE-PROC_STEP_NO =
/ADESSO/V_BPU_RU-PROC_STEP_NO .
/ADESSO/BPU_RULE-CHECK_ID =
/ADESSO/V_BPU_RU-CHECK_ID .
/ADESSO/BPU_RULE-CHECK_RESULT =
/ADESSO/V_BPU_RU-CHECK_RESULT .
/ADESSO/BPU_RULE-CCRULE =
/ADESSO/V_BPU_RU-CCRULE .
/ADESSO/BPU_RULE-USER_COMMENT =
/ADESSO/V_BPU_RU-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_RULE .
    ELSE.
    INSERT /ADESSO/BPU_RULE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_RU-UPD_FLAG,
STATUS_/ADESSO/V_BPU_RU-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_RU.
  SELECT SINGLE * FROM /ADESSO/BPU_RULE WHERE
PROC_ID = /ADESSO/V_BPU_RU-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_RU-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_RU-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_RU-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_RU-CHECK_RESULT .
/ADESSO/V_BPU_RU-MANDT =
/ADESSO/BPU_RULE-MANDT .
/ADESSO/V_BPU_RU-PROC_ID =
/ADESSO/BPU_RULE-PROC_ID .
/ADESSO/V_BPU_RU-PROC_VERSION =
/ADESSO/BPU_RULE-PROC_VERSION .
/ADESSO/V_BPU_RU-PROC_STEP_NO =
/ADESSO/BPU_RULE-PROC_STEP_NO .
/ADESSO/V_BPU_RU-CHECK_ID =
/ADESSO/BPU_RULE-CHECK_ID .
/ADESSO/V_BPU_RU-CHECK_RESULT =
/ADESSO/BPU_RULE-CHECK_RESULT .
/ADESSO/V_BPU_RU-CCRULE =
/ADESSO/BPU_RULE-CCRULE .
/ADESSO/V_BPU_RU-USER_COMMENT =
/ADESSO/BPU_RULE-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_RU USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_RU-PROC_ID TO
/ADESSO/BPU_RULE-PROC_ID .
MOVE /ADESSO/V_BPU_RU-PROC_VERSION TO
/ADESSO/BPU_RULE-PROC_VERSION .
MOVE /ADESSO/V_BPU_RU-PROC_STEP_NO TO
/ADESSO/BPU_RULE-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_RU-CHECK_ID TO
/ADESSO/BPU_RULE-CHECK_ID .
MOVE /ADESSO/V_BPU_RU-CHECK_RESULT TO
/ADESSO/BPU_RULE-CHECK_RESULT .
MOVE /ADESSO/V_BPU_RU-MANDT TO
/ADESSO/BPU_RULE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_RULE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_RULE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_RULE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_SP................................*
FORM GET_DATA_/ADESSO/V_BPU_SP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_SOP WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_SP .
/ADESSO/V_BPU_SP-MANDT =
/ADESSO/BPU_SOP-MANDT .
/ADESSO/V_BPU_SP-PROC_ID =
/ADESSO/BPU_SOP-PROC_ID .
/ADESSO/V_BPU_SP-PROC_VERSION =
/ADESSO/BPU_SOP-PROC_VERSION .
/ADESSO/V_BPU_SP-PROC_STEP_NO =
/ADESSO/BPU_SOP-PROC_STEP_NO .
/ADESSO/V_BPU_SP-CHECK_ID =
/ADESSO/BPU_SOP-CHECK_ID .
/ADESSO/V_BPU_SP-CHECK_RESULT =
/ADESSO/BPU_SOP-CHECK_RESULT .
/ADESSO/V_BPU_SP-SEQNR =
/ADESSO/BPU_SOP-SEQNR .
/ADESSO/V_BPU_SP-ICON =
/ADESSO/BPU_SOP-ICON .
/ADESSO/V_BPU_SP-SOPTEXT =
/ADESSO/BPU_SOP-SOPTEXT .
/ADESSO/V_BPU_SP-HIDDEN =
/ADESSO/BPU_SOP-HIDDEN .
/ADESSO/V_BPU_SP-USER_COMMENT =
/ADESSO/BPU_SOP-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_SP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_SP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_SP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_SP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_SOP WHERE
  PROC_ID = /ADESSO/V_BPU_SP-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_SP-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_SP-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_SP-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_SP-CHECK_RESULT AND
  SEQNR = /ADESSO/V_BPU_SP-SEQNR .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_SOP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_SOP WHERE
  PROC_ID = /ADESSO/V_BPU_SP-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_SP-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_SP-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_SP-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_SP-CHECK_RESULT AND
  SEQNR = /ADESSO/V_BPU_SP-SEQNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_SOP.
    ENDIF.
/ADESSO/BPU_SOP-MANDT =
/ADESSO/V_BPU_SP-MANDT .
/ADESSO/BPU_SOP-PROC_ID =
/ADESSO/V_BPU_SP-PROC_ID .
/ADESSO/BPU_SOP-PROC_VERSION =
/ADESSO/V_BPU_SP-PROC_VERSION .
/ADESSO/BPU_SOP-PROC_STEP_NO =
/ADESSO/V_BPU_SP-PROC_STEP_NO .
/ADESSO/BPU_SOP-CHECK_ID =
/ADESSO/V_BPU_SP-CHECK_ID .
/ADESSO/BPU_SOP-CHECK_RESULT =
/ADESSO/V_BPU_SP-CHECK_RESULT .
/ADESSO/BPU_SOP-SEQNR =
/ADESSO/V_BPU_SP-SEQNR .
/ADESSO/BPU_SOP-ICON =
/ADESSO/V_BPU_SP-ICON .
/ADESSO/BPU_SOP-SOPTEXT =
/ADESSO/V_BPU_SP-SOPTEXT .
/ADESSO/BPU_SOP-HIDDEN =
/ADESSO/V_BPU_SP-HIDDEN .
/ADESSO/BPU_SOP-USER_COMMENT =
/ADESSO/V_BPU_SP-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_SOP .
    ELSE.
    INSERT /ADESSO/BPU_SOP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_SP-UPD_FLAG,
STATUS_/ADESSO/V_BPU_SP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_SP.
  SELECT SINGLE * FROM /ADESSO/BPU_SOP WHERE
PROC_ID = /ADESSO/V_BPU_SP-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_SP-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_SP-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_SP-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_SP-CHECK_RESULT AND
SEQNR = /ADESSO/V_BPU_SP-SEQNR .
/ADESSO/V_BPU_SP-MANDT =
/ADESSO/BPU_SOP-MANDT .
/ADESSO/V_BPU_SP-PROC_ID =
/ADESSO/BPU_SOP-PROC_ID .
/ADESSO/V_BPU_SP-PROC_VERSION =
/ADESSO/BPU_SOP-PROC_VERSION .
/ADESSO/V_BPU_SP-PROC_STEP_NO =
/ADESSO/BPU_SOP-PROC_STEP_NO .
/ADESSO/V_BPU_SP-CHECK_ID =
/ADESSO/BPU_SOP-CHECK_ID .
/ADESSO/V_BPU_SP-CHECK_RESULT =
/ADESSO/BPU_SOP-CHECK_RESULT .
/ADESSO/V_BPU_SP-SEQNR =
/ADESSO/BPU_SOP-SEQNR .
/ADESSO/V_BPU_SP-ICON =
/ADESSO/BPU_SOP-ICON .
/ADESSO/V_BPU_SP-SOPTEXT =
/ADESSO/BPU_SOP-SOPTEXT .
/ADESSO/V_BPU_SP-HIDDEN =
/ADESSO/BPU_SOP-HIDDEN .
/ADESSO/V_BPU_SP-USER_COMMENT =
/ADESSO/BPU_SOP-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_SP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_SP-PROC_ID TO
/ADESSO/BPU_SOP-PROC_ID .
MOVE /ADESSO/V_BPU_SP-PROC_VERSION TO
/ADESSO/BPU_SOP-PROC_VERSION .
MOVE /ADESSO/V_BPU_SP-PROC_STEP_NO TO
/ADESSO/BPU_SOP-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_SP-CHECK_ID TO
/ADESSO/BPU_SOP-CHECK_ID .
MOVE /ADESSO/V_BPU_SP-CHECK_RESULT TO
/ADESSO/BPU_SOP-CHECK_RESULT .
MOVE /ADESSO/V_BPU_SP-SEQNR TO
/ADESSO/BPU_SOP-SEQNR .
MOVE /ADESSO/V_BPU_SP-MANDT TO
/ADESSO/BPU_SOP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_SOP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_SOP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_SOP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPU_TX................................*
FORM GET_DATA_/ADESSO/V_BPU_TX.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPU_TXT WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPU_TX .
/ADESSO/V_BPU_TX-MANDT =
/ADESSO/BPU_TXT-MANDT .
/ADESSO/V_BPU_TX-PROC_ID =
/ADESSO/BPU_TXT-PROC_ID .
/ADESSO/V_BPU_TX-PROC_VERSION =
/ADESSO/BPU_TXT-PROC_VERSION .
/ADESSO/V_BPU_TX-PROC_STEP_NO =
/ADESSO/BPU_TXT-PROC_STEP_NO .
/ADESSO/V_BPU_TX-CHECK_ID =
/ADESSO/BPU_TXT-CHECK_ID .
/ADESSO/V_BPU_TX-CHECK_RESULT =
/ADESSO/BPU_TXT-CHECK_RESULT .
/ADESSO/V_BPU_TX-CASETXT_SOURCE =
/ADESSO/BPU_TXT-CASETXT_SOURCE .
/ADESSO/V_BPU_TX-CASETXT =
/ADESSO/BPU_TXT-CASETXT .
/ADESSO/V_BPU_TX-TDNAME =
/ADESSO/BPU_TXT-TDNAME .
/ADESSO/V_BPU_TX-USER_COMMENT =
/ADESSO/BPU_TXT-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPU_TX.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPU_TX .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPU_TX.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPU_TX-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_TXT WHERE
  PROC_ID = /ADESSO/V_BPU_TX-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_TX-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_TX-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_TX-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_TX-CHECK_RESULT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPU_TXT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPU_TXT WHERE
  PROC_ID = /ADESSO/V_BPU_TX-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPU_TX-PROC_VERSION AND
  PROC_STEP_NO = /ADESSO/V_BPU_TX-PROC_STEP_NO AND
  CHECK_ID = /ADESSO/V_BPU_TX-CHECK_ID AND
  CHECK_RESULT = /ADESSO/V_BPU_TX-CHECK_RESULT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPU_TXT.
    ENDIF.
/ADESSO/BPU_TXT-MANDT =
/ADESSO/V_BPU_TX-MANDT .
/ADESSO/BPU_TXT-PROC_ID =
/ADESSO/V_BPU_TX-PROC_ID .
/ADESSO/BPU_TXT-PROC_VERSION =
/ADESSO/V_BPU_TX-PROC_VERSION .
/ADESSO/BPU_TXT-PROC_STEP_NO =
/ADESSO/V_BPU_TX-PROC_STEP_NO .
/ADESSO/BPU_TXT-CHECK_ID =
/ADESSO/V_BPU_TX-CHECK_ID .
/ADESSO/BPU_TXT-CHECK_RESULT =
/ADESSO/V_BPU_TX-CHECK_RESULT .
/ADESSO/BPU_TXT-CASETXT_SOURCE =
/ADESSO/V_BPU_TX-CASETXT_SOURCE .
/ADESSO/BPU_TXT-CASETXT =
/ADESSO/V_BPU_TX-CASETXT .
/ADESSO/BPU_TXT-TDNAME =
/ADESSO/V_BPU_TX-TDNAME .
/ADESSO/BPU_TXT-USER_COMMENT =
/ADESSO/V_BPU_TX-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPU_TXT .
    ELSE.
    INSERT /ADESSO/BPU_TXT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPU_TX-UPD_FLAG,
STATUS_/ADESSO/V_BPU_TX-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPU_TX.
  SELECT SINGLE * FROM /ADESSO/BPU_TXT WHERE
PROC_ID = /ADESSO/V_BPU_TX-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPU_TX-PROC_VERSION AND
PROC_STEP_NO = /ADESSO/V_BPU_TX-PROC_STEP_NO AND
CHECK_ID = /ADESSO/V_BPU_TX-CHECK_ID AND
CHECK_RESULT = /ADESSO/V_BPU_TX-CHECK_RESULT .
/ADESSO/V_BPU_TX-MANDT =
/ADESSO/BPU_TXT-MANDT .
/ADESSO/V_BPU_TX-PROC_ID =
/ADESSO/BPU_TXT-PROC_ID .
/ADESSO/V_BPU_TX-PROC_VERSION =
/ADESSO/BPU_TXT-PROC_VERSION .
/ADESSO/V_BPU_TX-PROC_STEP_NO =
/ADESSO/BPU_TXT-PROC_STEP_NO .
/ADESSO/V_BPU_TX-CHECK_ID =
/ADESSO/BPU_TXT-CHECK_ID .
/ADESSO/V_BPU_TX-CHECK_RESULT =
/ADESSO/BPU_TXT-CHECK_RESULT .
/ADESSO/V_BPU_TX-CASETXT_SOURCE =
/ADESSO/BPU_TXT-CASETXT_SOURCE .
/ADESSO/V_BPU_TX-CASETXT =
/ADESSO/BPU_TXT-CASETXT .
/ADESSO/V_BPU_TX-TDNAME =
/ADESSO/BPU_TXT-TDNAME .
/ADESSO/V_BPU_TX-USER_COMMENT =
/ADESSO/BPU_TXT-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPU_TX USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPU_TX-PROC_ID TO
/ADESSO/BPU_TXT-PROC_ID .
MOVE /ADESSO/V_BPU_TX-PROC_VERSION TO
/ADESSO/BPU_TXT-PROC_VERSION .
MOVE /ADESSO/V_BPU_TX-PROC_STEP_NO TO
/ADESSO/BPU_TXT-PROC_STEP_NO .
MOVE /ADESSO/V_BPU_TX-CHECK_ID TO
/ADESSO/BPU_TXT-CHECK_ID .
MOVE /ADESSO/V_BPU_TX-CHECK_RESULT TO
/ADESSO/BPU_TXT-CHECK_RESULT .
MOVE /ADESSO/V_BPU_TX-MANDT TO
/ADESSO/BPU_TXT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPU_TXT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPU_TXT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPU_TXT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
