************************************************************************
* Parallelverarbeitung von /ADESSO/HMV_IDOC_STATUS.
*
* Automatically created by RWLC_PROCESS_IN_PARALLEL.
*                  Version 4.70 - 1.10 from 04.01.2002.
*                       on 11.04.2016 - 13:33:27.
*
* Ändern Sie dieses Programm NIE manuell !!!!!!!!!!!!!.
* Ändern Sie ggf. das Customizing (Transaktion WLCPARC).
* und generieren Sie diesen Report erneut mit Transaktion WLCPAR.
************************************************************************
REPORT /ADESSO/HMV_IDOC_STATUS_PAR
       MESSAGE-ID WLC_PARALLEL LINE-SIZE 132.
INCLUDE WLC_REPORT_IN_PARALLELTOP.
INCLUDE WLC_REPORT_IN_PARALLELSEL1.
PARAMETERS GF_PTAB TYPE WLC_PRESELECT_PRIMARY_TABLE
           DEFAULT 'EDEXTASK'.
PARAMETERS GF_STAB TYPE WLC_PRESELECT_SECONDARY_TABLE
           DEFAULT 'EDEXTASKIDOC'.
PARAMETERS GF_WTFLD TYPE WLC_PRESELECT_WEIGHTING_FIELD
           DEFAULT '-DOCNUM'.
INCLUDE WLC_REPORT_IN_PARALLELSEL2.
TABLES EDEXTASK                      .
SELECT-OPTIONS _DEXPROC FOR EDEXTASK-DEXPROC
.
INCLUDE WLC_REPORT_IN_PARALLELSEL3.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $PAV0001 RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $PAV0001.
  SELECTION-SCREEN POSITION 35.
  PARAMETERS $PAV0004 RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 38(30) FOR FIELD $PAV0004.
SELECTION-SCREEN END   OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $PAV0002 RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $PAV0002.
  SELECTION-SCREEN POSITION 35.
  PARAMETERS $PAV0005 RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 38(30) FOR FIELD $PAV0005.
SELECTION-SCREEN END   OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $PAV0003 RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $PAV0003.
  SELECTION-SCREEN POSITION 35.
  PARAMETERS PAVOTHER RADIOBUTTON GROUP PAPT MODIF ID VIS.
  SELECTION-SCREEN POSITION 38.
  PARAMETERS if_paral TYPE WLC_FIELD_FOR_PARALL_PROCESS
                           VISIBLE LENGTH 45.
SELECTION-SCREEN END   OF LINE.

INCLUDE WLC_REPORT_IN_PARALLELSEL4.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $SOV0001 RADIOBUTTON GROUP SOPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $SOV0001.
  SELECTION-SCREEN POSITION 35.
  PARAMETERS $SOV0004 RADIOBUTTON GROUP SOPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 38(30) FOR FIELD $SOV0004.
SELECTION-SCREEN END   OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $SOV0002 RADIOBUTTON GROUP SOPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $SOV0002.
  SELECTION-SCREEN POSITION 35.
  PARAMETERS $SOV0005 RADIOBUTTON GROUP SOPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 38(30) FOR FIELD $SOV0005.
SELECTION-SCREEN END   OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 01.
  PARAMETERS $SOV0003 RADIOBUTTON GROUP SOPT MODIF ID VIS.
  SELECTION-SCREEN COMMENT 04(30) FOR FIELD $SOV0003.
SELECTION-SCREEN END   OF LINE.

INCLUDE WLC_REPORT_IN_PARALLELSEL5.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $PAV0001.
  PERFORM ON_HELP_FOR USING 'P' 0001 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $PAV0004.
  PERFORM ON_HELP_FOR USING 'P' 0004 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $PAV0002.
  PERFORM ON_HELP_FOR USING 'P' 0002 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $PAV0005.
  PERFORM ON_HELP_FOR USING 'P' 0005 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $PAV0003.
  PERFORM ON_HELP_FOR USING 'P' 0003 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $SOV0001.
  PERFORM ON_HELP_FOR USING 'S' 0001 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $SOV0004.
  PERFORM ON_HELP_FOR USING 'S' 0004 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $SOV0002.
  PERFORM ON_HELP_FOR USING 'S' 0002 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $SOV0005.
  PERFORM ON_HELP_FOR USING 'S' 0005 gt_selopts.
AT SELECTION-SCREEN ON HELP-REQUEST FOR $SOV0003.
  PERFORM ON_HELP_FOR USING 'S' 0003 gt_selopts.


INITIALIZATION.
  _selopt_append 0001 'SO_DATUM' 'X'
  'EDEXTASK-DEXAEDAT' &
  ''.
  _selopt_append 0004 'SO_SERVE' 'X'
  'EDEXTASK-DEXSERVPROV' &
  ''.
  _selopt_append 0002 'SO_TASKI' 'X'
  'EDEXTASK-DEXTASKID' &
  ''.
  _selopt_append 0005 'SO_INTUI' 'X'
  'EDEXTASK-INT_UI' &
  ''.
  _selopt_append 0003 'SO_SERV ' 'X'
  'EDEXTASK-DEXSERVPROVSELF' &
  ''.

  gf_selopt_count       =                   5.
  gf_invis_selopt_count =                   0.
  gf_selopt_max_entry   =                 250.

  gs_cust_options-report_name      = '/ADESSO/HMV_IDOC_STATUS'.
  gs_cust_options-presel_mode      = '2'.
  gs_cust_options-presel_fm        = ''.
  gs_cust_options-presel_prim_tab  = 'EDEXTASK'.
  gs_cust_options-prim_tab_weight  = ''.
  gs_cust_options-presel_sec_tab   = 'EDEXTASKIDOC'.
  gs_cust_options-sec_tab_weight   = 'DOCNUM'.
  gs_cust_options-workload_mode    = 'C'.
  gs_cust_options-parallel_mode    = '4'.

  gs_cust_options-report_variant   = 'SEL_PARALLEL'.
  gs_cust_options-selopt_to_fill   = 'SO_TASKI'.
  gs_cust_options-selopt_for_paral = 'SO_TASKI'.
  gs_cust_options-field_for_paral  = ''.
  gs_cust_options-show_hidden_sopt = ''.
  gs_cust_options-max_job_count    =                  10.
  gs_cust_options-max_workload     = '                          10000'.
  gs_cust_options-server_group     = ''.
  gs_cust_options-event            = ''.

  _cust_crit_append
   '/ADESSO/HMV_IDOC_STATUS                 ' 'DEXPROC'
   'EDEXTASK                      ' 'DEXPROC                       '.

INCLUDE WLC_REPORT_IN_PARALLELINI.
INCLUDE WLC_REPORT_IN_PARALLELF01.
INCLUDE WLC_REPORT_IN_PARALLELF02.
INCLUDE WLC_REPORT_IN_PARALLELF03.
INCLUDE WLC_REPORT_IN_PARALLELF04.
INCLUDE WLC_REPORT_IN_PARALLELF05.
INCLUDE WLC_REPORT_IN_PARALLELF06.
INCLUDE WLC_REPORT_IN_PARALLELATE.
INCLUDE WLC_REPORT_IN_PARALLELSOS.
