interface ZIF_AGC_MASTERDATA_CO
  public .


  constants AC_OWN_MDL_EXT_ID_ELE type DUNSNR value '9910204000006'. "#EC NOTEXT
  constants AC_OWN_MDL_EXT_ID_GAS type DUNSNR value '9800101100001'. "#EC NOTEXT
  constants AC_OWN_MSB_EXT_ID_ELE type DUNSNR value '9904686000007'. "#EC NOTEXT
  constants AC_OWN_MSB_EXT_ID_GAS type DUNSNR value '9800101000003'. "#EC NOTEXT
  constants AC_OWN_MDL_SERV_ID_ELE type SERVICE_PROV value 'SMD100001'. "#EC NOTEXT
  constants AC_OWN_MDL_SERV_ID_GAS type SERVICE_PROV value 'GMD100001'. "#EC NOTEXT
  constants AC_OWN_MSB_SERV_ID_ELE type SERVICE_PROV value 'SMB100001'. "#EC NOTEXT
  constants AC_OWN_MSB_SERV_ID_GAS type SERVICE_PROV value 'GMB100001'. "#EC NOTEXT
  constants AC_DUMMY_METERTYPE type /IDXGC/DE_DEV_CHAR_CODE value 'Z99'. "#EC NOTEXT
  constants GC_EXTERNALIDTYP_BDEW_1 type E_EDMIDEEXTNUMTYP value '1'. "#EC NOTEXT
  constants GC_EXTERNALIDTYP_GS1_2 type E_EDMIDEEXTNUMTYP value '2'. "#EC NOTEXT
  constants GC_EXTERNALIDTYP_DVGW_3 type E_EDMIDEEXTNUMTYP value '3'. "#EC NOTEXT
  constants GC_AGENT_TYPE_GLFR type SERCODE value 'GLFR'. "#EC NOTEXT
  constants GC_AGENT_TYPE_SLFR type SERCODE value 'SLFR'. "#EC NOTEXT
  constants AC_GAS_QUALITY_H_GAS type /IDXGC/DE_GAS_QUALITY value 'Y04'. "#EC NOTEXT
  constants AC_GAS_QUALITY_L_GAS type /IDXGC/DE_GAS_QUALITY value 'Y05'. "#EC NOTEXT
  constants AC_MKT_AR_37Y701125MH0000I type /IDXGC/DE_MARKET_AREA value '37Y701125MH0000I'. "#EC NOTEXT
  constants AC_MKT_AR_37Y701133MH0000P type /IDXGC/DE_MARKET_AREA value '37Y701133MH0000P'. "#EC NOTEXT
endinterface.
