*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 09.09.2015 at 13:50:58
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPM_GE................................*
FORM GET_DATA_/ADESSO/V_BPM_GE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPM_GEN WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPM_GE .
/ADESSO/V_BPM_GE-MANDT =
/ADESSO/BPM_GEN-MANDT .
/ADESSO/V_BPM_GE-BPAREA =
/ADESSO/BPM_GEN-BPAREA .
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_OBJ =
/ADESSO/BPM_GEN-AD_BPM_DP_CL_OBJ .
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_RUL =
/ADESSO/BPM_GEN-AD_BPM_DP_CL_RUL .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPM_GE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPM_GE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPM_GE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPM_GE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_GEN WHERE
  BPAREA = /ADESSO/V_BPM_GE-BPAREA .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPM_GEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_GEN WHERE
  BPAREA = /ADESSO/V_BPM_GE-BPAREA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPM_GEN.
    ENDIF.
/ADESSO/BPM_GEN-MANDT =
/ADESSO/V_BPM_GE-MANDT .
/ADESSO/BPM_GEN-BPAREA =
/ADESSO/V_BPM_GE-BPAREA .
/ADESSO/BPM_GEN-AD_BPM_DP_CL_OBJ =
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_OBJ .
/ADESSO/BPM_GEN-AD_BPM_DP_CL_RUL =
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_RUL .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPM_GEN .
    ELSE.
    INSERT /ADESSO/BPM_GEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPM_GE-UPD_FLAG,
STATUS_/ADESSO/V_BPM_GE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPM_GE.
  SELECT SINGLE * FROM /ADESSO/BPM_GEN WHERE
BPAREA = /ADESSO/V_BPM_GE-BPAREA .
/ADESSO/V_BPM_GE-MANDT =
/ADESSO/BPM_GEN-MANDT .
/ADESSO/V_BPM_GE-BPAREA =
/ADESSO/BPM_GEN-BPAREA .
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_OBJ =
/ADESSO/BPM_GEN-AD_BPM_DP_CL_OBJ .
/ADESSO/V_BPM_GE-AD_BPM_DP_CL_RUL =
/ADESSO/BPM_GEN-AD_BPM_DP_CL_RUL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPM_GE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPM_GE-BPAREA TO
/ADESSO/BPM_GEN-BPAREA .
MOVE /ADESSO/V_BPM_GE-MANDT TO
/ADESSO/BPM_GEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPM_GEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPM_GEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPM_GEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
