*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 10.09.2015 at 10:28:38
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPM_OB................................*
FORM GET_DATA_/ADESSO/V_BPM_OB.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPM_OBJ WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPM_OB .
/ADESSO/V_BPM_OB-MANDT =
/ADESSO/BPM_OBJ-MANDT .
/ADESSO/V_BPM_OB-AD_BPM_ID =
/ADESSO/BPM_OBJ-AD_BPM_ID .
/ADESSO/V_BPM_OB-OBJECT =
/ADESSO/BPM_OBJ-OBJECT .
/ADESSO/V_BPM_OB-BPAREA =
/ADESSO/BPM_OBJ-BPAREA .
/ADESSO/V_BPM_OB-REFOBJTYPE =
/ADESSO/BPM_OBJ-REFOBJTYPE .
/ADESSO/V_BPM_OB-REFSTRUCT =
/ADESSO/BPM_OBJ-REFSTRUCT .
/ADESSO/V_BPM_OB-REFFIELD =
/ADESSO/BPM_OBJ-REFFIELD .
/ADESSO/V_BPM_OB-DP_METHOD =
/ADESSO/BPM_OBJ-DP_METHOD .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPM_OB.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPM_OB .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPM_OB.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPM_OB-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_OBJ WHERE
  BPAREA = /ADESSO/V_BPM_OB-BPAREA AND
  AD_BPM_ID = /ADESSO/V_BPM_OB-AD_BPM_ID AND
  OBJECT = /ADESSO/V_BPM_OB-OBJECT .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPM_OBJ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_OBJ WHERE
  BPAREA = /ADESSO/V_BPM_OB-BPAREA AND
  AD_BPM_ID = /ADESSO/V_BPM_OB-AD_BPM_ID AND
  OBJECT = /ADESSO/V_BPM_OB-OBJECT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPM_OBJ.
    ENDIF.
/ADESSO/BPM_OBJ-MANDT =
/ADESSO/V_BPM_OB-MANDT .
/ADESSO/BPM_OBJ-AD_BPM_ID =
/ADESSO/V_BPM_OB-AD_BPM_ID .
/ADESSO/BPM_OBJ-OBJECT =
/ADESSO/V_BPM_OB-OBJECT .
/ADESSO/BPM_OBJ-BPAREA =
/ADESSO/V_BPM_OB-BPAREA .
/ADESSO/BPM_OBJ-REFOBJTYPE =
/ADESSO/V_BPM_OB-REFOBJTYPE .
/ADESSO/BPM_OBJ-REFSTRUCT =
/ADESSO/V_BPM_OB-REFSTRUCT .
/ADESSO/BPM_OBJ-REFFIELD =
/ADESSO/V_BPM_OB-REFFIELD .
/ADESSO/BPM_OBJ-DP_METHOD =
/ADESSO/V_BPM_OB-DP_METHOD .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPM_OBJ .
    ELSE.
    INSERT /ADESSO/BPM_OBJ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPM_OB-UPD_FLAG,
STATUS_/ADESSO/V_BPM_OB-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPM_OB.
  SELECT SINGLE * FROM /ADESSO/BPM_OBJ WHERE
BPAREA = /ADESSO/V_BPM_OB-BPAREA AND
AD_BPM_ID = /ADESSO/V_BPM_OB-AD_BPM_ID AND
OBJECT = /ADESSO/V_BPM_OB-OBJECT .
/ADESSO/V_BPM_OB-MANDT =
/ADESSO/BPM_OBJ-MANDT .
/ADESSO/V_BPM_OB-AD_BPM_ID =
/ADESSO/BPM_OBJ-AD_BPM_ID .
/ADESSO/V_BPM_OB-OBJECT =
/ADESSO/BPM_OBJ-OBJECT .
/ADESSO/V_BPM_OB-BPAREA =
/ADESSO/BPM_OBJ-BPAREA .
/ADESSO/V_BPM_OB-REFOBJTYPE =
/ADESSO/BPM_OBJ-REFOBJTYPE .
/ADESSO/V_BPM_OB-REFSTRUCT =
/ADESSO/BPM_OBJ-REFSTRUCT .
/ADESSO/V_BPM_OB-REFFIELD =
/ADESSO/BPM_OBJ-REFFIELD .
/ADESSO/V_BPM_OB-DP_METHOD =
/ADESSO/BPM_OBJ-DP_METHOD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPM_OB USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPM_OB-BPAREA TO
/ADESSO/BPM_OBJ-BPAREA .
MOVE /ADESSO/V_BPM_OB-AD_BPM_ID TO
/ADESSO/BPM_OBJ-AD_BPM_ID .
MOVE /ADESSO/V_BPM_OB-OBJECT TO
/ADESSO/BPM_OBJ-OBJECT .
MOVE /ADESSO/V_BPM_OB-MANDT TO
/ADESSO/BPM_OBJ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPM_OBJ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPM_OBJ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPM_OBJ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
