interface ZIF_AGC_DATEX_UTILMD_CO
  public .


  constants GC_AMID_11001 type /IDXGC/DE_AMID value '11001'. "#EC NOTEXT
  constants GC_AMID_11002 type /IDXGC/DE_AMID value '11002'. "#EC NOTEXT
  constants GC_AMID_11003 type /IDXGC/DE_AMID value '11003'. "#EC NOTEXT
  constants GC_AMID_11004 type /IDXGC/DE_AMID value '11004'. "#EC NOTEXT
  constants GC_AMID_11005 type /IDXGC/DE_AMID value '11005'. "#EC NOTEXT
  constants GC_AMID_11006 type /IDXGC/DE_AMID value '11006'. "#EC NOTEXT
  constants GC_AMID_11007 type /IDXGC/DE_AMID value '11007'. "#EC NOTEXT
  constants GC_AMID_11008 type /IDXGC/DE_AMID value '11008'. "#EC NOTEXT
  constants GC_AMID_11009 type /IDXGC/DE_AMID value '11009'. "#EC NOTEXT
  constants GC_AMID_11010 type /IDXGC/DE_AMID value '11010'. "#EC NOTEXT
  constants GC_AMID_11011 type /IDXGC/DE_AMID value '11011'. "#EC NOTEXT
  constants GC_AMID_11012 type /IDXGC/DE_AMID value '11012'. "#EC NOTEXT
  constants GC_AMID_11013 type /IDXGC/DE_AMID value '11013'. "#EC NOTEXT
  constants GC_AMID_11014 type /IDXGC/DE_AMID value '11014'. "#EC NOTEXT
  constants GC_AMID_11015 type /IDXGC/DE_AMID value '11015'. "#EC NOTEXT
  constants GC_AMID_11016 type /IDXGC/DE_AMID value '11016'. "#EC NOTEXT
  constants GC_AMID_11017 type /IDXGC/DE_AMID value '11017'. "#EC NOTEXT
  constants GC_AMID_11018 type /IDXGC/DE_AMID value '11018'. "#EC NOTEXT
  constants GC_AMID_11019 type /IDXGC/DE_AMID value '11019'. "#EC NOTEXT
  constants GC_AMID_11020 type /IDXGC/DE_AMID value '11020'. "#EC NOTEXT
  constants GC_AMID_11021 type /IDXGC/DE_AMID value '11021'. "#EC NOTEXT
  constants GC_AMID_11022 type /IDXGC/DE_AMID value '11022'. "#EC NOTEXT
  constants GC_AMID_11023 type /IDXGC/DE_AMID value '11023'. "#EC NOTEXT
  constants GC_AMID_11024 type /IDXGC/DE_AMID value '11024'. "#EC NOTEXT
  constants GC_AMID_11025 type /IDXGC/DE_AMID value '11025'. "#EC NOTEXT
  constants GC_AMID_11026 type /IDXGC/DE_AMID value '11026'. "#EC NOTEXT
  constants GC_AMID_11027 type /IDXGC/DE_AMID value '11027'. "#EC NOTEXT
  constants GC_AMID_11028 type /IDXGC/DE_AMID value '11028'. "#EC NOTEXT
  constants GC_AMID_11029 type /IDXGC/DE_AMID value '11029'. "#EC NOTEXT
  constants GC_AMID_11030 type /IDXGC/DE_AMID value '11030'. "#EC NOTEXT
  constants GC_AMID_11033 type /IDXGC/DE_AMID value '11033'. "#EC NOTEXT
  constants GC_AMID_11034 type /IDXGC/DE_AMID value '11034'. "#EC NOTEXT
  constants GC_AMID_11035 type /IDXGC/DE_AMID value '11035'. "#EC NOTEXT
  constants GC_AMID_11036 type /IDXGC/DE_AMID value '11036'. "#EC NOTEXT
  constants GC_AMID_11037 type /IDXGC/DE_AMID value '11037'. "#EC NOTEXT
  constants GC_AMID_11038 type /IDXGC/DE_AMID value '11038'. "#EC NOTEXT
  constants GC_AMID_11101 type /IDXGC/DE_AMID value '11101'. "#EC NOTEXT
  constants GC_AMID_11102 type /IDXGC/DE_AMID value '11102'. "#EC NOTEXT
  constants GC_AMID_11103 type /IDXGC/DE_AMID value '11103'. "#EC NOTEXT
  constants GC_AMID_11104 type /IDXGC/DE_AMID value '11104'. "#EC NOTEXT
  constants GC_AMID_11105 type /IDXGC/DE_AMID value '11105'. "#EC NOTEXT
  constants GC_BMID_ZMD01 type /IDXGC/DE_BMID value 'ZMD01'. "#EC NOTEXT
  constants GC_BMID_ZMD02 type /IDXGC/DE_BMID value 'ZMD02'. "#EC NOTEXT
  constants GC_BMID_ZMD03 type /IDXGC/DE_BMID value 'ZMD03'. "#EC NOTEXT
  constants GC_BMID_ZMD11 type /IDXGC/DE_BMID value 'ZMD11'. "#EC NOTEXT
  constants GC_BMID_ZMD12 type /IDXGC/DE_BMID value 'ZMD12'. "#EC NOTEXT
  constants GC_BMID_ZMD13 type /IDXGC/DE_BMID value 'ZMD13'. "#EC NOTEXT
  constants GC_BMID_ZMD21 type /IDXGC/DE_BMID value 'ZMD21'. "#EC NOTEXT
  constants GC_BMID_ZMD22 type /IDXGC/DE_BMID value 'ZMD22'. "#EC NOTEXT
  constants GC_BMID_ZMD23 type /IDXGC/DE_BMID value 'ZMD23'. "#EC NOTEXT
  constants GC_BMID_ZDC01 type /IDXGC/DE_BMID value 'ZDC01'. "#EC NOTEXT
  constants GC_BMID_ZDC02 type /IDXGC/DE_BMID value 'ZDC02'. "#EC NOTEXT
  constants GC_BMID_ZDC03 type /IDXGC/DE_BMID value 'ZDC03'. "#EC NOTEXT
  constants GC_DE_FM_UTILMD_1 type FUNCNAME value 'ZAGC_COMEV_UTILMD_IN_CL_1'. "#EC NOTEXT
  constants GC_EDIFACT_FRANCHISE_FEE type /IDXGC/DE_EDIFACT_STR value 'UTILMD_SG10_CCI+Z08/Z09+CAV_01'. "#EC NOTEXT
  constants GC_EDIFACT_SG9_QTY_265_Z08 type /IDXGC/DE_EDIFACT_STR value 'UTILMD_SG9_QTY+265/Z08'. "#EC NOTEXT
  constants GC_EDIFACT_SG9_QTY_31 type /IDXGC/DE_EDIFACT_STR value 'UTILMD_SG9_QTY+31'. "#EC NOTEXT
  constants GC_EDIFACT_SG9_QTY_Y02 type /IDXGC/DE_EDIFACT_STR value 'UTILMD_SG9_QTY+Y02'. "#EC NOTEXT
  constants GC_FABRIKKALENDER_DE_STAND type BP_CAL_ID value 'ZZ'. "#EC NOTEXT
  constants GC_NAD_NAME_FORMAT_Z01 type /IDXGC/DE_NAME_FORMAT_CODE value 'Z01'. "#EC NOTEXT
  constants GC_MSG_CATEGORY_Z22 type /IDXGC/DE_DOCNAME_CODE value 'Z22'. "#EC NOTEXT
  constants GC_PROC_ID_9012 type /IDXGC/DE_PROC_ID value '9012'. "#EC NOTEXT
  constants GC_PROC_ID_9013 type /IDXGC/DE_PROC_ID value '9013'. "#EC NOTEXT
  constants GC_PROC_ID_9032 type /IDXGC/DE_PROC_ID value '9032'. "#EC NOTEXT
  constants GC_PROC_ID_9041 type /IDXGC/DE_PROC_ID value '9041'. "#EC NOTEXT
  constants GC_PROC_ID_9112 type /IDXGC/DE_PROC_ID value '9112'. "#EC NOTEXT
  constants GC_PROC_ID_9132 type /IDXGC/DE_PROC_ID value '9132'. "#EC NOTEXT
  constants GC_PROC_ID_9180 type /IDXGC/DE_PROC_ID value '9180'. "#EC NOTEXT
  constants GC_PROC_ID_9181 type /IDXGC/DE_PROC_ID value '9181'. "#EC NOTEXT
  constants GC_PROC_ID_9184 type /IDXGC/DE_PROC_ID value '9184'. "#EC NOTEXT
  constants GC_PROC_ID_9910 type /IDXGC/DE_PROC_ID value '9910'. "#EC NOTEXT
  constants GC_PROC_ID_9911 type /IDXGC/DE_PROC_ID value '9911'. "#EC NOTEXT
  constants GC_PROC_ID_9912 type /IDXGC/DE_PROC_ID value '9912'. "#EC NOTEXT
  constants GC_PROC_ID_9913 type /IDXGC/DE_PROC_ID value '9913'. "#EC NOTEXT
  constants GC_SPARTE_GAS type SPARTYP value '02'. "#EC NOTEXT
  constants GC_SPARTE_STROM type SPARTYP value '01'. "#EC NOTEXT
  constants GC_PROC_TYPE_97 type /IDXGC/DE_PROC_TYPE value '97'. "#EC NOTEXT
  constants GC_RESPSTATUS_ZD4 type /IDXGC/DE_RESPSTATUS value 'ZD4'. "#EC NOTEXT
  constants GC_TRANS_REASON_CODE_Z01 type /IDXGC/DE_MSGTRANSREASON value 'Z01'. "#EC NOTEXT
  constants GC_TRANS_REASON_CODE_Z12 type /IDXGC/DE_MSGTRANSREASON value 'Z12'. "#EC NOTEXT
  constants GC_TRANS_REASON_CODE_Z27 type /IDXGC/DE_MSGTRANSREASON value 'Z27'. "#EC NOTEXT
  constants GC_TRANS_REASON_CODE_Z28 type /IDXGC/DE_MSGTRANSREASON value 'Z28'. "#EC NOTEXT
*  constants GC_VERSART_GRV type ZLW_VERSART value 'GRV'. "#EC NOTEXT
*  constants GC_VERSART_ERS type ZLW_VERSART value 'ERS'. "#EC NOTEXT
*  constants GC_VERSART_EDD type ZLW_VERSART value 'EDD'. "#EC NOTEXT
  constants GC_PROC_VIEW_02 type /IDXGC/DE_PROC_VIEW value '02'. "#EC NOTEXT
  constants GC_SPARTE_WASSER type SPARTE value '03'. "#EC NOTEXT
  constants GC_SPARTE_HEIZENERGIE type SPARTE value '08'. "#EC NOTEXT
  constants GC_SPARTE_WARMWASSER type SPARTE value '09'. "#EC NOTEXT
  constants GC_SPARTE_SCHMUTZWASSER type SPARTE value '04'. "#EC NOTEXT
  constants GC_TEXT_SUBJ_QUAL_AAI type /IDXGC/DE_TEXT_SUBJ_QUAL value 'AAI'. "#EC NOTEXT
  constants GC_BMID_ZE101 type /IDXGC/DE_BMID value 'ZE101'. "#EC NOTEXT
  constants GC_BMID_ZE102 type /IDXGC/DE_BMID value 'ZE102'. "#EC NOTEXT
  constants GC_BMID_ZE103 type /IDXGC/DE_BMID value 'ZE103'. "#EC NOTEXT
endinterface.
