CLASS zha_cl_smo_data DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
    SHARED MEMORY ENABLED .

  PUBLIC SECTION.
    DATA num TYPE integer.
    DATA str TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zha_cl_smo_data IMPLEMENTATION.
ENDCLASS.
