*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 03.01.2018 at 10:29:00
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_MOSB_PRICAT_V................................*
FORM GET_DATA_ZV_MOSB_PRICAT_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMOSB_PRICAT_VER WHERE
(VIM_WHERETAB) .
    CLEAR ZV_MOSB_PRICAT_V .
ZV_MOSB_PRICAT_V-MANDT =
ZMOSB_PRICAT_VER-MANDT .
ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID =
ZMOSB_PRICAT_VER-PRICE_CATALOGUE_ID .
ZV_MOSB_PRICAT_V-PRICAT_VERSION =
ZMOSB_PRICAT_VER-PRICAT_VERSION .
ZV_MOSB_PRICAT_V-VAL_START_DATE =
ZMOSB_PRICAT_VER-VAL_START_DATE .
ZV_MOSB_PRICAT_V-VAL_END_DATE =
ZMOSB_PRICAT_VER-VAL_END_DATE .
<VIM_TOTAL_STRUC> = ZV_MOSB_PRICAT_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_MOSB_PRICAT_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_MOSB_PRICAT_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_MOSB_PRICAT_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMOSB_PRICAT_VER WHERE
  PRICE_CATALOGUE_ID = ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID AND
  PRICAT_VERSION = ZV_MOSB_PRICAT_V-PRICAT_VERSION .
    IF SY-SUBRC = 0.
    DELETE ZMOSB_PRICAT_VER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMOSB_PRICAT_VER WHERE
  PRICE_CATALOGUE_ID = ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID AND
  PRICAT_VERSION = ZV_MOSB_PRICAT_V-PRICAT_VERSION .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMOSB_PRICAT_VER.
    ENDIF.
ZMOSB_PRICAT_VER-MANDT =
ZV_MOSB_PRICAT_V-MANDT .
ZMOSB_PRICAT_VER-PRICE_CATALOGUE_ID =
ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID .
ZMOSB_PRICAT_VER-PRICAT_VERSION =
ZV_MOSB_PRICAT_V-PRICAT_VERSION .
ZMOSB_PRICAT_VER-VAL_START_DATE =
ZV_MOSB_PRICAT_V-VAL_START_DATE .
ZMOSB_PRICAT_VER-VAL_END_DATE =
ZV_MOSB_PRICAT_V-VAL_END_DATE .
    IF SY-SUBRC = 0.
    UPDATE ZMOSB_PRICAT_VER .
    ELSE.
    INSERT ZMOSB_PRICAT_VER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_MOSB_PRICAT_V-UPD_FLAG,
STATUS_ZV_MOSB_PRICAT_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZV_MOSB_PRICAT_V.
  SELECT SINGLE * FROM ZMOSB_PRICAT_VER WHERE
PRICE_CATALOGUE_ID = ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID AND
PRICAT_VERSION = ZV_MOSB_PRICAT_V-PRICAT_VERSION .
ZV_MOSB_PRICAT_V-MANDT =
ZMOSB_PRICAT_VER-MANDT .
ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID =
ZMOSB_PRICAT_VER-PRICE_CATALOGUE_ID .
ZV_MOSB_PRICAT_V-PRICAT_VERSION =
ZMOSB_PRICAT_VER-PRICAT_VERSION .
ZV_MOSB_PRICAT_V-VAL_START_DATE =
ZMOSB_PRICAT_VER-VAL_START_DATE .
ZV_MOSB_PRICAT_V-VAL_END_DATE =
ZMOSB_PRICAT_VER-VAL_END_DATE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_MOSB_PRICAT_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_MOSB_PRICAT_V-PRICE_CATALOGUE_ID TO
ZMOSB_PRICAT_VER-PRICE_CATALOGUE_ID .
MOVE ZV_MOSB_PRICAT_V-PRICAT_VERSION TO
ZMOSB_PRICAT_VER-PRICAT_VERSION .
MOVE ZV_MOSB_PRICAT_V-MANDT TO
ZMOSB_PRICAT_VER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMOSB_PRICAT_VER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMOSB_PRICAT_VER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMOSB_PRICAT_VER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
