*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 13.11.2019 at 19:49:36
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADZ/V_BDR_DEVCO................................*
FORM GET_DATA_/ADZ/V_BDR_DEVCO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/BDR_DEVCONF WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_BDR_DEVCO .
/ADZ/V_BDR_DEVCO-MANDT =
/ADZ/BDR_DEVCONF-MANDT .
/ADZ/V_BDR_DEVCO-SETTL_PROC =
/ADZ/BDR_DEVCONF-SETTL_PROC .
/ADZ/V_BDR_DEVCO-DEVICE_CONF =
/ADZ/BDR_DEVCONF-DEVICE_CONF .
/ADZ/V_BDR_DEVCO-EUISTRUTYP =
/ADZ/BDR_DEVCONF-EUISTRUTYP .
/ADZ/V_BDR_DEVCO-VALIDSTART_DATE =
/ADZ/BDR_DEVCONF-VALIDSTART_DATE .
/ADZ/V_BDR_DEVCO-KENNZIFF =
/ADZ/BDR_DEVCONF-KENNZIFF .
/ADZ/V_BDR_DEVCO-TARIF_ALLOC =
/ADZ/BDR_DEVCONF-TARIF_ALLOC .
/ADZ/V_BDR_DEVCO-CONS_TYPE =
/ADZ/BDR_DEVCONF-CONS_TYPE .
/ADZ/V_BDR_DEVCO-APPL_INTERRUPT =
/ADZ/BDR_DEVCONF-APPL_INTERRUPT .
/ADZ/V_BDR_DEVCO-HEAT_CONSUMPT =
/ADZ/BDR_DEVCONF-HEAT_CONSUMPT .
/ADZ/V_BDR_DEVCO-ZA7_Z84 =
/ADZ/BDR_DEVCONF-ZA7_Z84 .
/ADZ/V_BDR_DEVCO-ZA7_Z85 =
/ADZ/BDR_DEVCONF-ZA7_Z85 .
/ADZ/V_BDR_DEVCO-ZA7_Z86 =
/ADZ/BDR_DEVCONF-ZA7_Z86 .
/ADZ/V_BDR_DEVCO-ZA7_Z47 =
/ADZ/BDR_DEVCONF-ZA7_Z47 .
/ADZ/V_BDR_DEVCO-ZA8_Z84 =
/ADZ/BDR_DEVCONF-ZA8_Z84 .
/ADZ/V_BDR_DEVCO-ZA8_Z85 =
/ADZ/BDR_DEVCONF-ZA8_Z85 .
/ADZ/V_BDR_DEVCO-ZA8_Z86 =
/ADZ/BDR_DEVCONF-ZA8_Z86 .
/ADZ/V_BDR_DEVCO-ZA8_Z92 =
/ADZ/BDR_DEVCONF-ZA8_Z92 .
/ADZ/V_BDR_DEVCO-ZA8_Z47 =
/ADZ/BDR_DEVCONF-ZA8_Z47 .
/ADZ/V_BDR_DEVCO-ZA9_Z85 =
/ADZ/BDR_DEVCONF-ZA9_Z85 .
<VIM_TOTAL_STRUC> = /ADZ/V_BDR_DEVCO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_BDR_DEVCO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_BDR_DEVCO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_BDR_DEVCO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/BDR_DEVCONF WHERE
  SETTL_PROC = /ADZ/V_BDR_DEVCO-SETTL_PROC AND
  DEVICE_CONF = /ADZ/V_BDR_DEVCO-DEVICE_CONF AND
  EUISTRUTYP = /ADZ/V_BDR_DEVCO-EUISTRUTYP AND
  VALIDSTART_DATE = /ADZ/V_BDR_DEVCO-VALIDSTART_DATE AND
  KENNZIFF = /ADZ/V_BDR_DEVCO-KENNZIFF .
    IF SY-SUBRC = 0.
    DELETE /ADZ/BDR_DEVCONF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/BDR_DEVCONF WHERE
  SETTL_PROC = /ADZ/V_BDR_DEVCO-SETTL_PROC AND
  DEVICE_CONF = /ADZ/V_BDR_DEVCO-DEVICE_CONF AND
  EUISTRUTYP = /ADZ/V_BDR_DEVCO-EUISTRUTYP AND
  VALIDSTART_DATE = /ADZ/V_BDR_DEVCO-VALIDSTART_DATE AND
  KENNZIFF = /ADZ/V_BDR_DEVCO-KENNZIFF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/BDR_DEVCONF.
    ENDIF.
/ADZ/BDR_DEVCONF-MANDT =
/ADZ/V_BDR_DEVCO-MANDT .
/ADZ/BDR_DEVCONF-SETTL_PROC =
/ADZ/V_BDR_DEVCO-SETTL_PROC .
/ADZ/BDR_DEVCONF-DEVICE_CONF =
/ADZ/V_BDR_DEVCO-DEVICE_CONF .
/ADZ/BDR_DEVCONF-EUISTRUTYP =
/ADZ/V_BDR_DEVCO-EUISTRUTYP .
/ADZ/BDR_DEVCONF-VALIDSTART_DATE =
/ADZ/V_BDR_DEVCO-VALIDSTART_DATE .
/ADZ/BDR_DEVCONF-KENNZIFF =
/ADZ/V_BDR_DEVCO-KENNZIFF .
/ADZ/BDR_DEVCONF-TARIF_ALLOC =
/ADZ/V_BDR_DEVCO-TARIF_ALLOC .
/ADZ/BDR_DEVCONF-CONS_TYPE =
/ADZ/V_BDR_DEVCO-CONS_TYPE .
/ADZ/BDR_DEVCONF-APPL_INTERRUPT =
/ADZ/V_BDR_DEVCO-APPL_INTERRUPT .
/ADZ/BDR_DEVCONF-HEAT_CONSUMPT =
/ADZ/V_BDR_DEVCO-HEAT_CONSUMPT .
/ADZ/BDR_DEVCONF-ZA7_Z84 =
/ADZ/V_BDR_DEVCO-ZA7_Z84 .
/ADZ/BDR_DEVCONF-ZA7_Z85 =
/ADZ/V_BDR_DEVCO-ZA7_Z85 .
/ADZ/BDR_DEVCONF-ZA7_Z86 =
/ADZ/V_BDR_DEVCO-ZA7_Z86 .
/ADZ/BDR_DEVCONF-ZA7_Z47 =
/ADZ/V_BDR_DEVCO-ZA7_Z47 .
/ADZ/BDR_DEVCONF-ZA8_Z84 =
/ADZ/V_BDR_DEVCO-ZA8_Z84 .
/ADZ/BDR_DEVCONF-ZA8_Z85 =
/ADZ/V_BDR_DEVCO-ZA8_Z85 .
/ADZ/BDR_DEVCONF-ZA8_Z86 =
/ADZ/V_BDR_DEVCO-ZA8_Z86 .
/ADZ/BDR_DEVCONF-ZA8_Z92 =
/ADZ/V_BDR_DEVCO-ZA8_Z92 .
/ADZ/BDR_DEVCONF-ZA8_Z47 =
/ADZ/V_BDR_DEVCO-ZA8_Z47 .
/ADZ/BDR_DEVCONF-ZA9_Z85 =
/ADZ/V_BDR_DEVCO-ZA9_Z85 .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/BDR_DEVCONF ##WARN_OK.
    ELSE.
    INSERT /ADZ/BDR_DEVCONF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_BDR_DEVCO-UPD_FLAG,
STATUS_/ADZ/V_BDR_DEVCO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_BDR_DEVCO.
  SELECT SINGLE * FROM /ADZ/BDR_DEVCONF WHERE
SETTL_PROC = /ADZ/V_BDR_DEVCO-SETTL_PROC AND
DEVICE_CONF = /ADZ/V_BDR_DEVCO-DEVICE_CONF AND
EUISTRUTYP = /ADZ/V_BDR_DEVCO-EUISTRUTYP AND
VALIDSTART_DATE = /ADZ/V_BDR_DEVCO-VALIDSTART_DATE AND
KENNZIFF = /ADZ/V_BDR_DEVCO-KENNZIFF .
/ADZ/V_BDR_DEVCO-MANDT =
/ADZ/BDR_DEVCONF-MANDT .
/ADZ/V_BDR_DEVCO-SETTL_PROC =
/ADZ/BDR_DEVCONF-SETTL_PROC .
/ADZ/V_BDR_DEVCO-DEVICE_CONF =
/ADZ/BDR_DEVCONF-DEVICE_CONF .
/ADZ/V_BDR_DEVCO-EUISTRUTYP =
/ADZ/BDR_DEVCONF-EUISTRUTYP .
/ADZ/V_BDR_DEVCO-VALIDSTART_DATE =
/ADZ/BDR_DEVCONF-VALIDSTART_DATE .
/ADZ/V_BDR_DEVCO-KENNZIFF =
/ADZ/BDR_DEVCONF-KENNZIFF .
/ADZ/V_BDR_DEVCO-TARIF_ALLOC =
/ADZ/BDR_DEVCONF-TARIF_ALLOC .
/ADZ/V_BDR_DEVCO-CONS_TYPE =
/ADZ/BDR_DEVCONF-CONS_TYPE .
/ADZ/V_BDR_DEVCO-APPL_INTERRUPT =
/ADZ/BDR_DEVCONF-APPL_INTERRUPT .
/ADZ/V_BDR_DEVCO-HEAT_CONSUMPT =
/ADZ/BDR_DEVCONF-HEAT_CONSUMPT .
/ADZ/V_BDR_DEVCO-ZA7_Z84 =
/ADZ/BDR_DEVCONF-ZA7_Z84 .
/ADZ/V_BDR_DEVCO-ZA7_Z85 =
/ADZ/BDR_DEVCONF-ZA7_Z85 .
/ADZ/V_BDR_DEVCO-ZA7_Z86 =
/ADZ/BDR_DEVCONF-ZA7_Z86 .
/ADZ/V_BDR_DEVCO-ZA7_Z47 =
/ADZ/BDR_DEVCONF-ZA7_Z47 .
/ADZ/V_BDR_DEVCO-ZA8_Z84 =
/ADZ/BDR_DEVCONF-ZA8_Z84 .
/ADZ/V_BDR_DEVCO-ZA8_Z85 =
/ADZ/BDR_DEVCONF-ZA8_Z85 .
/ADZ/V_BDR_DEVCO-ZA8_Z86 =
/ADZ/BDR_DEVCONF-ZA8_Z86 .
/ADZ/V_BDR_DEVCO-ZA8_Z92 =
/ADZ/BDR_DEVCONF-ZA8_Z92 .
/ADZ/V_BDR_DEVCO-ZA8_Z47 =
/ADZ/BDR_DEVCONF-ZA8_Z47 .
/ADZ/V_BDR_DEVCO-ZA9_Z85 =
/ADZ/BDR_DEVCONF-ZA9_Z85 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_BDR_DEVCO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_BDR_DEVCO-SETTL_PROC TO
/ADZ/BDR_DEVCONF-SETTL_PROC .
MOVE /ADZ/V_BDR_DEVCO-DEVICE_CONF TO
/ADZ/BDR_DEVCONF-DEVICE_CONF .
MOVE /ADZ/V_BDR_DEVCO-EUISTRUTYP TO
/ADZ/BDR_DEVCONF-EUISTRUTYP .
MOVE /ADZ/V_BDR_DEVCO-VALIDSTART_DATE TO
/ADZ/BDR_DEVCONF-VALIDSTART_DATE .
MOVE /ADZ/V_BDR_DEVCO-KENNZIFF TO
/ADZ/BDR_DEVCONF-KENNZIFF .
MOVE /ADZ/V_BDR_DEVCO-MANDT TO
/ADZ/BDR_DEVCONF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/BDR_DEVCONF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/BDR_DEVCONF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/BDR_DEVCONF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
