*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 02.12.2019 at 10:53:55
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_IN...................................*
FORM GET_DATA_/ADZ/V_MDC_IN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_IN WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_IN .
/ADZ/V_MDC_IN-MANDT =
/ADZ/MDC_IN-MANDT .
/ADZ/V_MDC_IN-EDIFACT_STRUCTUR =
/ADZ/MDC_IN-EDIFACT_STRUCTUR .
/ADZ/V_MDC_IN-VALID_FROM =
/ADZ/MDC_IN-VALID_FROM .
/ADZ/V_MDC_IN-SETTING_SYNC =
/ADZ/MDC_IN-SETTING_SYNC .
/ADZ/V_MDC_IN-BADI_NAME =
/ADZ/MDC_IN-BADI_NAME .
/ADZ/V_MDC_IN-USER_COMMENT =
/ADZ/MDC_IN-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_IN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_IN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_IN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_IN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN WHERE
  EDIFACT_STRUCTUR = /ADZ/V_MDC_IN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADZ/V_MDC_IN-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_IN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN WHERE
  EDIFACT_STRUCTUR = /ADZ/V_MDC_IN-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADZ/V_MDC_IN-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_IN.
    ENDIF.
/ADZ/MDC_IN-MANDT =
/ADZ/V_MDC_IN-MANDT .
/ADZ/MDC_IN-EDIFACT_STRUCTUR =
/ADZ/V_MDC_IN-EDIFACT_STRUCTUR .
/ADZ/MDC_IN-VALID_FROM =
/ADZ/V_MDC_IN-VALID_FROM .
/ADZ/MDC_IN-SETTING_SYNC =
/ADZ/V_MDC_IN-SETTING_SYNC .
/ADZ/MDC_IN-BADI_NAME =
/ADZ/V_MDC_IN-BADI_NAME .
/ADZ/MDC_IN-USER_COMMENT =
/ADZ/V_MDC_IN-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_IN ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_IN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_IN-UPD_FLAG,
STATUS_/ADZ/V_MDC_IN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_IN.
  SELECT SINGLE * FROM /ADZ/MDC_IN WHERE
EDIFACT_STRUCTUR = /ADZ/V_MDC_IN-EDIFACT_STRUCTUR AND
VALID_FROM = /ADZ/V_MDC_IN-VALID_FROM .
/ADZ/V_MDC_IN-MANDT =
/ADZ/MDC_IN-MANDT .
/ADZ/V_MDC_IN-EDIFACT_STRUCTUR =
/ADZ/MDC_IN-EDIFACT_STRUCTUR .
/ADZ/V_MDC_IN-VALID_FROM =
/ADZ/MDC_IN-VALID_FROM .
/ADZ/V_MDC_IN-SETTING_SYNC =
/ADZ/MDC_IN-SETTING_SYNC .
/ADZ/V_MDC_IN-BADI_NAME =
/ADZ/MDC_IN-BADI_NAME .
/ADZ/V_MDC_IN-USER_COMMENT =
/ADZ/MDC_IN-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_IN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_IN-EDIFACT_STRUCTUR TO
/ADZ/MDC_IN-EDIFACT_STRUCTUR .
MOVE /ADZ/V_MDC_IN-VALID_FROM TO
/ADZ/MDC_IN-VALID_FROM .
MOVE /ADZ/V_MDC_IN-MANDT TO
/ADZ/MDC_IN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_IN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_IN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_IN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_IN_MP................................*
FORM GET_DATA_/ADZ/V_MDC_IN_MP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_IN_MPG WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_IN_MP .
/ADZ/V_MDC_IN_MP-MANDT =
/ADZ/MDC_IN_MPG-MANDT .
/ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR =
/ADZ/MDC_IN_MPG-EDIFACT_STRUCTUR .
/ADZ/V_MDC_IN_MP-VALID_FROM =
/ADZ/MDC_IN_MPG-VALID_FROM .
/ADZ/V_MDC_IN_MP-MP_GROUP_ID =
/ADZ/MDC_IN_MPG-MP_GROUP_ID .
/ADZ/V_MDC_IN_MP-SETTING_SYNC =
/ADZ/MDC_IN_MPG-SETTING_SYNC .
/ADZ/V_MDC_IN_MP-BADI_NAME =
/ADZ/MDC_IN_MPG-BADI_NAME .
/ADZ/V_MDC_IN_MP-USER_COMMENT =
/ADZ/MDC_IN_MPG-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_IN_MP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_IN_MP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_IN_MP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_IN_MP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_MPG WHERE
  EDIFACT_STRUCTUR = /ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADZ/V_MDC_IN_MP-VALID_FROM AND
  MP_GROUP_ID = /ADZ/V_MDC_IN_MP-MP_GROUP_ID .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_IN_MPG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_MPG WHERE
  EDIFACT_STRUCTUR = /ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR AND
  VALID_FROM = /ADZ/V_MDC_IN_MP-VALID_FROM AND
  MP_GROUP_ID = /ADZ/V_MDC_IN_MP-MP_GROUP_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_IN_MPG.
    ENDIF.
/ADZ/MDC_IN_MPG-MANDT =
/ADZ/V_MDC_IN_MP-MANDT .
/ADZ/MDC_IN_MPG-EDIFACT_STRUCTUR =
/ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR .
/ADZ/MDC_IN_MPG-VALID_FROM =
/ADZ/V_MDC_IN_MP-VALID_FROM .
/ADZ/MDC_IN_MPG-MP_GROUP_ID =
/ADZ/V_MDC_IN_MP-MP_GROUP_ID .
/ADZ/MDC_IN_MPG-SETTING_SYNC =
/ADZ/V_MDC_IN_MP-SETTING_SYNC .
/ADZ/MDC_IN_MPG-BADI_NAME =
/ADZ/V_MDC_IN_MP-BADI_NAME .
/ADZ/MDC_IN_MPG-USER_COMMENT =
/ADZ/V_MDC_IN_MP-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_IN_MPG ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_IN_MPG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_IN_MP-UPD_FLAG,
STATUS_/ADZ/V_MDC_IN_MP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_IN_MP.
  SELECT SINGLE * FROM /ADZ/MDC_IN_MPG WHERE
EDIFACT_STRUCTUR = /ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR AND
VALID_FROM = /ADZ/V_MDC_IN_MP-VALID_FROM AND
MP_GROUP_ID = /ADZ/V_MDC_IN_MP-MP_GROUP_ID .
/ADZ/V_MDC_IN_MP-MANDT =
/ADZ/MDC_IN_MPG-MANDT .
/ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR =
/ADZ/MDC_IN_MPG-EDIFACT_STRUCTUR .
/ADZ/V_MDC_IN_MP-VALID_FROM =
/ADZ/MDC_IN_MPG-VALID_FROM .
/ADZ/V_MDC_IN_MP-MP_GROUP_ID =
/ADZ/MDC_IN_MPG-MP_GROUP_ID .
/ADZ/V_MDC_IN_MP-SETTING_SYNC =
/ADZ/MDC_IN_MPG-SETTING_SYNC .
/ADZ/V_MDC_IN_MP-BADI_NAME =
/ADZ/MDC_IN_MPG-BADI_NAME .
/ADZ/V_MDC_IN_MP-USER_COMMENT =
/ADZ/MDC_IN_MPG-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_IN_MP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_IN_MP-EDIFACT_STRUCTUR TO
/ADZ/MDC_IN_MPG-EDIFACT_STRUCTUR .
MOVE /ADZ/V_MDC_IN_MP-VALID_FROM TO
/ADZ/MDC_IN_MPG-VALID_FROM .
MOVE /ADZ/V_MDC_IN_MP-MP_GROUP_ID TO
/ADZ/MDC_IN_MPG-MP_GROUP_ID .
MOVE /ADZ/V_MDC_IN_MP-MANDT TO
/ADZ/MDC_IN_MPG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_IN_MPG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_IN_MPG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_IN_MPG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_IN_ST................................*
FORM GET_DATA_/ADZ/V_MDC_IN_ST.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_IN_SYOT WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_IN_ST .
/ADZ/V_MDC_IN_ST-MANDT =
/ADZ/MDC_IN_SYOT-MANDT .
/ADZ/V_MDC_IN_ST-SETTING_SYNC =
/ADZ/MDC_IN_SYOT-SETTING_SYNC .
/ADZ/V_MDC_IN_ST-SPRAS =
/ADZ/MDC_IN_SYOT-SPRAS .
/ADZ/V_MDC_IN_ST-DESCRIPTION =
/ADZ/MDC_IN_SYOT-DESCRIPTION .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_IN_ST.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_IN_ST .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_IN_ST.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_IN_ST-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_SYOT WHERE
  SETTING_SYNC = /ADZ/V_MDC_IN_ST-SETTING_SYNC AND
  SPRAS = /ADZ/V_MDC_IN_ST-SPRAS .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_IN_SYOT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_SYOT WHERE
  SETTING_SYNC = /ADZ/V_MDC_IN_ST-SETTING_SYNC AND
  SPRAS = /ADZ/V_MDC_IN_ST-SPRAS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_IN_SYOT.
    ENDIF.
/ADZ/MDC_IN_SYOT-MANDT =
/ADZ/V_MDC_IN_ST-MANDT .
/ADZ/MDC_IN_SYOT-SETTING_SYNC =
/ADZ/V_MDC_IN_ST-SETTING_SYNC .
/ADZ/MDC_IN_SYOT-SPRAS =
/ADZ/V_MDC_IN_ST-SPRAS .
/ADZ/MDC_IN_SYOT-DESCRIPTION =
/ADZ/V_MDC_IN_ST-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_IN_SYOT ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_IN_SYOT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_IN_ST-UPD_FLAG,
STATUS_/ADZ/V_MDC_IN_ST-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_IN_ST.
  SELECT SINGLE * FROM /ADZ/MDC_IN_SYOT WHERE
SETTING_SYNC = /ADZ/V_MDC_IN_ST-SETTING_SYNC AND
SPRAS = /ADZ/V_MDC_IN_ST-SPRAS .
/ADZ/V_MDC_IN_ST-MANDT =
/ADZ/MDC_IN_SYOT-MANDT .
/ADZ/V_MDC_IN_ST-SETTING_SYNC =
/ADZ/MDC_IN_SYOT-SETTING_SYNC .
/ADZ/V_MDC_IN_ST-SPRAS =
/ADZ/MDC_IN_SYOT-SPRAS .
/ADZ/V_MDC_IN_ST-DESCRIPTION =
/ADZ/MDC_IN_SYOT-DESCRIPTION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_IN_ST USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_IN_ST-SETTING_SYNC TO
/ADZ/MDC_IN_SYOT-SETTING_SYNC .
MOVE /ADZ/V_MDC_IN_ST-SPRAS TO
/ADZ/MDC_IN_SYOT-SPRAS .
MOVE /ADZ/V_MDC_IN_ST-MANDT TO
/ADZ/MDC_IN_SYOT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_IN_SYOT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_IN_SYOT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_IN_SYOT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_IN_SY................................*
FORM GET_DATA_/ADZ/V_MDC_IN_SY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_IN_SYO WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_IN_SY .
/ADZ/V_MDC_IN_SY-MANDT =
/ADZ/MDC_IN_SYO-MANDT .
/ADZ/V_MDC_IN_SY-SETTING_SYNC =
/ADZ/MDC_IN_SYO-SETTING_SYNC .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_IN_SY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_IN_SY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_IN_SY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_IN_SY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_SYO WHERE
  SETTING_SYNC = /ADZ/V_MDC_IN_SY-SETTING_SYNC .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_IN_SYO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_IN_SYO WHERE
  SETTING_SYNC = /ADZ/V_MDC_IN_SY-SETTING_SYNC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_IN_SYO.
    ENDIF.
/ADZ/MDC_IN_SYO-MANDT =
/ADZ/V_MDC_IN_SY-MANDT .
/ADZ/MDC_IN_SYO-SETTING_SYNC =
/ADZ/V_MDC_IN_SY-SETTING_SYNC .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_IN_SYO ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_IN_SYO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_IN_SY-UPD_FLAG,
STATUS_/ADZ/V_MDC_IN_SY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_IN_SY.
  SELECT SINGLE * FROM /ADZ/MDC_IN_SYO WHERE
SETTING_SYNC = /ADZ/V_MDC_IN_SY-SETTING_SYNC .
/ADZ/V_MDC_IN_SY-MANDT =
/ADZ/MDC_IN_SYO-MANDT .
/ADZ/V_MDC_IN_SY-SETTING_SYNC =
/ADZ/MDC_IN_SYO-SETTING_SYNC .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_IN_SY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_IN_SY-SETTING_SYNC TO
/ADZ/MDC_IN_SYO-SETTING_SYNC .
MOVE /ADZ/V_MDC_IN_SY-MANDT TO
/ADZ/MDC_IN_SYO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_IN_SYO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_IN_SYO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_IN_SYO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_MPG..................................*
FORM GET_DATA_/ADZ/V_MDC_MPG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_MPG WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_MPG .
/ADZ/V_MDC_MPG-MANDT =
/ADZ/MDC_MPG-MANDT .
/ADZ/V_MDC_MPG-MP_GROUP_ID =
/ADZ/MDC_MPG-MP_GROUP_ID .
/ADZ/V_MDC_MPG-MP_GROUP_TYPE =
/ADZ/MDC_MPG-MP_GROUP_TYPE .
/ADZ/V_MDC_MPG-USER_COMMENT =
/ADZ/MDC_MPG-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_MPG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_MPG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_MPG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_MPG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_MPG WHERE
  MP_GROUP_ID = /ADZ/V_MDC_MPG-MP_GROUP_ID .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_MPG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_MPG WHERE
  MP_GROUP_ID = /ADZ/V_MDC_MPG-MP_GROUP_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_MPG.
    ENDIF.
/ADZ/MDC_MPG-MANDT =
/ADZ/V_MDC_MPG-MANDT .
/ADZ/MDC_MPG-MP_GROUP_ID =
/ADZ/V_MDC_MPG-MP_GROUP_ID .
/ADZ/MDC_MPG-MP_GROUP_TYPE =
/ADZ/V_MDC_MPG-MP_GROUP_TYPE .
/ADZ/MDC_MPG-USER_COMMENT =
/ADZ/V_MDC_MPG-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_MPG ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_MPG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_MPG-UPD_FLAG,
STATUS_/ADZ/V_MDC_MPG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_MPG.
  SELECT SINGLE * FROM /ADZ/MDC_MPG WHERE
MP_GROUP_ID = /ADZ/V_MDC_MPG-MP_GROUP_ID .
/ADZ/V_MDC_MPG-MANDT =
/ADZ/MDC_MPG-MANDT .
/ADZ/V_MDC_MPG-MP_GROUP_ID =
/ADZ/MDC_MPG-MP_GROUP_ID .
/ADZ/V_MDC_MPG-MP_GROUP_TYPE =
/ADZ/MDC_MPG-MP_GROUP_TYPE .
/ADZ/V_MDC_MPG-USER_COMMENT =
/ADZ/MDC_MPG-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_MPG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_MPG-MP_GROUP_ID TO
/ADZ/MDC_MPG-MP_GROUP_ID .
MOVE /ADZ/V_MDC_MPG-MANDT TO
/ADZ/MDC_MPG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_MPG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_MPG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_MPG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /ADZ/V_MDC_MPG_S................................*
FORM GET_DATA_/ADZ/V_MDC_MPG_S.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADZ/MDC_MPG_SP WHERE
(VIM_WHERETAB) .
    CLEAR /ADZ/V_MDC_MPG_S .
/ADZ/V_MDC_MPG_S-MANDT =
/ADZ/MDC_MPG_SP-MANDT .
/ADZ/V_MDC_MPG_S-MP_GROUP_ID =
/ADZ/MDC_MPG_SP-MP_GROUP_ID .
/ADZ/V_MDC_MPG_S-SERVPROV =
/ADZ/MDC_MPG_SP-SERVPROV .
/ADZ/V_MDC_MPG_S-USER_COMMENT =
/ADZ/MDC_MPG_SP-USER_COMMENT .
<VIM_TOTAL_STRUC> = /ADZ/V_MDC_MPG_S.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADZ/V_MDC_MPG_S .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADZ/V_MDC_MPG_S.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADZ/V_MDC_MPG_S-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_MPG_SP WHERE
  MP_GROUP_ID = /ADZ/V_MDC_MPG_S-MP_GROUP_ID AND
  SERVPROV = /ADZ/V_MDC_MPG_S-SERVPROV .
    IF SY-SUBRC = 0.
    DELETE /ADZ/MDC_MPG_SP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADZ/MDC_MPG_SP WHERE
  MP_GROUP_ID = /ADZ/V_MDC_MPG_S-MP_GROUP_ID AND
  SERVPROV = /ADZ/V_MDC_MPG_S-SERVPROV .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADZ/MDC_MPG_SP.
    ENDIF.
/ADZ/MDC_MPG_SP-MANDT =
/ADZ/V_MDC_MPG_S-MANDT .
/ADZ/MDC_MPG_SP-MP_GROUP_ID =
/ADZ/V_MDC_MPG_S-MP_GROUP_ID .
/ADZ/MDC_MPG_SP-SERVPROV =
/ADZ/V_MDC_MPG_S-SERVPROV .
/ADZ/MDC_MPG_SP-USER_COMMENT =
/ADZ/V_MDC_MPG_S-USER_COMMENT .
    IF SY-SUBRC = 0.
    UPDATE /ADZ/MDC_MPG_SP ##WARN_OK.
    ELSE.
    INSERT /ADZ/MDC_MPG_SP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADZ/V_MDC_MPG_S-UPD_FLAG,
STATUS_/ADZ/V_MDC_MPG_S-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADZ/V_MDC_MPG_S.
  SELECT SINGLE * FROM /ADZ/MDC_MPG_SP WHERE
MP_GROUP_ID = /ADZ/V_MDC_MPG_S-MP_GROUP_ID AND
SERVPROV = /ADZ/V_MDC_MPG_S-SERVPROV .
/ADZ/V_MDC_MPG_S-MANDT =
/ADZ/MDC_MPG_SP-MANDT .
/ADZ/V_MDC_MPG_S-MP_GROUP_ID =
/ADZ/MDC_MPG_SP-MP_GROUP_ID .
/ADZ/V_MDC_MPG_S-SERVPROV =
/ADZ/MDC_MPG_SP-SERVPROV .
/ADZ/V_MDC_MPG_S-USER_COMMENT =
/ADZ/MDC_MPG_SP-USER_COMMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADZ/V_MDC_MPG_S USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADZ/V_MDC_MPG_S-MP_GROUP_ID TO
/ADZ/MDC_MPG_SP-MP_GROUP_ID .
MOVE /ADZ/V_MDC_MPG_S-SERVPROV TO
/ADZ/MDC_MPG_SP-SERVPROV .
MOVE /ADZ/V_MDC_MPG_S-MANDT TO
/ADZ/MDC_MPG_SP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADZ/MDC_MPG_SP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADZ/MDC_MPG_SP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADZ/MDC_MPG_SP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
