FUNCTION-POOL z_car_rental_screens.         "MESSAGE-ID ..

* SELECTION SCREEN FOR CUSTOMER ID

SELECTION-SCREEN BEGIN OF SCREEN 1100
  AS WINDOW TITLE text-cid.

PARAMETERS id TYPE zcustomers-id.
SELECTION-SCREEN END OF SCREEN 1100.

* SELECTION SCREEN FOR RESERVATION DATA

SELECTION-SCREEN BEGIN OF SCREEN 1200
  AS WINDOW TITLE text-rsv.

PARAMETERS category TYPE zcars-category OBLIGATORY VALUE CHECK.
PARAMETERS day_from TYPE zreservations-date_from.
PARAMETERS day_to TYPE zreservations-date_to.
SELECTION-SCREEN END OF SCREEN 1200.

* INPUT CHECK FOR SELECTION SCREEN
AT SELECTION-SCREEN.
  CASE sy-dynnr.
    WHEN 1200.
      IF day_to < day_from.
        MESSAGE 'DAY_TO must not be before DAY_FROM'
          TYPE 'E'.
      ENDIF.
  ENDCASE.
