*&---------------------------------------------------------------------*
*& Include /ADESSO/MT_MIGTOOL_TOP                            Modulpool        /ADESSO/MT_MIGTOOL
*&
*&---------------------------------------------------------------------*

TABLES: /adesso/mt_firma.
DATA  fcode(20) TYPE c.

DATA:  firma(5)        TYPE  c
                       VALUE 'NVB'.

DATA: isu(1)  TYPE c,
      bka(1)  TYPE c,
      vert(1) TYPE c.

DATA:  file     LIKE  rlgrap-filename,
       exp_path LIKE  rlgrap-filename
                VALUE '\\srv8705\migWBD1\Entladung\',
       imp_path LIKE  rlgrap-filename
               VALUE  '\\srv8705\migWBD1\Beladung\'.


DATA:  imp_ext(3) TYPE c VALUE 'IMP',
       exp_ext(3) TYPE c VALUE 'EXP'.

DATA:  cbdelerr(1)     TYPE c. "Fehlertabelle löschen

* Beladung
DATA:   fn_par  LIKE  temfd-file  VALUE  'PARTNER',
        fn_pno  LIKE  temfd-file  VALUE  'PARTN_NOTE',
        fn_420  LIKE  temfd-file  VALUE  'BDC_TE420',
        fn_mru  LIKE  temfd-file  VALUE  'BDC_MRUNIT',
        fn_con  LIKE  temfd-file  VALUE  'CONNOBJ',
        fn_noc  LIKE  temfd-file  VALUE  'NOTE_CON',
        fn_pre  LIKE  temfd-file  VALUE  'PREMISE',
        fn_dlc  LIKE  temfd-file  VALUE  'DEVLOC',
        fn_nod  LIKE  temfd-file  VALUE  'NOTE_DLC',
        fn_dev  LIKE  temfd-file  VALUE  'DEVICE',
        fn_dir  LIKE  temfd-file  VALUE  'DEVINFO',
        fn_ins  LIKE  temfd-file  VALUE  'INSTLN',
        fn_ich  LIKE  temfd-file  VALUE  'INSTLNCHA',
        fn_inn  LIKE  temfd-file  VALUE  'INSTLN_NN',
        fn_icn  LIKE  temfd-file  VALUE 'INSTLNCHNN',
        efn_inn LIKE  temfd-file  VALUE  'INSTLN_NN',
        efn_icn LIKE  temfd-file  VALUE 'INSTLNCHNN',
        fn_fac  LIKE  temfd-file  VALUE  'FACTS',
        fn_rva  LIKE  temfd-file  VALUE  'REFVALUES',
        fn_acc  LIKE  temfd-file  VALUE  'ACCOUNT',
        fn_acs  LIKE  temfd-file  VALUE  'ACCOUNTS',
        fn_acn  LIKE  temfd-file  VALUE  'ACC_NOTE',
        fn_moi  LIKE  temfd-file  VALUE  'MOVE_IN',
        fn_moh  LIKE  temfd-file  VALUE  'MOVE_IN_H',
        fn_moo  LIKE  temfd-file  VALUE  'MOVE_OUT',
        fn_bct  LIKE  temfd-file  VALUE  'BCONTACT',
        fn_bcn  LIKE  temfd-file  VALUE  'BCONT_NOTE',
        fn_bpm  LIKE  temfd-file  VALUE  'BBP_MULT',
        fn_pay  LIKE  temfd-file  VALUE  'PAYMENT',
        fn_doc  LIKE  temfd-file  VALUE  'DOCUMENT',
        fn_ipl  LIKE  temfd-file  VALUE  'INSTPLAN',
        fn_inm  LIKE  temfd-file  VALUE  'INSTMGMT',
        fn_mrd  LIKE  temfd-file  VALUE  'METEREAD',
        fn_pod  LIKE  temfd-file  VALUE  'POD',
        fn_poc  LIKE  temfd-file  VALUE  'PODCHANGE',
        fn_pos  LIKE  temfd-file  VALUE  'PODSERVICE',
        fn_lot  LIKE  temfd-file  VALUE  'LOT',
        fn_cno  LIKE  temfd-file  VALUE  'CON_NOTE',
        fn_drt  LIKE  temfd-file  VALUE  'DEVICERATE',
        fn_pad  LIKE  temfd-file  VALUE  'PAYDOC',
        fn_lop  LIKE  temfd-file  VALUE  'LOADPROF',
        fn_dno  LIKE  temfd-file  VALUE  'DLC_NOTE',
        fn_dcd  LIKE  temfd-file  VALUE  'DISC_DOC',
        fn_dco  LIKE  temfd-file  VALUE  'DISC_ORDER',
        fn_dce  LIKE  temfd-file  VALUE  'DISC_ENTER',
        fn_dcr  LIKE  temfd-file  VALUE  'DISC_RCORD',
        fn_dcm  LIKE  temfd-file  VALUE  'DISC_RCENT',
        fn_dgr  LIKE  temfd-file  VALUE  'DEVGRP',
        fn_srt  LIKE  temfd-file  VALUE  'STRT_ROUTE',
        fn_reg  LIKE  temfd-file  VALUE  'ADRSTREET'.

* Entladung
DATA:   efn_par LIKE  temfd-file  VALUE  'PARTNER',
        efn_pno LIKE  temfd-file  VALUE  'PARTN_NOTE',
        efn_420 LIKE  temfd-file  VALUE  'BDC_TE420',
        efn_mru LIKE  temfd-file  VALUE  'BDC_MRUNIT',
        efn_con LIKE  temfd-file  VALUE  'CONNOBJ',
        efn_noc LIKE  temfd-file  VALUE  'NOTE_CON',
        efn_pre LIKE  temfd-file  VALUE  'PREMISE',
        efn_dlc LIKE  temfd-file  VALUE  'DEVLOC',
        efn_nod LIKE  temfd-file  VALUE  'NOTE_DLC',
        efn_dev LIKE  temfd-file  VALUE  'DEVICE',
        efn_dir LIKE  temfd-file  VALUE  'DEVINFO',
        efn_ins LIKE  temfd-file  VALUE  'INSTLN',
        efn_ich LIKE  temfd-file  VALUE  'INSTLNCHA',
        efn_fac LIKE  temfd-file  VALUE  'FACTS',
        efn_rva LIKE  temfd-file  VALUE  'REFVALUES',
        efn_acc LIKE  temfd-file  VALUE  'ACCOUNT',
        efn_acs LIKE  temfd-file  VALUE  'ACCOUNTS',
        efn_acn LIKE  temfd-file  VALUE  'ACC_NOTE',
        efn_moi LIKE  temfd-file  VALUE  'MOVE_IN',
        efn_moh LIKE  temfd-file  VALUE  'MOVE_IN_H',
        efn_moo LIKE  temfd-file  VALUE  'MOVE_OUT',
        efn_bct LIKE  temfd-file  VALUE  'BCONTACT',
        efn_bcn LIKE  temfd-file  VALUE  'BCONT_NOTE',
        efn_bpm LIKE  temfd-file  VALUE  'BBP_MULT',
        efn_pay LIKE  temfd-file  VALUE  'PAYMENT',
        efn_doc LIKE  temfd-file  VALUE  'DOCUMENT',
        efn_ipl LIKE  temfd-file  VALUE  'INSTPLAN',
        efn_inm LIKE  temfd-file  VALUE  'INSTMGMT',
        efn_mrd LIKE  temfd-file  VALUE  'METEREAD',
        efn_pod LIKE  temfd-file  VALUE  'POD',
        efn_poc LIKE  temfd-file  VALUE  'PODCHANGE',
        efn_pos LIKE  temfd-file  VALUE  'PODSERVICE',
        efn_lot LIKE  temfd-file  VALUE  'LOT',
        efn_cno LIKE  temfd-file  VALUE  'CON_NOTE',
        efn_drt LIKE  temfd-file  VALUE  'DEVICERATE',
        efn_pad LIKE  temfd-file  VALUE  'PAYDOC',
        efn_lop LIKE  temfd-file  VALUE  'LOADPROF',
        efn_dno LIKE  temfd-file  VALUE  'DLC_NOTE',
        efn_dcd LIKE  temfd-file  VALUE  'DISC_DOC',
        efn_dco LIKE  temfd-file  VALUE  'DISC_ORDER',
        efn_dce LIKE  temfd-file  VALUE  'DISC_ENTER',
        efn_dcr LIKE  temfd-file  VALUE  'DISC_RCORD',
        efn_dcm LIKE  temfd-file  VALUE  'DISC_RCENT',
        efn_dgr LIKE  temfd-file  VALUE  'DEVGRP',
        efn_srt LIKE  temfd-file  VALUE  'STRT_ROUTE',
        efn_reg LIKE  temfd-file  VALUE  'ADRSTEET'.

* Beladung
DATA:   cb_par(1) TYPE  c,
        cb_pno(1) TYPE  c,
        cb_420(1) TYPE  c,
        cb_mru(1) TYPE  c,
        cb_con(1) TYPE  c,
        cb_noc(1) TYPE  c,
        cb_pre(1) TYPE  c,
        cb_dlc(1) TYPE  c,
        cb_nod(1) TYPE  c,
        cb_dev(1) TYPE  c,
        cb_dir(1) TYPE  c,
        cb_ins(1) TYPE  c,
        cb_ich(1) TYPE  c,
        cb_inn(1) TYPE  c,
        cb_icn(1) TYPE  c,
        cb_fac(1) TYPE  c,
        cb_rva(1) TYPE  c,
        cb_acc(1) TYPE  c,
        cb_acs(1) TYPE  c,
        cb_acn(1) TYPE  c,
        cb_moi(1) TYPE  c,
        cb_moh(1) TYPE  c,
        cb_moo(1) TYPE  c,
        cb_bct(1) TYPE  c,
        cb_bcn(1) TYPE  c,
        cb_bpm(1) TYPE  c,
        cb_pay(1) TYPE  c,
        cb_doc(1) TYPE  c,
        cb_ipl(1) TYPE  c,
        cb_inm(1) TYPE  c,
        cb_mrd(1) TYPE  c,
        cb_pod(1) TYPE  c,
        cb_poc(1) TYPE  c,
        cb_pos(1) TYPE  c,
        cb_lot(1) TYPE  c,
        cb_cno(1) TYPE  c,
        cb_drt(1) TYPE  c,
        cb_pad(1) TYPE  c,
        cb_lop(1) TYPE  c,
        cb_dno(1) TYPE  c,
        cb_dcd(1) TYPE  c,
        cb_dco(1) TYPE  c,
        cb_dce(1) TYPE  c,
        cb_dcr(1) TYPE  c,
        cb_dcm(1) TYPE  c,
        cb_dgr(1) TYPE  c,
        cb_srt(1) TYPE  c,
        cb_reg(1) TYPE  c.

* Entladung
DATA:   ecb_par(1) TYPE  c,
        ecb_pno(1) TYPE  c,
        ecb_420(1) TYPE  c,
        ecb_mru(1) TYPE  c,
        ecb_con(1) TYPE  c,
        ecb_noc(1) TYPE  c,
        ecb_pre(1) TYPE  c,
        ecb_dlc(1) TYPE  c,
        ecb_nod(1) TYPE  c,
        ecb_dev(1) TYPE  c,
        ecb_dir(1) TYPE  c,
        ecb_ins(1) TYPE  c,
        ecb_ich(1) TYPE  c,
        ecb_inn(1) TYPE  c,
        ecb_icn(1) TYPE  c,
        ecb_fac(1) TYPE  c,
        ecb_rva(1) TYPE  c,
        ecb_acc(1) TYPE  c,
        ecb_acs(1) TYPE  c,
        ecb_acn(1) TYPE  c,
        ecb_moi(1) TYPE  c,
        ecb_moh(1) TYPE  c,
        ecb_moo(1) TYPE  c,
        ecb_bct(1) TYPE  c,
        ecb_bcn(1) TYPE  c,
        ecb_bpm(1) TYPE  c,
        ecb_pay(1) TYPE  c,
        ecb_doc(1) TYPE  c,
        ecb_ipl(1) TYPE  c,
        ecb_inm(1) TYPE  c,
        ecb_mrd(1) TYPE  c,
        ecb_pod(1) TYPE  c,
        ecb_poc(1) TYPE  c,
        ecb_pos(1) TYPE  c,
        ecb_lot(1) TYPE  c,
        ecb_cno(1) TYPE  c,
        ecb_drt(1) TYPE  c,
        ecb_pad(1) TYPE  c,
        ecb_lop(1) TYPE  c,
        ecb_dno(1) TYPE  c,
        ecb_dcd(1) TYPE  c,
        ecb_dco(1) TYPE  c,
        ecb_dce(1) TYPE  c,
        ecb_dcr(1) TYPE  c,
        ecb_dcm(1) TYPE  c,
        ecb_dgr(1) TYPE  c,
        ecb_srt(1) TYPE  c,
        ecb_reg(1) TYPE  c.


DATA:   p_step(6)  TYPE n  VALUE '1000',
        p_split(6) TYPE n.


DATA:  iscreen         LIKE TABLE OF  screen  WITH HEADER LINE.

DATA:  job_name      LIKE tbtcjob-jobname.
DATA:  gestartet(1)  TYPE  c.
DATA:  jobname       LIKE  tbtcjob-jobname.
DATA:  jobnumber     LIKE  tbtcjob-jobcount.
DATA:  targetserver  LIKE  btctgtsrvr-srvname.
