*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 15.09.2015 at 14:02:37
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /ADESSO/V_BPM_TX................................*
FORM GET_DATA_/ADESSO/V_BPM_TX.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ADESSO/BPM_TXT WHERE
(VIM_WHERETAB) .
    CLEAR /ADESSO/V_BPM_TX .
/ADESSO/V_BPM_TX-MANDT =
/ADESSO/BPM_TXT-MANDT .
/ADESSO/V_BPM_TX-PROC_ID =
/ADESSO/BPM_TXT-PROC_ID .
/ADESSO/V_BPM_TX-PROC_VERSION =
/ADESSO/BPM_TXT-PROC_VERSION .
/ADESSO/V_BPM_TX-STEPNO =
/ADESSO/BPM_TXT-STEPNO .
/ADESSO/V_BPM_TX-CHKID =
/ADESSO/BPM_TXT-CHKID .
/ADESSO/V_BPM_TX-EXCN_NAME =
/ADESSO/BPM_TXT-EXCN_NAME .
/ADESSO/V_BPM_TX-TITLE =
/ADESSO/BPM_TXT-TITLE .
/ADESSO/V_BPM_TX-DESCRIPTION =
/ADESSO/BPM_TXT-DESCRIPTION .
<VIM_TOTAL_STRUC> = /ADESSO/V_BPM_TX.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ADESSO/V_BPM_TX .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ADESSO/V_BPM_TX.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ADESSO/V_BPM_TX-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_TXT WHERE
  PROC_ID = /ADESSO/V_BPM_TX-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPM_TX-PROC_VERSION AND
  STEPNO = /ADESSO/V_BPM_TX-STEPNO AND
  CHKID = /ADESSO/V_BPM_TX-CHKID AND
  EXCN_NAME = /ADESSO/V_BPM_TX-EXCN_NAME .
    IF SY-SUBRC = 0.
    DELETE /ADESSO/BPM_TXT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ADESSO/BPM_TXT WHERE
  PROC_ID = /ADESSO/V_BPM_TX-PROC_ID AND
  PROC_VERSION = /ADESSO/V_BPM_TX-PROC_VERSION AND
  STEPNO = /ADESSO/V_BPM_TX-STEPNO AND
  CHKID = /ADESSO/V_BPM_TX-CHKID AND
  EXCN_NAME = /ADESSO/V_BPM_TX-EXCN_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ADESSO/BPM_TXT.
    ENDIF.
/ADESSO/BPM_TXT-MANDT =
/ADESSO/V_BPM_TX-MANDT .
/ADESSO/BPM_TXT-PROC_ID =
/ADESSO/V_BPM_TX-PROC_ID .
/ADESSO/BPM_TXT-PROC_VERSION =
/ADESSO/V_BPM_TX-PROC_VERSION .
/ADESSO/BPM_TXT-STEPNO =
/ADESSO/V_BPM_TX-STEPNO .
/ADESSO/BPM_TXT-CHKID =
/ADESSO/V_BPM_TX-CHKID .
/ADESSO/BPM_TXT-EXCN_NAME =
/ADESSO/V_BPM_TX-EXCN_NAME .
/ADESSO/BPM_TXT-TITLE =
/ADESSO/V_BPM_TX-TITLE .
/ADESSO/BPM_TXT-DESCRIPTION =
/ADESSO/V_BPM_TX-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE /ADESSO/BPM_TXT .
    ELSE.
    INSERT /ADESSO/BPM_TXT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ADESSO/V_BPM_TX-UPD_FLAG,
STATUS_/ADESSO/V_BPM_TX-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ADESSO/V_BPM_TX.
  SELECT SINGLE * FROM /ADESSO/BPM_TXT WHERE
PROC_ID = /ADESSO/V_BPM_TX-PROC_ID AND
PROC_VERSION = /ADESSO/V_BPM_TX-PROC_VERSION AND
STEPNO = /ADESSO/V_BPM_TX-STEPNO AND
CHKID = /ADESSO/V_BPM_TX-CHKID AND
EXCN_NAME = /ADESSO/V_BPM_TX-EXCN_NAME .
/ADESSO/V_BPM_TX-MANDT =
/ADESSO/BPM_TXT-MANDT .
/ADESSO/V_BPM_TX-PROC_ID =
/ADESSO/BPM_TXT-PROC_ID .
/ADESSO/V_BPM_TX-PROC_VERSION =
/ADESSO/BPM_TXT-PROC_VERSION .
/ADESSO/V_BPM_TX-STEPNO =
/ADESSO/BPM_TXT-STEPNO .
/ADESSO/V_BPM_TX-CHKID =
/ADESSO/BPM_TXT-CHKID .
/ADESSO/V_BPM_TX-EXCN_NAME =
/ADESSO/BPM_TXT-EXCN_NAME .
/ADESSO/V_BPM_TX-TITLE =
/ADESSO/BPM_TXT-TITLE .
/ADESSO/V_BPM_TX-DESCRIPTION =
/ADESSO/BPM_TXT-DESCRIPTION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ADESSO/V_BPM_TX USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ADESSO/V_BPM_TX-PROC_ID TO
/ADESSO/BPM_TXT-PROC_ID .
MOVE /ADESSO/V_BPM_TX-PROC_VERSION TO
/ADESSO/BPM_TXT-PROC_VERSION .
MOVE /ADESSO/V_BPM_TX-STEPNO TO
/ADESSO/BPM_TXT-STEPNO .
MOVE /ADESSO/V_BPM_TX-CHKID TO
/ADESSO/BPM_TXT-CHKID .
MOVE /ADESSO/V_BPM_TX-EXCN_NAME TO
/ADESSO/BPM_TXT-EXCN_NAME .
MOVE /ADESSO/V_BPM_TX-MANDT TO
/ADESSO/BPM_TXT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ADESSO/BPM_TXT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ADESSO/BPM_TXT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ADESSO/BPM_TXT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
