interface /ADESSO/IF_BPM_EIDE_CO
  public .


  constants GC_TRANS_REASON_CODE_ZE6 type /IDXGC/DE_MSGTRANSREASON value 'ZE6' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZE9 type /IDXGC/DE_MSGTRANSREASON value 'ZE9' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF0 type /IDXGC/DE_MSGTRANSREASON value 'ZF0' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF1 type /IDXGC/DE_MSGTRANSREASON value 'ZF1' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF2 type /IDXGC/DE_MSGTRANSREASON value 'ZF2' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF3 type /IDXGC/DE_MSGTRANSREASON value 'ZF3' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF4 type /IDXGC/DE_MSGTRANSREASON value 'ZF4' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF5 type /IDXGC/DE_MSGTRANSREASON value 'ZF5' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF6 type /IDXGC/DE_MSGTRANSREASON value 'ZF6' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF7 type /IDXGC/DE_MSGTRANSREASON value 'ZF7' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZF8 type /IDXGC/DE_MSGTRANSREASON value 'ZF8' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZG7 type /IDXGC/DE_MSGTRANSREASON value 'ZG7' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZG8 type /IDXGC/DE_MSGTRANSREASON value 'ZG8' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZE7 type /IDXGC/DE_MSGTRANSREASON value 'ZE7' ##NO_TEXT.
  constants GC_TRANS_REASON_CODE_ZE8 type /IDXGC/DE_MSGTRANSREASON value 'ZE8' ##NO_TEXT.
  constants GC_CASE_PRIO_1 type EMMA_CPRIO value '1' ##NO_TEXT.
  constants GC_PROC_ID_8011 type /IDXGC/DE_PROC_ID value '8011' ##NO_TEXT.
  constants GC_PROC_ID_8012 type /IDXGC/DE_PROC_ID value '8012' ##NO_TEXT.
  constants GC_PROC_ID_8013 type /IDXGC/DE_PROC_ID value '8013' ##NO_TEXT.
  constants GC_PROC_ID_8014 type /IDXGC/DE_PROC_ID value '8014' ##NO_TEXT.
  constants GC_PROC_ID_8030 type /IDXGC/DE_PROC_ID value '8030' ##NO_TEXT.
  constants GC_PROC_ID_8031 type /IDXGC/DE_PROC_ID value '8031' ##NO_TEXT.
  constants GC_PROC_ID_8032 type /IDXGC/DE_PROC_ID value '8032' ##NO_TEXT.
  constants GC_PROC_ID_8033 type /IDXGC/DE_PROC_ID value '8033' ##NO_TEXT.
  constants GC_PROC_ID_8034 type /IDXGC/DE_PROC_ID value '8034' ##NO_TEXT.
  constants GC_CASE_STAT_1 type EMMA_CSTATUS value '1' ##NO_TEXT.
  constants GC_CASE_STAT_2 type EMMA_CSTATUS value '2' ##NO_TEXT.
  constants GC_CASE_PRIO_5 type EMMA_CPRIO value '5' ##NO_TEXT.
  constants GC_CASE_PRIO_2 type EMMA_CPRIO value '2' ##NO_TEXT.
  constants GC_CASE_PRIO_3 type EMMA_CPRIO value '3' ##NO_TEXT.
  constants GC_CASE_PRIO_4 type EMMA_CPRIO value '4' ##NO_TEXT.
endinterface.
